import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAuth } from '../../../../context/AuthContext'
import { useLanguage } from '../../../../context/LanguageContext'
import { isLocalTenantHost } from '../../../../config/tenantBranding'
import { resolveErpUserTenantBranding, resolveErpUserTenantKey } from '../resolveErpUserTenant'
import {
  buildDashboardSearchParams,
  buildEnquiryHref,
} from '../../../../utils/dashboardNavigation'
import erpAccountingAPI from '../../../../api/erp-accounting'
import { buildEntryAccountOptions, filterActiveAccounts } from '../accountDropdownHelpers'
import { ACCOUNT_TYPES } from '../../../../constants/accountTypes'
import {
  LEDGER_REFERENCE_TYPES,
  LEDGER_DEPARTMENTS,
  ENQUIRY_DETAILS_PANEL_STORAGE_KEY,
  ENQUIRY_STATEMENT_AUDIT_TOGGLE_STORAGE_KEY,
  INVENTORY_STOCK_CODE_SETTINGS_STORAGE_KEY,
  ACCOUNT_TYPE_ORDER,
  ERP_DASH_ALL_WIDGETS,
  DEFAULT_METAL_RATES,
} from '../../erpTabConstants'
import { formatTransactionAuditEntry, formatTransactionCommentKind, getTransactionBulkSelectionLabel } from '../../transactionWorkflow'
import { useERPTabStateAdapter } from '../useERPTabStateAdapter'
import { useErpDashUiState } from '../useErpDashUiState'
import { useErpDashWidgetData } from '../useErpDashWidgetData'
import { useFixingRegisterPanelDrag } from '../useFixingRegisterPanelDrag'
import { useFixingRegisterState } from '../useFixingRegisterState'
import { useJvFormState } from '../useJvFormState'
import { useJvModalChrome } from '../useJvModalChrome'
import { useFixingRegisterStockTypeOptions } from '../useFixingRegisterStockTypeOptions'
import { ERP_TAB_COLORS as C, TRANSACTION_STATUS_STYLES, ERP_EMPTY_CARD_STYLE, ERP_MODAL_BACKDROP_STYLE, ERP_MODAL_CARD_STYLE, ERP_MODAL_INPUT_STYLE } from '../erpTabPresentation'
import { useTransactionComposer } from '../useTransactionComposer'
import { useJournalVoucher } from '../useJournalVoucher'
import { useAccountEnquiryStatement } from '../accountEnquiry/useAccountEnquiryStatement'
import { useAccountEnquiryModalDrag } from '../accountEnquiry/useAccountEnquiryModalDrag'
import { useEnquiryDeepLinkEffects } from '../accountEnquiry/useEnquiryDeepLinkEffects'
import {
  fixingRegFmtQty,
  fixingRegFmtRate,
  fixingRegFmtAmt,
} from '../fixingRegisterUtils'

import { deriveErpAccessPolicy, getAvailableTransactionTypes } from '../accessPolicy'
import {
  DEFAULT_INVENTORY_STOCK_CODE_SETTINGS,
  createInventoryMappingForm,
  createInventoryProductForm,
  decodeInventoryCategoryMeta,
  decodeInventoryCategoryPairs,
  formatVatPercent,
  getTransactionActionLabels,
  getTransactionTypeLabels,
  resolveMainStockValueFromForm,
  resolveTransactionAttachmentUrl,
  titleCaseWords,
} from '../erpTabUtils'
import { useErpEnquiryMetalRatesSync } from '../useErpMetalRatesRealtime'
import { useErpLiveMetalSpotPrices } from '../useErpLiveMetalSpotPrices'
import useLiveMetalRates from '../../../../hooks/useLiveMetalRates'
import { useErpCustomers } from '../useErpCustomers'
import { useErpMappings } from '../useErpMappings'
import { useErpCurrencies } from '../useErpCurrencies'
import { useErpCustomerMargin, useErpSupplierMargin, useErpMarginContextMenuDismissal } from '../useErpMarginTabs'
import { useErpReportsController } from '../useErpReportsController'
import { useErpTransactionWorkflow } from '../useErpTransactionWorkflow'
import { useErpVoucherSource } from '../useErpVoucherSource'

import {
  liveRatesToMetalRatesState,
  resolveInventoryValuationUnitCost,
} from '../../../../utils/liveMetalRates'
import {
  formatAccountEnquiryExcessDisplay,
  getAccountEnquirySignedMetricColor,
  resolveExposureDirection,
  isMetalStatementEntry,
} from '../statementHelpers'
import { generateStatementHtml as buildStatementHtml } from '../statementPrintHtml'
import {
  canViewErpSubTab,
} from '../../../../utils/erpSubTabPermissions'
import {
  JV_MODE_META,
  buildJvDocNo as buildNextJvDocNo,
  convertJvAmountBetweenCurrencies,
  normalizeJvCurrencyCode,
  resolveJvModeMeta,
} from '../journalVoucherHelpers'
import {
  DEFAULT_BRANDING,
  DEFAULT_BRANDING_PROFILES,
  clampBrandingDimension,
} from '../ERPBrandingUtils'
import { resolveDocumentBranding } from '../documentBranding'
import { exchangeRateFromUnitsPerBase, resolveCurrencyRowByCode } from '../erpCurrencyRowHelpers'
import { buildBrandingLogoTag as buildBrandingLogoTagHelper, openPrintWindow as openPrintWindowHelper } from '../erpPrintHelpers'
import { useErpAccountEnquiryController } from '../useErpAccountEnquiryController'
import { useErpTabRouter } from '../useErpTabRouter'
import { useErpLedger } from '../useErpLedger'
import { useErpLedgerActions } from '../useErpLedgerActions'
import { useErpVendors } from '../useErpVendors'
import { useErpInventory } from '../useErpInventory'
import { useErpAccounts } from '../useErpAccounts'
import { useErpVendorActions } from '../useErpVendorActions'
import { useErpInventoryActions } from '../useErpInventoryActions'
import { useErpBranding } from '../useErpBranding'
import { useErpTransactions } from '../useErpTransactions'
import { useErpExportActions } from '../useErpExportActions'
import { useErpReferenceCrud } from '../useErpReferenceCrud'
import { useErpTransactionNavigation } from '../useErpTransactionNavigation'
import { useErpTabBindings } from '../useErpTabBindings'
import { EMPTY_VENDOR_DOCUMENT_FORM, EMPTY_VENDOR_FORM } from '../vendorFormDefaults'



export function useErpTabDomainActionsSlice(scope) {
  const {
    accountEnquiryCode,
    accountEnquiryData,
    accounts,
    activeTab,
    activeTabRef,
    brandingForm,
    canAccessERP,
    canAccessFixingRegister,
    canAccessInventory,
    canAccessReports,
    canAccessTransactions,
    canAccessVouchers,
    canLoadInventoryData,
    canLoadParties,
    canLoadReferenceData,
    canManageVendors,
    canViewLedger,
    canViewMappings,
    currencies,
    currencyForm,
    customerForm,
    customers,
    editingInventoryProductId,
    editingProductId,
    editingVendorId,
    editState,
    enquiryHistory,
    erpBaseCurrencyCode,
    fixingRegFilter,
    inventoryMappingForm,
    inventoryModalOffset,
    inventoryProductForm,
    inventoryProductModalOffset,
    inventoryProducts,
    inventoryStockCodeManualOverride,
    inventoryStockCodeSettings,
    isSuperAdmin,
    lastEnquiryDeepLinkKeyRef,
    ledgerFilters,
    ledgerMeta,
    ledgerVoucherTab,
    loadAccounts,
    loadCurrencies,
    loadCustomers,
    loadDashboard,
    loadMappings,
    mappingFilters,
    mappingForm,
    safeSummaryAccounts,
    selectedBrandingKey,
    selectedTransactionId,
    selectedVendorId,
    setAccountEnquiryCode,
    setAccountEnquiryData,
    setAccounts,
    setActiveTabGuarded,
    setBrandingForm,
    setBrandingPreviewLogo,
    setBrandingProfiles,
    setCurrencies,
    setCurrencyForm,
    setCustomerForm,
    setCustomers,
    setEditingInventoryProductId,
    setEditingProductId,
    setEditingVendorId,
    setEditState,
    setEnquiryHistory,
    setEnquiryLoading,
    setEnquiryStatus,
    setError,
    setFixingRegFilter,
    setInventoryLoading,
    setInventoryMappingForm,
    setInventoryModalDragging,
    setInventoryModalOffset,
    setInventoryProductForm,
    setInventoryProductModalDragging,
    setInventoryProductModalOffset,
    setInventoryProducts,
    setInventoryStockCodeManualOverride,
    setLedger,
    setLedgerLoading,
    setLedgerMeta,
    setMappingForm,
    setMappings,
    setPendingStatementPreview,
    setReportBranding,
    setSaving,
    setSelectedBrandingKey,
    setSelectedTransactionId,
    setSelectedVendorDetails,
    setSelectedVendorId,
    setShowCurrencyForm,
    setShowCustomerForm,
    setShowEnquiryLookupMenu,
    setShowEnquiryModal,
    setShowInventoryMappingModal,
    setShowInventoryProductModal,
    setShowMappingForm,
    setShowVendorForm,
    setStatementFilters,
    setStatementMetalCommodityEnabled,
    setStockMovements,
    setStockMovementsLoading,
    setTransactionMeta,
    setTransactions,
    setTransactionsLoading,
    setTransactionSummary,
    setVendorComplianceSummary,
    setVendorDocumentForm,
    setVendorForm,
    setVendorOverdueQueue,
    setVendorPaymentCalendar,
    setVendorPermissions,
    setVendors,
    setVendorsLoading,
    setVendorSummary,
    setVendorWorkflowReason,
    showInventoryMappingModal,
    showNotification,
    syncEnquiryUrl,
    token,
    transactionFilters,
    transactionMeta,
    transactions,
    user,
    vendorDocumentForm,
    vendorFilters,
    vendorForm,
    vendorPermissions,
    vendors,
    vendorWorkflowReason,
    baseCurrencyCode,
    fixingRegisterStockTypeOptions,
    inventoryCatalogProducts,
    inventoryMappingProducts,
    selectedInventoryStockType,
  } = scope

  const {
    loadReportBranding,
    handleBrandingLogoFile,
    handleSaveBranding,
    handleSelectBrandingProfile,
    handleCreateBrandingDraft,
    brandingPreview,
  } = useErpBranding({
    token,
    selectedBrandingKey,
    brandingForm,
    setBrandingProfiles,
    setSelectedBrandingKey,
    setReportBranding,
    setBrandingForm,
    setBrandingPreviewLogo,
    setSaving,
    setError,
    showNotification,
  })
  const {
    reports,
    reportsLoading,
    reportView,
    setReportView,
    reportFilters,
    setReportFilters,
    selectedReportAccountId,
    setSelectedReportAccountId,
    selectedReportAccountCode,
    setSelectedReportAccountCode,
    ledgerReportRows,
    handleTrialAccountDrilldown,
    handleReportAccountDrilldown,
  } = useErpReportsController({
    token,
    activeTab,
    canAccessERP,
    canAccessReports,
    accounts,
    loadAccounts,
    loadReportBranding,
    setError,
    api: erpAccountingAPI,
  })
  const {
    voucherSource,
    setVoucherSource,
    voucherSourceLoading,
    handleOpenVoucherSource,
  } = useErpVoucherSource({
    token,
    setError,
    api: erpAccountingAPI,
  })
  const { loadLedger } = useErpLedger({
    token,
    canViewLedger,
    canLoadReferenceData,
    canViewMappings,
    ledgerFilters,
    ledgerVoucherTab,
    ledgerMeta,
    setLoading: setLedgerLoading,
    setLedger,
    setLedgerMeta,
    setAccounts,
    setCurrencies,
    setMappings,
    setError,
  })
  const {
    loadVendors,
    loadVendorDetails,
    loadVendorPaymentCalendar,
    loadVendorComplianceSummary,
    loadVendorOverdueQueue,
  } = useErpVendors({
    token,
    canLoadParties,
    setLoading: setVendorsLoading,
    setVendors,
    setVendorSummary,
    setVendorPermissions,
    setSelectedVendorDetails,
    setVendorPaymentCalendar,
    setVendorComplianceSummary,
    setVendorOverdueQueue,
    setError,
  })
  const { loadInventory, loadStockLedger } = useErpInventory({
    token,
    canAccessInventory,
    canAccessFixingRegister,
    setLoading: setInventoryLoading,
    setInventoryProducts,
    setStockMovements,
    setStockMovementsLoading,
    setError,
  })
  const { loadTransactions, loadTransactionReferenceData } = useErpTransactions({
    token,
    canAccessTransactions,
    canAccessVouchers,
    canAccessFixingRegister,
    canLoadParties,
    canLoadInventoryData,
    canLoadReferenceData,
    canViewMappings,
    transactionFilters,
    transactionMeta,
    setLoading: setTransactionsLoading,
    setTransactions,
    setTransactionSummary,
    setTransactionMeta,
    setCustomers,
    setVendors,
    setInventoryProducts,
    setMappings,
    setAccounts,
    setCurrencies,
    setError,
  })
  const { handleJumpToTransaction } = useErpTransactionNavigation({
    setSelectedTransactionId,
    setVoucherSource,
    setActiveTabGuarded,
    loadTransactions,
    showNotification,
  })
  const {
    transactionForm,
    setTransactionForm,
    editingTransactionId,
    setEditingTransactionId: _setEditingTransactionId,
    isTransactionEditMode,
    resetTransactionComposer,
    populateTransactionForm,
    getTransactionValidationMessage: _getTransactionValidationMessage,
    handleCreateTransaction,
  } = useTransactionComposer({
    baseCurrencyCode,
    customers,
    vendors,
    currencies,
    token,
    loadTransactionReferenceData,
    loadTransactions,
    setError,
    setSaving,
    setSelectedTransactionId,
    showNotification,
    erpAccountingAPI,
  })
  const {
    selectedTransactionIds,
    setSelectedTransactionIds,
    transactionWorkflowNote,
    setTransactionWorkflowNote,
    transactionCommentDraft,
    setTransactionCommentDraft,
    transactionAttachmentInputKey,
    allVisibleTransactionsSelected,
    toggleTransactionSelection,
    toggleVisibleTransactionSelection,
    handleDeleteTransaction,
    handleTransactionAction,
    handleAddTransactionComment,
    handleSendTransactionChat,
    handleUploadTransactionAttachment,
    handleDeleteTransactionAttachment,
    handleBulkTransactionAction,
  } = useErpTransactionWorkflow({
    token,
    transactions,
    setTransactions,
    selectedTransactionId,
    setSelectedTransactionId,
    editingTransactionId,
    resetTransactionComposer,
    transactionForm,
    loadTransactions,
    loadDashboard,
    setError,
    setSaving,
    showNotification,
    api: erpAccountingAPI,
  })
  const {
    handleEditLedger,
    handleReverseLedger,
    handleReconcileLedger,
    handleSaveEditLedger,
  } = useErpLedgerActions({
    token,
    editState,
    setEditState,
    setSaving,
    setError,
    loadLedger,
    showNotification,
  })
  const {
    openEditModal: _openEditModal,
    closeEditModal,
    handleCreateCustomer,
    handleSaveEdit,
    handleCreateCurrency,
    handleSyncCurrencyMaster,
    handleCreateMapping,
    handleEditMapping,
    handleEditCurrency,
    handleEditCustomer,
    handleDeleteMapping,
    handleDeleteCurrency,
    handleDeleteCustomer,
  } = useErpReferenceCrud({
    token,
    erpBaseCurrencyCode,
    customerForm,
    currencyForm,
    mappingForm,
    editState,
    currencies,
    setCustomerForm,
    setCurrencyForm,
    setMappingForm,
    setShowCustomerForm,
    setShowCurrencyForm,
    setShowMappingForm,
    setEditState,
    setSaving,
    setError,
    showNotification,
    loadCustomers,
    loadAccounts,
    loadCurrencies,
    loadMappings,
    handleSaveEditLedger,
  })
  const {
    handleCreateVendor,
    handleVendorFilterSearch,
    handleVendorSelect,
    handleEditVendor,
    handleDeleteVendor,
    handleVendorWorkflowStatus,
    handleAddVendorDocument,
    handleVendorTableDocumentUpload,
    handleDeleteVendorDocument,
  } = useErpVendorActions({
    token,
    canManageVendors,
    vendorPermissions,
    vendorForm,
    editingVendorId,
    vendorFilters,
    vendorWorkflowReason,
    vendorDocumentForm,
    selectedVendorId,
    setVendorForm,
    setShowVendorForm,
    setEditingVendorId,
    setSelectedVendorId,
    setSelectedVendorDetails,
    setVendorWorkflowReason,
    setVendorDocumentForm,
    setSaving,
    setError,
    showNotification,
    loadVendors,
    loadVendorDetails,
    loadVendorPaymentCalendar,
    loadVendorComplianceSummary,
    loadVendorOverdueQueue,
  })
  const {
    resetInventoryMappingForm,
    resetInventoryProductForm,
    handleInventoryModalDragStart,
    handleInventoryProductModalDragStart,
    handleCreateProduct,
    handleEditProduct,
    handleDeleteProduct,
    handleCreateInventoryCatalogProduct,
    handleEditInventoryCatalogProduct,
    handleDeleteInventoryCatalogProduct,
  } = useErpInventoryActions({
    token,
    isSuperAdmin,
    inventoryMappingForm,
    inventoryProductForm,
    inventoryMappingProducts,
    inventoryCatalogProducts,
    inventoryStockCodeSettings,
    inventoryStockCodeManualOverride,
    editingProductId,
    editingInventoryProductId,
    selectedInventoryStockType,
    showInventoryMappingModal,
    inventoryModalOffset,
    inventoryProductModalOffset,
    setInventoryMappingForm,
    setInventoryProductForm,
    setInventoryStockCodeManualOverride,
    setInventoryModalOffset,
    setInventoryModalDragging,
    setInventoryProductModalOffset,
    setInventoryProductModalDragging,
    setEditingProductId,
    setEditingInventoryProductId,
    setShowInventoryMappingModal,
    setShowInventoryProductModal,
    setSaving,
    setError,
    showNotification,
    loadInventory,
  })
  const {
    loadEnquiryHistory,
    fetchAccountEnquiryByCode,
    handleOpenAccountSummaryFromTree,
    handleAccountEnquiry,
  } = useErpAccountEnquiryController({
    user,
    token,
    safeSummaryAccounts,
    accountEnquiryCode,
    accountEnquiryData,
    enquiryHistory,
    setAccountEnquiryCode,
    setAccountEnquiryData,
    setEnquiryLoading,
    setShowEnquiryLookupMenu,
    setEnquiryStatus,
    setShowEnquiryModal,
    setPendingStatementPreview,
    setStatementFilters,
    setStatementMetalCommodityEnabled,
    setEnquiryHistory,
    setError,
    showNotification,
    syncEnquiryUrl,
    lastEnquiryDeepLinkKeyRef,
    setActiveTabGuarded,
  })
  useErpTabRouter({
    activeTab,
    activeTabRef,
    token,
    user,
    canAccessERP,
    canAccessTransactions,
    canAccessVouchers,
    canAccessFixingRegister,
    accounts,
    customers,
    currencies,
    inventoryProducts,
    fixingRegisterStockTypeOptions,
    fixingRegFilter,
    setFixingRegFilter,
    ledgerFilters,
    ledgerVoucherTab,
    mappingFilters,
    selectedTransactionId,
    selectedVendorId,
    transactions,
    setError,
    setSelectedTransactionId,
    setSelectedTransactionIds,
    loadAccounts,
    loadCustomers,
    loadVendors,
    loadVendorDetails,
    loadVendorPaymentCalendar,
    loadVendorComplianceSummary,
    loadVendorOverdueQueue,
    loadTransactions,
    loadReportBranding,
    loadInventory,
    loadStockLedger,
    loadCurrencies,
    loadLedger,
    loadMappings,
  })

  return {
    allVisibleTransactionsSelected,
    brandingPreview,
    closeEditModal,
    editingTransactionId,
    fetchAccountEnquiryByCode,
    getTransactionValidationMessage: _getTransactionValidationMessage,
    handleAccountEnquiry,
    handleAddTransactionComment,
    handleAddVendorDocument,
    handleBrandingLogoFile,
    handleBulkTransactionAction,
    handleCreateBrandingDraft,
    handleCreateCurrency,
    handleCreateCustomer,
    handleCreateInventoryCatalogProduct,
    handleCreateMapping,
    handleCreateProduct,
    handleCreateTransaction,
    handleCreateVendor,
    handleDeleteCurrency,
    handleDeleteCustomer,
    handleDeleteInventoryCatalogProduct,
    handleDeleteMapping,
    handleDeleteProduct,
    handleDeleteTransaction,
    handleDeleteTransactionAttachment,
    handleDeleteVendor,
    handleDeleteVendorDocument,
    handleEditCurrency,
    handleEditCustomer,
    handleEditInventoryCatalogProduct,
    handleEditLedger,
    handleEditMapping,
    handleEditProduct,
    handleEditVendor,
    handleInventoryModalDragStart,
    handleInventoryProductModalDragStart,
    handleJumpToTransaction,
    handleOpenAccountSummaryFromTree,
    handleOpenVoucherSource,
    handleReconcileLedger,
    handleReportAccountDrilldown,
    handleReverseLedger,
    handleSaveBranding,
    handleSaveEdit,
    handleSaveEditLedger,
    handleSelectBrandingProfile,
    handleSendTransactionChat,
    handleSyncCurrencyMaster,
    handleTransactionAction,
    handleTrialAccountDrilldown,
    handleUploadTransactionAttachment,
    handleVendorFilterSearch,
    handleVendorSelect,
    handleVendorTableDocumentUpload,
    handleVendorWorkflowStatus,
    isTransactionEditMode,
    ledgerReportRows,
    loadEnquiryHistory,
    loadInventory,
    loadLedger,
    loadReportBranding,
    loadStockLedger,
    loadTransactionReferenceData,
    loadTransactions,
    loadVendorComplianceSummary,
    loadVendorDetails,
    loadVendorOverdueQueue,
    loadVendorPaymentCalendar,
    loadVendors,
    openEditModal: _openEditModal,
    populateTransactionForm,
    reportFilters,
    reports,
    reportsLoading,
    reportView,
    resetInventoryMappingForm,
    resetInventoryProductForm,
    resetTransactionComposer,
    selectedReportAccountCode,
    selectedReportAccountId,
    selectedTransactionIds,
    setEditingTransactionId: _setEditingTransactionId,
    setReportFilters,
    setReportView,
    setSelectedReportAccountCode,
    setSelectedReportAccountId,
    setSelectedTransactionIds,
    setTransactionCommentDraft,
    setTransactionForm,
    setTransactionWorkflowNote,
    setVoucherSource,
    toggleTransactionSelection,
    toggleVisibleTransactionSelection,
    transactionAttachmentInputKey,
    transactionCommentDraft,
    transactionForm,
    transactionWorkflowNote,
    voucherSource,
    voucherSourceLoading,
  }
}
