/**
 * LoopC built-in agent — max capability without external LLM.
 * Live tenant data, project analysis, knowledge base, fix playbooks, conversation memory.
 */

const {
  matchKnowledge,
  matchFixPlaybooks,
  detectBuiltinIntent,
  resolveNavigation,
  MODULE_GUIDES,
} = require('./loopcKnowledgeBase')

function formatPlaybookReply(playbooks, lastError, pageContext) {
  const lines = ['**Fix plan**']
  if (lastError?.status) {
    lines.push(`\nCaptured error: HTTP **${lastError.status}** — ${lastError.message || 'Unknown'}`)
    if (lastError.url) lines.push(`Endpoint: \`${lastError.url}\``)
  }
  if (pageContext?.tab) lines.push(`You were on: **${pageContext.tab}** tab`)

  playbooks.forEach((pb, idx) => {
    lines.push(`\n**${idx + 1}. ${pb.id.replace(/-/g, ' ')}**`)
    pb.steps.forEach((step, i) => lines.push(`${i + 1}. ${step}`))
  })

  if (!lastError?.status) {
    lines.push('\nIf this does not help, describe what you clicked and any error text you see.')
  }
  return lines.join('\n')
}

function fmtNum(n, digits = 0) {
  if (n == null || Number.isNaN(n)) return '—'
  return Number(n).toLocaleString(undefined, { maximumFractionDigits: digits })
}

function fmtMoney(n) {
  if (n == null) return '—'
  return `$${fmtNum(n, 0)}`
}

function feedLabel(metals) {
  if (!metals || metals.error) return 'unavailable'
  if (!metals.live) return 'offline'
  const ft = String(metals.feedType || '')
  if (ft.includes('mt4') || ft === 'mt4-bridge') return 'MT4 live'
  return 'server market feed'
}

function buildMarketReply(ctx) {
  const { user, tenant, metals } = ctx
  if (metals?.error) {
    return `Hi ${user.name}! Could not load live prices (${metals.error}). Say **fix MT4 prices** for step-by-step bridge setup.`
  }
  const lines = [
    `**Live metal prices (${String(tenant).toUpperCase()})**`,
    `- Gold: **${fmtNum(metals.gold, 2)}** ${metals.currency}/${metals.unit}`,
    `- Silver: **${fmtNum(metals.silver, 2)}**`,
    `- Platinum: **${fmtNum(metals.platinum, 2)}**`,
    `- Feed: **${feedLabel(metals)}**`,
  ]
  if (metals.updatedAt) lines.push(`- Updated: ${new Date(metals.updatedAt).toLocaleString()}`)
  if (metals.message) lines.push(`- ${metals.message}`)
  if (ctx.savedRates && !metals.live) {
    lines.push(`\n_Saved rates in DB: Gold ${fmtNum(ctx.savedRates.gold, 2)} (${ctx.savedRates.source})_`)
  }
  if (!metals.live) lines.push('\nAsk **fix MT4** if you need live bridge prices.')
  return lines.join('\n')
}

function buildAlertsSection(snapshot) {
  if (!snapshot.alerts?.length) return '✅ No critical alerts right now.'
  return snapshot.alerts.map((a) => {
    const icon = a.level === 'error' ? '🔴' : a.level === 'warning' ? '🟡' : '🔵'
    return `${icon} ${a.text}`
  }).join('\n')
}

function buildRecommendations(snapshot) {
  const recs = []
  const { tasks, erp, crm, metals, lastError } = snapshot

  if (tasks.overdue > 0) recs.push(`Clear **${tasks.overdue} overdue task(s)** — Overview → Tasks`)
  if (erp.lowStock > 0) recs.push(`Restock **${erp.lowStock} low inventory item(s)** — ERP → Inventory`)
  if (crm.overdueFollowups > 0) recs.push(`Complete **${crm.overdueFollowups} CRM follow-up(s)** — CRM → Activities`)
  if (erp.vouchers?.draft > 0) recs.push(`Post or discard **${erp.vouchers.draft} draft voucher(s)** — ERP → Vouchers`)
  if (metals && !metals.error && !metals.live) recs.push('Restore **MT4 bridge** for live gold/silver/platinum on the top bar')
  if (lastError?.status === 403) recs.push('Review **user permissions** — Admin → Users')
  if (lastError?.status === 401) recs.push('**Re-login** — session may have expired')

  if (recs.length === 0) {
    recs.push('System looks healthy — run reports in ERP or check CRM pipeline for business insights.')
  }
  return recs.map((r, i) => `${i + 1}. ${r}`).join('\n')
}

function buildAnalyzeReply(ctx) {
  const { user, tenant, snapshot } = ctx
  const { erp, crm, hr, tasks, metals, build, pageContext } = snapshot
  const tenantUp = String(tenant).toUpperCase()

  return [
    `# ${tenantUp} — Company Analysis`,
    `_Generated by LoopC · ${new Date().toLocaleString()}_`,
    '',
    '## Executive summary',
    `**${user.name}** (${user.role}${user.department ? ` · ${user.department}` : ''}) on **${tenantUp}**.`,
    `API build \`${(build?.commit || 'unknown').slice(0, 7)}\` · Page: **${pageContext?.tab || 'dashboard'}**`,
    '',
    '## Live status',
    buildMarketReply(ctx).split('\n').slice(1).join('\n'),
    '',
    '## Operations',
    `| Metric | Count |`,
    `|--------|------:|`,
    `| Open tasks | **${fmtNum(tasks.open)}** |`,
    `| Overdue tasks | **${fmtNum(tasks.overdue)}** |`,
    `| Employees (HR) | **${fmtNum(hr.employees)}** |`,
    '',
    '## ERP & Accounting',
    `| Metric | Count |`,
    `|--------|------:|`,
    `| Inventory items | **${fmtNum(erp.inventoryItems)}** |`,
    `| Low stock alerts | **${fmtNum(erp.lowStock)}** |`,
    `| Vendors | **${fmtNum(erp.vendors)}** |`,
    `| Customers | **${fmtNum(erp.customers)}** |`,
    `| Chart of accounts | **${fmtNum(erp.accounts)}** |`,
    `| Ledger entries | **${fmtNum(erp.ledgerEntries)}** |`,
    `| Draft vouchers | **${fmtNum(erp.vouchers?.draft)}** |`,
    `| Pending approval | **${fmtNum(erp.vouchers?.pending)}** |`,
    `| Posted vouchers | **${fmtNum(erp.vouchers?.posted)}** |`,
    '',
    '## Sales (CRM)',
    `| Metric | Value |`,
    `|--------|------:|`,
    `| Contacts | **${fmtNum(crm.contacts)}** |`,
    `| Active leads | **${fmtNum(crm.activeLeads)}** |`,
    `| Hot leads | **${fmtNum(crm.hotLeads)}** |`,
    `| Pipeline | **${fmtMoney(crm.pipelineValue)}** |`,
    `| Win rate | **${crm.winRate ?? '—'}%** |`,
    `| Overdue follow-ups | **${fmtNum(crm.overdueFollowups)}** |`,
    '',
    '## Alerts',
    buildAlertsSection(snapshot),
    '',
    '## Recommended actions',
    buildRecommendations(snapshot),
    '',
    '_Ask follow-ups: "low stock details", "recent vouchers", "fix MT4", or "how do vouchers work?"_',
  ].join('\n')
}

function buildSummaryReply(ctx) {
  const { user, tenant, snapshot } = ctx
  const { tasks, erp, crm, metals, build } = snapshot
  return [
    `Hello ${user.name}! **${String(tenant).toUpperCase()} — today's snapshot**`,
    '',
    '**Tasks**',
    `- Open: **${fmtNum(tasks.open)}** · Overdue: **${fmtNum(tasks.overdue)}**`,
    '',
    '**ERP**',
    `- Inventory: **${fmtNum(erp.inventoryItems)}** items (${fmtNum(erp.lowStock)} low stock)`,
    `- Vouchers: **${fmtNum(erp.vouchers?.draft)}** draft · **${fmtNum(erp.vouchers?.posted)}** posted`,
    '',
    '**CRM**',
    `- Pipeline: **${fmtMoney(crm.pipelineValue)}** · Hot leads: **${fmtNum(crm.hotLeads)}**`,
    '',
    '**Market**',
    `- Gold: **${fmtNum(metals?.gold, 2)}** · Feed: **${feedLabel(metals)}**`,
    '',
    `Build: \`${(build?.commit || '?').slice(0, 7)}\` · Agent: **LoopC Pro**`,
    '',
    'Say **analyze my company** for the full report.',
  ].join('\n')
}

function buildInventoryReply(ctx) {
  const { user, snapshot } = ctx
  const { erp, metals } = snapshot
  const lines = [
    `**Inventory status (${String(ctx.tenant).toUpperCase()})**`,
    `- Total items: **${fmtNum(erp.inventoryItems)}**`,
    `- Below minimum stock: **${fmtNum(erp.lowStock)}**`,
    `- Live metal feed: **${feedLabel(metals)}**`,
  ]
  if (erp.lowStock > 0) {
    lines.push('\n⚠️ Restock low items in **ERP → Inventory** — filter by quantity vs min threshold.')
  } else {
    lines.push('\n✅ No low-stock alerts.')
  }
  lines.push('\n**How-to:** ERP → Inventory → add/edit items, set min threshold, link ledger accounts for valuation.')
  return lines.join('\n')
}

function buildSalesReply(ctx) {
  const { user, snapshot } = ctx
  const { crm } = snapshot
  return [
    `**Sales & CRM (${String(ctx.tenant).toUpperCase()})**`,
    `- Contacts: **${fmtNum(crm.contacts)}**`,
    `- Active leads: **${fmtNum(crm.activeLeads)}** · Hot: **${fmtNum(crm.hotLeads)}**`,
    `- Deals in pipeline: **${fmtNum(crm.totalDeals)}** · Value: **${fmtMoney(crm.pipelineValue)}**`,
    `- Win rate: **${crm.winRate ?? '—'}%**`,
    `- Overdue follow-ups: **${fmtNum(crm.overdueFollowups)}**`,
    '',
    'Open **CRM tab** for pipeline board, lead temperature, and activity calendar.',
    crm.overdueFollowups > 0 ? '\n🟡 Prioritize overdue CRM follow-ups today.' : '',
  ].filter(Boolean).join('\n')
}

function buildFinanceReply(ctx) {
  const { snapshot } = ctx
  const { erp } = snapshot
  return [
    `**Finance snapshot (${String(ctx.tenant).toUpperCase()})**`,
    `- Chart of accounts: **${fmtNum(erp.accounts)}**`,
    `- Ledger entries: **${fmtNum(erp.ledgerEntries)}**`,
    `- Posted vouchers: **${fmtNum(erp.vouchers?.posted)}**`,
    `- Draft vouchers: **${fmtNum(erp.vouchers?.draft)}**`,
    `- Customers: **${fmtNum(erp.customers)}** · Vendors: **${fmtNum(erp.vendors)}**`,
    '',
    '**Reports:** ERP → Reports — trial balance, P&L, balance sheet, cash flow.',
    '**Finance tab:** budgets, expenses, invoices (operational finance).',
  ].join('\n')
}

function buildHrReply(ctx) {
  const { snapshot } = ctx
  const { hr, tasks } = snapshot
  return [
    `**HR snapshot (${String(ctx.tenant).toUpperCase()})**`,
    `- Employees: **${fmtNum(hr.employees)}**`,
    `- Open tasks (all depts): **${fmtNum(tasks.open)}**`,
    '',
    '**HR tab:** employee records, attendance, leave requests.',
    'Department heads manage their team; Super Admin sees all.',
  ].join('\n')
}

function buildAlertsReply(ctx) {
  const { user, snapshot } = ctx
  const { tasks } = snapshot
  const lines = [
    `**Alerts for ${user.name}**`,
    '',
    buildAlertsSection(snapshot),
  ]
  if (tasks.recent?.length) {
    lines.push('\n**Recent tasks:**')
    tasks.recent.forEach((t) => {
      lines.push(`- ${t.title} (${t.status}${t.dueDate ? ` · due ${new Date(t.dueDate).toLocaleDateString()}` : ''})`)
    })
  }
  if (snapshot.erp.recentVouchers?.length) {
    lines.push('\n**Recent vouchers:**')
    snapshot.erp.recentVouchers.forEach((v) => {
      lines.push(`- ${v.type} · ${v.status} · ${fmtMoney(v.amount)}${v.description ? ` — ${v.description}` : ''}`)
    })
  }
  return lines.join('\n')
}

function buildCapabilitiesReply(ctx) {
  const { user, tenant } = ctx
  return [
    `Hi ${user.name}! I'm **LoopC Pro** — your built-in AI for **${String(tenant).toUpperCase()}**. No API billing required.`,
    '',
    '**What I can do (with live data):**',
    '1. **Analyze my company** — full ERP + CRM + HR + market report',
    '2. **Today\'s summary** — tasks, inventory, pipeline, metal prices',
    '3. **Live metal prices** — gold, silver, platinum + MT4 feed status',
    '4. **Fix problems** — step-by-step playbooks from your prompt or last API error',
    '5. **Software help** — vouchers, ledger, inventory, CRM, HR, permissions, MT4',
    '6. **Upload files** — documents, PDF, CSV, images, audio, video (📎 button)',
    '7. **Voice input** — mic button for speech-to-text (Chrome/Edge)',
    '8. **Navigation** — "where is vouchers?" → exact tab path',
    '',
    '**Quick prompts:**',
    '- "Analyze my project"',
    '- "Show low stock"',
    '- "CRM pipeline status"',
    '- "Fix last error"',
    '- "How do I post a metal voucher?"',
    '',
    '_Optional: switch Engine to ChatGPT for open-ended questions (requires OpenAI billing)._',
  ].join('\n')
}

function buildNavigateReply(message) {
  const tab = resolveNavigation(message)
  if (tab) {
    return `Open **${tab}** from the main navigation bar.\n\nIf you don't see it, your role may not have that module enabled — ask Super Admin.`
  }
  return [
    '**Main modules:**',
    '- **ERP** → Vouchers, Ledger, Inventory, Vendors, Reports',
    '- **CRM** → Contacts, Leads, Deals, Activities',
    '- **HR** → Employees, Attendance, Leave',
    '- **Finance** → Budgets, Expenses, Invoices',
    '- **Operations / Production / Compliance / Training**',
    '',
    'Try: "where is vouchers?" or "open CRM pipeline"',
  ].join('\n')
}

function buildCompareReply(message) {
  const lower = String(message).toLowerCase()
  if (/mt4|market|live/.test(lower)) {
    return [
      '**MT4 live vs market fallback vs saved rates:**',
      '',
      '| Source | Speed | Accuracy | Requires |',
      '|--------|-------|----------|----------|',
      '| **MT4 bridge** | Real-time ticks | Broker spot (Equiti) | EA running + BridgeToken |',
      '| **Market fallback** | ~minutes | Server/API feed | No MT4 — auto when bridge down |',
      '| **Saved rates** | Manual | Last entered in ERP Settings | Admin update |',
      '',
      'Top bar shows MT4 when bridge is healthy; falls back automatically.',
    ].join('\n')
  }
  if (/draft|posted|voucher/.test(lower)) {
    return [
      '**Draft vs Posted vouchers:**',
      '- **Draft** — editable, no ledger impact',
      '- **Submitted/Approved** — workflow states before posting',
      '- **Posted** — creates ledger entries, locked for accounting',
    ].join('\n')
  }
  return 'Ask me to compare specific things: "MT4 vs market prices", "draft vs posted vouchers", "MG vs CG tenants".'
}

function buildHelpReply(ctx, message) {
  const hit = matchKnowledge(message)
  if (hit?.body) return hit.body
  if (hit?.id === 'navigation') return buildNavigateReply(message)

  const { user, tenant } = ctx
  return [
    `Hi ${user.name}! I'm **LoopC Pro** for **${String(tenant).toUpperCase()}**.`,
    '',
    '**Topics I know well:**',
    MODULE_GUIDES.filter((g) => g.body).slice(0, 8).map((g) => `- **${g.title}** — ask about ${g.keys.slice(0, 2).join(', ')}`).join('\n'),
    '',
    'Or try: **analyze my company**, **live metal prices**, **fix last error**.',
  ].join('\n')
}

function buildAttachmentReply(ctx, message) {
  const files = ctx.snapshot?.attachments || ctx.attachments || []
  const { user, tenant } = ctx
  if (!files.length) {
    return `Hi ${user.name}! Attach a file with the **📎 upload** button, then ask what you want analyzed.`
  }

  const lines = [
    `**Uploaded files analysis (${String(tenant).toUpperCase()})**`,
    `_LoopC Pro · ${files.length} file(s)_`,
    '',
  ]

  if (String(message || '').trim() && !/^analyze|review|summarize|what is this|explain/i.test(message)) {
    lines.push(`**Your question:** ${message.trim()}`, '')
  }

  files.forEach((file, idx) => {
    lines.push(`### ${idx + 1}. ${file.name}`)
    lines.push(`- Type: **${file.kind}** · ${file.summary || `${Math.round((file.size || 0) / 1024)} KB`}`)

    if (file.kind === 'image') {
      lines.push('- Image received. LoopC built-in cannot vision-analyze — switch **Engine → ChatGPT** for image description, or describe what you need from this image.')
    } else if (file.kind === 'audio' || file.kind === 'video') {
      lines.push(`- ${file.kind === 'audio' ? 'Audio' : 'Video'} received. Use **ChatGPT engine** for transcription/analysis, or type what you said.`)
    } else if (file.textExcerpt) {
      const excerpt = String(file.textExcerpt).split('\n').slice(0, 12).join('\n')
      lines.push('', '**Extracted preview:**', '```', excerpt, '```')
      if (file.stats?.rows) {
        lines.push(`\n_CSV stats: ${file.stats.rows} data rows, ${file.stats.columns} columns._`)
      }
      const keywords = extractKeywords(file.textExcerpt)
      if (keywords.length) lines.push(`\n**Key terms:** ${keywords.slice(0, 8).join(', ')}`)
    } else {
      lines.push('- Binary file stored. Describe what you want checked, or switch to **ChatGPT** for deeper analysis.')
    }
    lines.push('')
  })

  lines.push(
    '**Next steps:**',
    '1. Ask a follow-up about the file content',
    '2. Switch to **ChatGPT** for images, audio transcription, or complex docs',
    '3. Combine with live data: "compare this invoice to our vendors"',
  )

  return lines.join('\n')
}

function extractKeywords(text = '') {
  const stop = new Set(['the', 'and', 'for', 'with', 'this', 'that', 'from', 'have', 'are', 'was', 'were', 'your', 'you', 'our', 'not', 'but', 'all', 'can', 'will', 'has', 'had'])
  const counts = {}
  String(text).toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/)
    .filter((w) => w.length > 3 && !stop.has(w))
    .forEach((w) => { counts[w] = (counts[w] || 0) + 1 })
  return Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([w]) => w)
}

function buildGeneralReply(ctx, message) {
  const hit = matchKnowledge(message)
  if (hit?.body) return hit.body

  const { user } = ctx
  return [
    `Hello ${user.name}!`,
    '',
    'Try one of these:',
    '- **Analyze my company** — full live report',
    '- **Show today\'s summary** — quick snapshot',
    '- **Live metal prices** — gold, silver, platinum',
    '- **Fix last error** — diagnose from last API failure',
    '- **What can you do?** — full capability list',
    '- **📎 Upload** documents, images, audio, or video for analysis',
    '',
    'Or ask how to use **vouchers**, **ledger**, **CRM**, **MT4**, **permissions**.',
  ].join('\n')
}

function runBuiltinAgent({ message, context, history = [] }) {
  const intent = detectBuiltinIntent(message, history)
  const snapshot = context.snapshot || {
    user: context.user || { name: 'there' },
    tenant: context.tenant,
    erp: context.erp || {},
    crm: context.crm || {},
    hr: context.hr || {},
    tasks: context.tasks || {},
    metals: context.metals || {},
    alerts: context.alerts || [],
    build: context.build || {},
    pageContext: context.pageContext || {},
    lastError: context.lastError,
    savedRates: context.savedRates,
  }

  const ctx = {
    user: snapshot.user || { name: context.user?.name || 'there' },
    tenant: context.tenant || 'your company',
    metals: context.metals || {},
    snapshot,
    build: context.build || {},
    pageContext: context.pageContext || {},
    lastError: context.lastError,
    savedRates: context.savedRates,
    attachments: context.attachments || [],
  }

  if (context.attachments?.length) {
    return { reply: buildAttachmentReply(ctx, message), intent: 'attachment', mode: 'builtin' }
  }

  if (intent === 'fix') {
    const playbooks = matchFixPlaybooks(message, context.lastError)
    if (playbooks.length > 0) {
      return { reply: formatPlaybookReply(playbooks, context.lastError, context.pageContext), intent, mode: 'builtin' }
    }
    if (context.lastError?.status || context.lastError?.message) {
      return {
        reply: formatPlaybookReply([{
          id: 'generic',
          steps: [
            'Hard refresh (Ctrl+F5) and retry.',
            'Sign out and back in if session-related.',
            'Copy the error message for your admin.',
            'Say **fix MT4** or **fix permission 403** for specific playbooks.',
          ],
        }], context.lastError, context.pageContext),
        intent,
        mode: 'builtin',
      }
    }
    return {
      reply: [
        `Hi ${ctx.user.name}! I can fix problems from your **prompt** or the **last API error**.`,
        '',
        'Try:',
        '1. Reproduce the problem once (so I capture the error).',
        '2. Click **Fix last error** or describe the issue (e.g. "voucher save 403", "MT4 prices missing").',
        '',
        'I have playbooks for: MT4, permissions, session, CSRF, server errors, voucher save, deploy.',
      ].join('\n'),
      intent,
      mode: 'builtin',
    }
  }

  if (intent === 'analyze') return { reply: buildAnalyzeReply(ctx), intent, mode: 'builtin' }
  if (intent === 'market') return { reply: buildMarketReply(ctx), intent, mode: 'builtin' }
  if (intent === 'summary') return { reply: buildSummaryReply(ctx), intent, mode: 'builtin' }
  if (intent === 'inventory') return { reply: buildInventoryReply(ctx), intent, mode: 'builtin' }
  if (intent === 'sales') return { reply: buildSalesReply(ctx), intent, mode: 'builtin' }
  if (intent === 'finance') return { reply: buildFinanceReply(ctx), intent, mode: 'builtin' }
  if (intent === 'hr') return { reply: buildHrReply(ctx), intent, mode: 'builtin' }
  if (intent === 'alerts') return { reply: buildAlertsReply(ctx), intent, mode: 'builtin' }
  if (intent === 'capabilities') return { reply: buildCapabilitiesReply(ctx), intent, mode: 'builtin' }
  if (intent === 'navigate') return { reply: buildNavigateReply(message), intent, mode: 'builtin' }
  if (intent === 'compare') return { reply: buildCompareReply(message), intent, mode: 'builtin' }
  if (intent === 'help') return { reply: buildHelpReply(ctx, message), intent, mode: 'builtin' }

  const knowledgeHit = matchKnowledge(message)
  if (knowledgeHit?.body) return { reply: knowledgeHit.body, intent: 'help', mode: 'builtin' }

  return { reply: buildGeneralReply(ctx, message), intent: 'general', mode: 'builtin' }
}

module.exports = {
  runBuiltinAgent,
  detectBuiltinIntent,
  matchFixPlaybooks,
  matchKnowledge: matchKnowledge,
}
