import AccountEnquiryModal from './accountEnquiry/AccountEnquiryModal'
import StatementPreviewModal from './accountEnquiry/StatementPreviewModal'
import StatementExportOptionsModal from './StatementExportOptionsModal'
import ErpMappingTestModal from './ErpMappingTestModal'

export default function ERPTabModals({
  showMappingTest,
  setShowMappingTest,
  testMapping,
  colors,
  showEnquiryModal,
  setShowEnquiryModal,
  enquiryBackdropColor,
  enquiryModalOffset,
  enquiryModalDrag,
  beginEnquiryModalDrag,
  enquiryLoading,
  accountEnquiryCode,
  setAccountEnquiryCode,
  setShowEnquiryLookupMenu,
  showEnquiryLookupMenu,
  filteredGroupedSummaryAccounts,
  setEnquiryStatus,
  fetchAccountEnquiryByCode,
  enquiryStatus,
  accountEnquiryData,
  modalPositionRows,
  formatStatementValue,
  getSignedColor,
  formatDirectionalBalance,
  unfixedMetalEntries,
  formatStatementDate,
  fixedMetalSummary,
  unfixedMetalSummary,
  unknownFixMetalEntries,
  modalTotalFundsDisplay,
  modalRevaluationDisplay,
  modalNetEquityDisplay,
  modalMarginAmtDisplay,
  modalExcessDisplay,
  modalMarginPctDisplay,
  enquirySuppressMetalSpotMtm,
  enquiryLiveRecalcEnabled,
  hasMetalExposure,
  excessCurrency,
  setExcessCurrency,
  baseCurrencyCode,
  statementDisplayCurrencyOptions,
  filteredStatementEntries,
  recentPaymentReceiptEntry,
  resolveStatementReceiptNo,
  statementFilters,
  setStatementFilters,
  statementReferenceTypes,
  statementDepartments,
  setStatementMetalCommodityEnabled,
  statementMetalCommodityEnabled,
  statementFilterCurrencyOptions,
  statementMetalOptions,
  statementDisplayCurrency,
  showStatementAuditIds,
  setShowStatementAuditIds,
  statementTableRef,
  convertStatementDisplayAmount,
  convertStatementEntryAmounts,
  resolveMetalCode,
  statementSelectedMetalCode,
  pureWeightRunningByEntryKey,
  formatStatementNullableValue,
  canExportAccountSummary,
  handleViewStatement,
  buildAccountEnquiryHref,
  handleExportEnquiryPdf,
  getAccountEnquirySignedMetricColor,
  formatAccountEnquiryExcessDisplay,
  resolveExposureDirection,
  isMetalStatementEntry,
  showStatementPreview,
  setShowStatementPreview,
  statementPreviewTitle,
  statementPreviewHtml,
  statementPreviewLoading,
  exportOptionsOpen,
  setExportOptionsOpen,
  handlePrintStatement,
  handleDownloadStatementPdf,
}) {
  return (
    <>
      <ErpMappingTestModal
        open={showMappingTest}
        testMapping={testMapping}
        colors={colors}
        onClose={() => setShowMappingTest(false)}
      />
      <AccountEnquiryModal
        open={showEnquiryModal}
        onClose={() => setShowEnquiryModal(false)}
        enquiryBackdropColor={enquiryBackdropColor}
        enquiryModalOffset={enquiryModalOffset}
        enquiryModalDrag={enquiryModalDrag}
        beginEnquiryModalDrag={beginEnquiryModalDrag}
        enquiryLoading={enquiryLoading}
        accountEnquiryCode={accountEnquiryCode}
        setAccountEnquiryCode={setAccountEnquiryCode}
        setShowEnquiryLookupMenu={setShowEnquiryLookupMenu}
        showEnquiryLookupMenu={showEnquiryLookupMenu}
        filteredGroupedSummaryAccounts={filteredGroupedSummaryAccounts}
        setEnquiryStatus={setEnquiryStatus}
        fetchAccountEnquiryByCode={fetchAccountEnquiryByCode}
        enquiryStatus={enquiryStatus}
        accountEnquiryData={accountEnquiryData}
        modalPositionRows={modalPositionRows}
        formatStatementValue={formatStatementValue}
        getSignedColor={getSignedColor}
        formatDirectionalBalance={formatDirectionalBalance}
        unfixedMetalEntries={unfixedMetalEntries}
        formatStatementDate={formatStatementDate}
        fixedMetalSummary={fixedMetalSummary}
        unfixedMetalSummary={unfixedMetalSummary}
        unknownFixMetalEntries={unknownFixMetalEntries}
        modalTotalFundsDisplay={modalTotalFundsDisplay}
        modalRevaluationDisplay={modalRevaluationDisplay}
        modalNetEquityDisplay={modalNetEquityDisplay}
        modalMarginAmtDisplay={modalMarginAmtDisplay}
        modalExcessDisplay={modalExcessDisplay}
        modalMarginPctDisplay={modalMarginPctDisplay}
        enquirySuppressMetalSpotMtm={enquirySuppressMetalSpotMtm}
        enquiryLiveRecalcEnabled={enquiryLiveRecalcEnabled}
        hasMetalExposure={hasMetalExposure}
        excessCurrency={excessCurrency}
        setExcessCurrency={setExcessCurrency}
        baseCurrencyCode={baseCurrencyCode}
        statementDisplayCurrencyOptions={statementDisplayCurrencyOptions}
        filteredStatementEntries={filteredStatementEntries}
        recentPaymentReceiptEntry={recentPaymentReceiptEntry}
        resolveStatementReceiptNo={resolveStatementReceiptNo}
        statementFilters={statementFilters}
        setStatementFilters={setStatementFilters}
        statementReferenceTypes={statementReferenceTypes}
        statementDepartments={statementDepartments}
        setStatementMetalCommodityEnabled={setStatementMetalCommodityEnabled}
        statementMetalCommodityEnabled={statementMetalCommodityEnabled}
        statementFilterCurrencyOptions={statementFilterCurrencyOptions}
        statementMetalOptions={statementMetalOptions}
        statementDisplayCurrency={statementDisplayCurrency}
        showStatementAuditIds={showStatementAuditIds}
        setShowStatementAuditIds={setShowStatementAuditIds}
        statementTableRef={statementTableRef}
        convertStatementDisplayAmount={convertStatementDisplayAmount}
        convertStatementEntryAmounts={convertStatementEntryAmounts}
        resolveMetalCode={resolveMetalCode}
        statementSelectedMetalCode={statementSelectedMetalCode}
        pureWeightRunningByEntryKey={pureWeightRunningByEntryKey}
        formatStatementNullableValue={formatStatementNullableValue}
        canExportAccountSummary={canExportAccountSummary}
        handleViewStatement={handleViewStatement}
        buildAccountEnquiryHref={buildAccountEnquiryHref}
        handleExportEnquiryPdf={handleExportEnquiryPdf}
        getAccountEnquirySignedMetricColor={getAccountEnquirySignedMetricColor}
        formatAccountEnquiryExcessDisplay={formatAccountEnquiryExcessDisplay}
        resolveExposureDirection={resolveExposureDirection}
        isMetalStatementEntry={isMetalStatementEntry}
      />
      <StatementPreviewModal
        open={showStatementPreview}
        onClose={() => setShowStatementPreview(false)}
        title={statementPreviewTitle}
        html={statementPreviewHtml}
        loading={statementPreviewLoading}
      />
      <StatementExportOptionsModal
        open={exportOptionsOpen}
        onClose={() => setExportOptionsOpen(false)}
        onPrint={handlePrintStatement}
        onDownloadPdf={handleDownloadStatementPdf}
      />
    </>
  )
}
