import { lazy, Suspense } from 'react'
import {
  ERPAccountsTabContainer,
  ERPVouchersTabContainer,
} from './ERPTabContainers'
import ERPDashboardTab from './tabs/ERPDashboardTab'
import ErpEditRecordModal from './ErpEditRecordModal'

const ChartOfAccountsTree = lazy(() => import('../ChartOfAccountsTree'))
const DirectDealsTab = lazy(() => import('../DirectDealsTab'))
const ERPInventoryTab = lazy(() => import('./tabs/ERPInventoryTab'))
const ERPVendorsTab = lazy(() => import('./tabs/ERPVendorsTab'))
const ERPLedgerTab = lazy(() => import('./tabs/ERPLedgerTab'))
const ERPTransactionsTab = lazy(() => import('./tabs/ERPTransactionsTab'))
const ERPReportsTab = lazy(() => import('./tabs/ERPReportsTab'))
const ERPFixingRegisterTab = lazy(() => import('./tabs/ERPFixingRegisterTab'))
const ERPCustomersTab = lazy(() => import('./tabs/ERPCustomersTab'))
const ERPCustomerMarginTab = lazy(() => import('./tabs/ERPCustomerMarginTab'))
const ERPSupplierMarginTab = lazy(() => import('./tabs/ERPSupplierMarginTab'))
const ERPMappingsTab = lazy(() => import('./tabs/ERPMappingsTab'))
const ERPEnquiryTab = lazy(() => import('./tabs/ERPEnquiryTab'))
const ERPSettingsTab = lazy(() => import('./tabs/ERPSettingsTab'))
const ERPCurrenciesTab = lazy(() => import('./tabs/ERPCurrenciesTab'))
const VoucherTab = lazy(() => import('../VoucherTab'))

function ErpSubTabFallback() {
  return (
    <div style={{ padding: '1rem', color: '#6B7280', fontSize: '0.875rem' }}>
      Loading…
    </div>
  )
}

export default function ERPTabPanels({
  C,
  ACCOUNT_TYPES,
  ERP_DASH_ALL_WIDGETS,
  ERP_EMPTY_CARD_STYLE,
  ERP_MODAL_BACKDROP_STYLE,
  ERP_MODAL_CARD_STYLE,
  ERP_MODAL_INPUT_STYLE,
  ITEMS_PER_PAGE,
  JV_MODE_META,
  LEDGER_DEPARTMENTS,
  LEDGER_REFERENCE_TYPES,
  TRANSACTION_ACTION_LABELS,
  TRANSACTION_STATUS_STYLES,
  TRANSACTION_TYPE_LABELS,
  accountEnquiryCode,
  accounts,
  activeTab,
  addJvLine,
  allVisibleTransactionsSelected,
  availableTransactionTypes,
  bankJvComboGroups,
  baseCurrencyCode,
  beginFixingRegPanelDrag,
  beginJvModalDrag,
  beginJvModalResize,
  branding,
  brandingForm,
  brandingPreview,
  brandingPreviewLogo,
  brandingProfiles,
  buildAccountEnquiryHref,
  canManageAccounts,
  canManageCustomers,
  canManageDirectDeals,
  canManageVendors,
  canViewBalanceEnquiry,
  closeEditModal,
  closeJvModal,
  createInventoryMappingForm,
  currencies,
  currencyForm,
  customerForm,
  customerMarginCompactView,
  customerMarginContextMenu,
  customerMarginRows,
  customerMarginSearch,
  customerMarginSort,
  customers,
  dashChatMessages,
  dashCustomizeOpen,
  dashDragSrc,
  dashEditMode,
  dashHoveredWid,
  dashPickSelected,
  dashWidgetCols,
  dashWidgets,
  dashboard,
  decodeInventoryCategoryMeta,
  editState,
  editingInventoryProductId,
  editingProductId,
  editingVendorId,
  enquiryHistory,
  enquiryLoading,
  enquiryStatus,
  erpBaseCurrencyCode,
  erpLiveMetalSnapshot,
  fetchAccountEnquiryByCode,
  filteredGroupedSummaryAccounts,
  fixingRegError,
  fixingRegFilter,
  fixingRegFmtAmt,
  fixingRegFmtQty,
  fixingRegFmtRate,
  fixingRegLoading,
  fixingRegOpening,
  fixingRegPanelDrag,
  fixingRegPanelOffset,
  fixingRegResults,
  fixingRegShown,
  fixingRegisterStockTypeOptions,
  formatDirectionalBalance,
  formatMoney,
  formatMoneyAbs,
  formatTransactionAuditEntry,
  formatTransactionCommentKind,
  formatVatPercent,
  getDepartmentBadgeStyle,
  getJvValidation,
  getReportPeriodLabel,
  getTransactionBulkSelectionLabel,
  handleAccountEnquiry,
  handleAddTransactionComment,
  handleAddVendorDocument,
  handleBrandingLogoFile,
  handleBulkTransactionAction,
  handleCreateBrandingDraft,
  handleCreateCurrency,
  handleCreateCustomer,
  handleCreateInventoryCatalogProduct,
  handleCreateMapping,
  handleCreateProduct,
  handleCreateTransaction,
  handleCreateVendor,
  handleCustomerMarginRowContextMenu,
  handleDeleteCurrency,
  handleDeleteCustomer,
  handleDeleteInventoryCatalogProduct,
  handleDeleteMapping,
  handleDeleteProduct,
  handleDeleteTransaction,
  handleDeleteTransactionAttachment,
  handleDeleteVendor,
  handleDeleteVendorDocument,
  handleEditCurrency,
  handleEditCustomer,
  handleEditInventoryCatalogProduct,
  handleEditJv,
  handleEditLedger,
  handleEditMapping,
  handleEditProduct,
  handleEditVendor,
  handleExportReportCsv,
  handleExportReportPdf,
  handleExportReportXlsx,
  handleExportTransactionsCsv,
  handleExportTransactionsPdf,
  handleExportTransactionsXlsx,
  handleFixingRegProceed,
  handleInventoryModalDragStart,
  handleInventoryProductModalDragStart,
  handleJumpToTransaction,
  handleJvAccountKeyDown,
  handleJvLineKeyDown,
  handleOpenAccountSummaryFromTree,
  handleOpenJv,
  handleOpenVoucherSource,
  handlePrintCurrentReport,
  handlePrintJvVoucher,
  handleReconcileLedger,
  handleRepairJvFxApply,
  handleRepairJvFxPreview,
  handleReportAccountDrilldown,
  handleReverseLedger,
  handleSaveBranding,
  handleSaveEdit,
  handleSaveMultiLineJV,
  handleSelectBrandingProfile,
  handleSendTransactionChat,
  handleSupplierMarginRowContextMenu,
  handleSyncCurrencyMaster,
  handleTransactionAction,
  handleTrialAccountDrilldown,
  handleUploadTransactionAttachment,
  handleVendorFilterSearch,
  handleVendorSelect,
  handleVendorTableDocumentUpload,
  handleVendorWorkflowStatus,
  inventoryCatalogProducts,
  inventoryLowStockCount,
  inventoryMappingForm,
  inventoryMappingProducts,
  inventoryMetalBreakdown,
  inventoryModalDragging,
  inventoryModalOffset,
  inventoryProductForm,
  inventoryProductModalDragging,
  inventoryProductModalOffset,
  inventoryProductPurityWeight,
  inventoryProducts,
  inventoryProductsByMetal,
  inventoryReportProducts,
  inventoryStockCodeSettings,
  inventoryStockTypeOptions,
  inventoryTenantKey,
  inventoryTopProducts,
  inventoryTotalQuantity,
  inventoryTotalValue,
  inventoryVatFilter,
  inventoryVatSortDir,
  isFinance,
  isSuperAdmin,
  isTransactionEditMode,
  jumpToTransactionId,
  jumpToVoucher,
  jvComboGroups,
  jvEditEntryIds,
  jvError,
  jvHeader,
  jvLines,
  jvModalDrag,
  jvModalOffset,
  jvModalResize,
  jvModalSize,
  jvMode,
  jvReadOnly,
  ledger,
  ledgerFilters,
  ledgerMeta,
  ledgerReportRows,
  ledgerVoucherTab,
  legacyInventoryProducts,
  liveMetalFetchError,
  loadInventory,
  loadLedger,
  loadMappings,
  loadStockLedger,
  loadTransactions,
  loadVendorOverdueQueue,
  mappingFilters,
  mappingForm,
  mappingSummary,
  mappings,
  onJumpToVoucherConsumed,
  onNavigateMain,
  openJvModal,
  pagination,
  populateTransactionForm,
  removeJvLine,
  reportBranding,
  reportFilters,
  reportView,
  reports,
  reportsLoading,
  resetInventoryMappingForm,
  resetInventoryProductForm,
  resetTransactionComposer,
  resolveJvLineAccount,
  resolveJvModeMeta,
  resolveMainStockValueFromForm,
  resolveTransactionAttachmentUrl,
  safeSummaryAccounts,
  saving,
  selectedBrandingKey,
  selectedReportAccountCode,
  selectedReportAccountId,
  selectedTransaction,
  selectedTransactionId,
  selectedTransactionIds,
  selectedUsdConversionRate,
  selectedVendorDetails,
  selectedVendorId,
  setAccountEnquiryCode,
  setActiveTabGuarded,
  setBrandingForm,
  setCurrencyForm,
  setCustomerForm,
  setCustomerMarginCompactView,
  setCustomerMarginSearch,
  setCustomerMarginSort,
  setDashCustomizeOpen,
  setDashEditMode,
  setDashHoveredWid,
  setDashPickSelected,
  setDashWidgetCols,
  setDashWidgets,
  setEditState,
  setEditingInventoryProductId,
  setEditingProductId,
  setEditingVendorId,
  setEnquiryStatus,
  setError,
  setFixingRegError,
  setFixingRegFilter,
  setFixingRegResults,
  setFixingRegShown,
  setInventoryMappingForm,
  setInventoryModalOffset,
  setInventoryProductForm,
  setInventoryProductModalOffset,
  setInventoryStockCodeManualOverride,
  setInventoryStockCodeSettings,
  setInventoryVatFilter,
  setInventoryVatSortDir,
  setJvHeader,
  setLedgerFilters,
  setLedgerVoucherTab,
  setMappingFilters,
  setMappingForm,
  setPagination,
  setReportFilters,
  setReportView,
  setSelectedBrandingKey,
  setSelectedReportAccountCode,
  setSelectedReportAccountId,
  setSelectedTransactionId,
  setSelectedTransactionIds,
  setShowCurrencyForm,
  setShowCustomerForm,
  setShowInventoryMappingModal,
  setShowInventoryProductModal,
  setShowMappingForm,
  setShowMappingTest,
  setShowVendorForm,
  setSorting,
  setStockMovementsFilter,
  setStockTypeModalTab,
  setSupplierMarginCompactView,
  setSupplierMarginSearch,
  setSupplierMarginSort,
  setTestMapping,
  setTransactionCommentDraft,
  setTransactionFilters,
  setTransactionForm,
  setTransactionWorkflowNote,
  setUsdConversion,
  setVendorDocumentForm,
  setVendorFilters,
  setVendorForm,
  setVendorWorkflowReason,
  setVoucherSource,
  showCurrencyForm,
  showCustomerForm,
  showInventoryMappingModal,
  showInventoryProductModal,
  showLedgerForm,
  showMappingForm,
  showNotification,
  showVendorForm,
  sortedInventoryTableRows,
  sorting,
  stockMovements,
  stockMovementsFilter,
  stockMovementsLoading,
  stockTypeModalTab,
  summaryAccountsLoading,
  supplierMarginCompactView,
  supplierMarginContextMenu,
  supplierMarginRows,
  supplierMarginSearch,
  supplierMarginSort,
  switchJvMode,
  titleCaseWords,
  toggleTransactionSelection,
  toggleVisibleTransactionSelection,
  token,
  transactionAttachmentInputKey,
  transactionCommentDraft,
  transactionFilters,
  transactionForm,
  transactionMeta,
  transactionPageCount,
  transactionSummary,
  transactionWorkflowNote,
  transactions,
  transactionsLoading,
  updateJvLine,
  usdConversion,
  usdToTargetAmount,
  user,
  vendorComplianceSummary,
  vendorDocumentForm,
  vendorFilters,
  vendorForm,
  vendorOverdueQueue,
  vendorPaymentCalendar,
  vendorPermissions,
  vendorSummary,
  vendorWorkflowReason,
  vendors,
  voucherSource,
  voucherSourceLoading,
}) {
  return (
    <>
      {activeTab === 'dashboard' && (
      <ERPDashboardTab
        activeTab={activeTab}
        C={C}
        dashWidgets={dashWidgets}
        setDashWidgets={setDashWidgets}
        dashEditMode={dashEditMode}
        setDashEditMode={setDashEditMode}
        dashHoveredWid={dashHoveredWid}
        setDashHoveredWid={setDashHoveredWid}
        dashWidgetCols={dashWidgetCols}
        setDashWidgetCols={setDashWidgetCols}
        dashCustomizeOpen={dashCustomizeOpen}
        setDashCustomizeOpen={setDashCustomizeOpen}
        dashPickSelected={dashPickSelected}
        setDashPickSelected={setDashPickSelected}
        dashDragSrc={dashDragSrc}
        ERP_DASH_ALL_WIDGETS={ERP_DASH_ALL_WIDGETS}
        dashboard={dashboard}
        dashChatMessages={dashChatMessages}
        setActiveTab={setActiveTabGuarded}
        onNavigateMain={onNavigateMain}
        dashboardLiveRecalcEnabled={activeTab === 'dashboard'}
        token={token}
        accounts={accounts}
        setLedgerFilters={setLedgerFilters}
      />
      )}
      {/* CHART OF ACCOUNTS TAB */}
      {activeTab === 'accounts' && (
      <ERPAccountsTabContainer activeTab={activeTab}>
        <div>
          <div style={{ marginBottom: '1.25rem' }}>
            <h3 style={{ color: C.ink, fontSize: '1.25rem', fontWeight: '700', margin: 0 }}>Chart of Accounts</h3>
            <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: C.inkSoft }}>
              Hierarchical account tree — right-click any account for more options.
            </p>
          </div>
          <Suspense fallback={<ErpSubTabFallback />}>
            <ChartOfAccountsTree canManageAccounts={canManageAccounts} onOpenSummary={handleOpenAccountSummaryFromTree} />
          </Suspense>
        </div>
      </ERPAccountsTabContainer>
      )}
      {/* LEDGER TAB */}
      {activeTab === 'customers' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPCustomersTab
            C={C}
            canManageCustomers={canManageCustomers}
            showCustomerForm={showCustomerForm}
            setShowCustomerForm={setShowCustomerForm}
            customerForm={customerForm}
            setCustomerForm={setCustomerForm}
            handleCreateCustomer={handleCreateCustomer}
            saving={saving}
            customers={customers}
            handleEditCustomer={handleEditCustomer}
            handleDeleteCustomer={handleDeleteCustomer}
          />
        </Suspense>
      )}
      {/* CUSTOMER MARGIN TAB */}
      {activeTab === 'customer-margin' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPCustomerMarginTab
            C={C}
            setActiveTabGuarded={setActiveTabGuarded}
            customerMarginSort={customerMarginSort}
            setCustomerMarginSort={setCustomerMarginSort}
            customerMarginCompactView={customerMarginCompactView}
            setCustomerMarginCompactView={setCustomerMarginCompactView}
            customerMarginSearch={customerMarginSearch}
            setCustomerMarginSearch={setCustomerMarginSearch}
            customerMarginRows={customerMarginRows}
            handleCustomerMarginRowContextMenu={handleCustomerMarginRowContextMenu}
            customerMarginContextMenu={customerMarginContextMenu}
          />
        </Suspense>
      )}
      {/* SUPPLIER MARGIN TAB */}
      {activeTab === 'supplier-margin' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPSupplierMarginTab
            C={C}
            setActiveTabGuarded={setActiveTabGuarded}
            supplierMarginSort={supplierMarginSort}
            setSupplierMarginSort={setSupplierMarginSort}
            supplierMarginCompactView={supplierMarginCompactView}
            setSupplierMarginCompactView={setSupplierMarginCompactView}
            supplierMarginSearch={supplierMarginSearch}
            setSupplierMarginSearch={setSupplierMarginSearch}
            supplierMarginRows={supplierMarginRows}
            handleSupplierMarginRowContextMenu={handleSupplierMarginRowContextMenu}
            supplierMarginContextMenu={supplierMarginContextMenu}
          />
        </Suspense>
      )}
      {activeTab === 'fixing-register' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPFixingRegisterTab
            activeTab={activeTab}
            C={C}
            setActiveTab={setActiveTabGuarded}
            fixingRegPanelOffset={fixingRegPanelOffset}
            fixingRegPanelDrag={fixingRegPanelDrag}
            beginFixingRegPanelDrag={beginFixingRegPanelDrag}
            handleFixingRegProceed={handleFixingRegProceed}
            fixingRegLoading={fixingRegLoading}
            fixingRegFilter={fixingRegFilter}
            setFixingRegFilter={setFixingRegFilter}
            fixingRegisterStockTypeOptions={fixingRegisterStockTypeOptions}
            setFixingRegShown={setFixingRegShown}
            setFixingRegResults={setFixingRegResults}
            setFixingRegError={setFixingRegError}
            fixingRegError={fixingRegError}
            fixingRegShown={fixingRegShown}
            fixingRegOpening={fixingRegOpening}
            fixingRegResults={fixingRegResults}
            fixingRegFmtQty={fixingRegFmtQty}
            fixingRegFmtRate={fixingRegFmtRate}
            fixingRegFmtAmt={fixingRegFmtAmt}
          />
        </Suspense>
      )}
      {(activeTab === 'ledger' || showLedgerForm) && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPLedgerTab
        activeTab={activeTab}
        C={C}
        canManageAccounts={canManageAccounts}
        showLedgerForm={showLedgerForm}
        openJvModal={openJvModal}
        ledgerVoucherTab={ledgerVoucherTab}
        setLedgerVoucherTab={setLedgerVoucherTab}
        JV_MODE_META={JV_MODE_META}
        resolveJvModeMeta={resolveJvModeMeta}
        jvMode={jvMode}
        getJvValidation={getJvValidation}
        jvLines={jvLines}
        baseCurrencyCode={baseCurrencyCode}
        closeJvModal={closeJvModal}
        jvModalSize={jvModalSize}
        jvModalOffset={jvModalOffset}
        jvModalDrag={jvModalDrag}
        jvModalResize={jvModalResize}
        beginJvModalDrag={beginJvModalDrag}
        switchJvMode={switchJvMode}
        jvEditEntryIds={jvEditEntryIds}
        currencies={currencies}
        jvHeader={jvHeader}
        setJvHeader={setJvHeader}
        bankJvComboGroups={bankJvComboGroups}
        jvComboGroups={jvComboGroups}
        resolveJvLineAccount={resolveJvLineAccount}
        handleJvAccountKeyDown={handleJvAccountKeyDown}
        updateJvLine={updateJvLine}
        handleJvLineKeyDown={handleJvLineKeyDown}
        removeJvLine={removeJvLine}
        addJvLine={addJvLine}
        handlePrintJvVoucher={handlePrintJvVoucher}
        handleSaveMultiLineJV={handleSaveMultiLineJV}
        saving={saving}
        jvError={jvError}
        beginJvModalResize={beginJvModalResize}
        ledgerFilters={ledgerFilters}
        setLedgerFilters={setLedgerFilters}
        modalInputStyle={ERP_MODAL_INPUT_STYLE}
        LEDGER_DEPARTMENTS={LEDGER_DEPARTMENTS}
        LEDGER_REFERENCE_TYPES={LEDGER_REFERENCE_TYPES}
        accounts={accounts}
        sorting={sorting}
        setSorting={setSorting}
        pagination={pagination}
        setPagination={setPagination}
        ITEMS_PER_PAGE={ITEMS_PER_PAGE}
        ledger={ledger}
        ledgerMeta={ledgerMeta}
        loadLedger={loadLedger}
        jvReadOnly={jvReadOnly}
        handleOpenJv={handleOpenJv}
        handleEditJv={handleEditJv}
        handleEditLedger={handleEditLedger}
        handleReconcileLedger={handleReconcileLedger}
        handleReverseLedger={handleReverseLedger}
        isFinance={isFinance}
        handleRepairJvFxPreview={handleRepairJvFxPreview}
        handleRepairJvFxApply={handleRepairJvFxApply}
          />
        </Suspense>
      )}
      {/* ACCOUNT MAPPINGS TAB */}
      {activeTab === 'mappings' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPMappingsTab
            C={C}
            canManageAccounts={canManageAccounts}
            showMappingForm={showMappingForm}
            setShowMappingForm={setShowMappingForm}
            mappingFilters={mappingFilters}
            setMappingFilters={setMappingFilters}
            LEDGER_DEPARTMENTS={LEDGER_DEPARTMENTS}
            mappingSummary={mappingSummary}
            getDepartmentBadgeStyle={getDepartmentBadgeStyle}
            mappingForm={mappingForm}
            setMappingForm={setMappingForm}
            accounts={accounts}
            handleCreateMapping={handleCreateMapping}
            saving={saving}
            mappings={mappings}
            sorting={sorting}
            setSorting={setSorting}
            pagination={pagination}
            setPagination={setPagination}
            ITEMS_PER_PAGE={ITEMS_PER_PAGE}
            token={token}
            loadMappings={loadMappings}
            showNotification={showNotification}
            setError={setError}
            setTestMapping={setTestMapping}
            setShowMappingTest={setShowMappingTest}
            handleEditMapping={handleEditMapping}
            handleDeleteMapping={handleDeleteMapping}
          />
        </Suspense>
      )}
      {/* ACCOUNT SUMMARY TAB */}
      {activeTab === 'enquiry' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPEnquiryTab
            activeTab={activeTab}
            C={C}
            isSuperAdmin={isSuperAdmin}
            isFinance={isFinance}
            canViewBalanceEnquiry={canViewBalanceEnquiry}
            handleAccountEnquiry={handleAccountEnquiry}
            accountEnquiryCode={accountEnquiryCode}
            setAccountEnquiryCode={setAccountEnquiryCode}
            setEnquiryStatus={setEnquiryStatus}
            filteredGroupedSummaryAccounts={filteredGroupedSummaryAccounts}
            fetchAccountEnquiryByCode={fetchAccountEnquiryByCode}
            enquiryLoading={enquiryLoading}
            enquiryStatus={enquiryStatus}
            summaryAccountsLoading={summaryAccountsLoading}
            safeSummaryAccounts={safeSummaryAccounts}
            enquiryHistory={enquiryHistory}
            buildAccountEnquiryHref={buildAccountEnquiryHref}
          />
        </Suspense>
      )}
      {(activeTab === 'transactions' || jumpToTransactionId) && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPTransactionsTab
        activeTab={activeTab}
        C={C}
        emptyCardStyle={ERP_EMPTY_CARD_STYLE}
        transactionSummary={transactionSummary}
        selectedTransactionId={selectedTransactionId}
        setSelectedTransactionId={setSelectedTransactionId}
        transactionFilters={transactionFilters}
        setTransactionFilters={setTransactionFilters}
        modalInputStyle={ERP_MODAL_INPUT_STYLE}
        availableTransactionTypes={availableTransactionTypes}
        TRANSACTION_TYPE_LABELS={TRANSACTION_TYPE_LABELS}
        loadTransactions={loadTransactions}
        handleExportTransactionsCsv={handleExportTransactionsCsv}
        handleExportTransactionsXlsx={handleExportTransactionsXlsx}
        handleExportTransactionsPdf={handleExportTransactionsPdf}
        getTransactionBulkSelectionLabel={getTransactionBulkSelectionLabel}
        selectedTransactionIds={selectedTransactionIds}
        setSelectedTransactionIds={setSelectedTransactionIds}
        transactionWorkflowNote={transactionWorkflowNote}
        setTransactionWorkflowNote={setTransactionWorkflowNote}
        saving={saving}
        handleBulkTransactionAction={handleBulkTransactionAction}
        isSuperAdmin={isSuperAdmin}
        isFinance={isFinance}
        handleCreateTransaction={handleCreateTransaction}
        isTransactionEditMode={isTransactionEditMode}
        resetTransactionComposer={resetTransactionComposer}
        transactionForm={transactionForm}
        setTransactionForm={setTransactionForm}
        currencies={currencies}
        customers={customers}
        vendors={vendors}
        inventoryProducts={inventoryProducts}
        mappings={mappings}
        accounts={accounts}
        selectedTransaction={selectedTransaction}
        TRANSACTION_STATUS_STYLES={TRANSACTION_STATUS_STYLES}
        resolveTransactionAttachmentUrl={resolveTransactionAttachmentUrl}
        transactionAttachmentInputKey={transactionAttachmentInputKey}
        handleUploadTransactionAttachment={handleUploadTransactionAttachment}
        handleDeleteTransactionAttachment={handleDeleteTransactionAttachment}
        handleTransactionAction={handleTransactionAction}
        transactionCommentDraft={transactionCommentDraft}
        setTransactionCommentDraft={setTransactionCommentDraft}
        handleAddTransactionComment={handleAddTransactionComment}
        handleSendTransactionChat={handleSendTransactionChat}
        formatTransactionCommentKind={formatTransactionCommentKind}
        formatTransactionAuditEntry={formatTransactionAuditEntry}
        TRANSACTION_ACTION_LABELS={TRANSACTION_ACTION_LABELS}
        transactions={transactions}
        toggleVisibleTransactionSelection={toggleVisibleTransactionSelection}
        allVisibleTransactionsSelected={allVisibleTransactionsSelected}
        toggleTransactionSelection={toggleTransactionSelection}
        populateTransactionForm={populateTransactionForm}
        handleDeleteTransaction={handleDeleteTransaction}
        transactionMeta={transactionMeta}
        transactionPageCount={transactionPageCount}
        loading={transactionsLoading}
          />
        </Suspense>
      )}
      {activeTab === 'reports' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPReportsTab
        activeTab={activeTab}
        C={C}
        modalInputStyle={ERP_MODAL_INPUT_STYLE}
        reportFilters={reportFilters}
        setReportFilters={setReportFilters}
        ACCOUNT_TYPES={ACCOUNT_TYPES}
        LEDGER_REFERENCE_TYPES={LEDGER_REFERENCE_TYPES}
        handleExportReportCsv={handleExportReportCsv}
        handleExportReportXlsx={handleExportReportXlsx}
        handleExportReportPdf={handleExportReportPdf}
        handlePrintCurrentReport={handlePrintCurrentReport}
        emptyCardStyle={ERP_EMPTY_CARD_STYLE}
        reports={reports}
        reportView={reportView}
        setReportView={setReportView}
        getReportPeriodLabel={getReportPeriodLabel}
        formatDirectionalBalance={formatDirectionalBalance}
        handleTrialAccountDrilldown={handleTrialAccountDrilldown}
        formatMoney={formatMoney}
        handleReportAccountDrilldown={handleReportAccountDrilldown}
        formatMoneyAbs={formatMoneyAbs}
        selectedReportAccountId={selectedReportAccountId}
        setSelectedReportAccountId={setSelectedReportAccountId}
        accounts={accounts}
        setSelectedReportAccountCode={setSelectedReportAccountCode}
        selectedReportAccountCode={selectedReportAccountCode}
        ledgerReportRows={ledgerReportRows}
        loading={reportsLoading}
        voucherSource={voucherSource}
        setVoucherSource={setVoucherSource}
        modalBackdropStyle={ERP_MODAL_BACKDROP_STYLE}
        modalCardStyle={ERP_MODAL_CARD_STYLE}
        voucherSourceLoading={voucherSourceLoading}
        handleOpenVoucherSource={handleOpenVoucherSource}
        handleJumpToTransaction={handleJumpToTransaction}
          />
        </Suspense>
      )}
      {/* VENDORS TAB */}
      {activeTab === 'vendors' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPVendorsTab
        activeTab={activeTab}
        C={C}
        modalInputStyle={ERP_MODAL_INPUT_STYLE}
        emptyCardStyle={ERP_EMPTY_CARD_STYLE}
        saving={saving}
        canManageVendors={canManageVendors}
        vendorSummary={vendorSummary}
        vendorPaymentCalendar={vendorPaymentCalendar}
        vendorComplianceSummary={vendorComplianceSummary}
        vendorOverdueQueue={vendorOverdueQueue}
        vendorFilters={vendorFilters}
        showVendorForm={showVendorForm}
        editingVendorId={editingVendorId}
        vendorForm={vendorForm}
        vendors={vendors}
        selectedVendorId={selectedVendorId}
        selectedVendorDetails={selectedVendorDetails}
        vendorPermissions={vendorPermissions}
        vendorWorkflowReason={vendorWorkflowReason}
        vendorDocumentForm={vendorDocumentForm}
        handleVendorFilterSearch={handleVendorFilterSearch}
        setEditingVendorId={setEditingVendorId}
        setShowVendorForm={setShowVendorForm}
        loadVendorOverdueQueue={loadVendorOverdueQueue}
        setVendorFilters={setVendorFilters}
        handleCreateVendor={handleCreateVendor}
        setVendorForm={setVendorForm}
        handleVendorSelect={handleVendorSelect}
        handleEditVendor={handleEditVendor}
        handleDeleteVendor={handleDeleteVendor}
        setVendorWorkflowReason={setVendorWorkflowReason}
        handleVendorWorkflowStatus={handleVendorWorkflowStatus}
        handleAddVendorDocument={handleAddVendorDocument}
        handleVendorTableDocumentUpload={handleVendorTableDocumentUpload}
        setVendorDocumentForm={setVendorDocumentForm}
        handleDeleteVendorDocument={handleDeleteVendorDocument}
          />
        </Suspense>
      )}
      {/* INVENTORY TAB */}
      {activeTab === 'inventory' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPInventoryTab
        activeTab={activeTab}
        C={C}
        modalInputStyle={ERP_MODAL_INPUT_STYLE}
        isSuperAdmin={isSuperAdmin}
        isFinance={isFinance}
        saving={saving}
        token={token}
        tenantKey={inventoryTenantKey}
        liveMetalSnapshot={erpLiveMetalSnapshot}
        liveMetalError={liveMetalFetchError}
        loadInventory={loadInventory}
        inventoryMappingProducts={inventoryMappingProducts}
        inventoryCatalogProducts={inventoryCatalogProducts}
        inventoryProductsByMetal={inventoryProductsByMetal}
        inventoryReportProducts={inventoryReportProducts}
        inventoryTotalQuantity={inventoryTotalQuantity}
        inventoryTotalValue={inventoryTotalValue}
        inventoryLowStockCount={inventoryLowStockCount}
        inventoryMetalBreakdown={inventoryMetalBreakdown}
        inventoryTopProducts={inventoryTopProducts}
        legacyInventoryProducts={legacyInventoryProducts}
        inventoryVatFilter={inventoryVatFilter}
        inventoryVatSortDir={inventoryVatSortDir}
        sortedInventoryTableRows={sortedInventoryTableRows}
        stockMovements={stockMovements}
        stockMovementsLoading={stockMovementsLoading}
        stockMovementsFilter={stockMovementsFilter}
        showInventoryProductModal={showInventoryProductModal}
        showInventoryMappingModal={showInventoryMappingModal}
        editingProductId={editingProductId}
        editingInventoryProductId={editingInventoryProductId}
        stockTypeModalTab={stockTypeModalTab}
        inventoryModalOffset={inventoryModalOffset}
        inventoryModalDragging={inventoryModalDragging}
        inventoryProductModalOffset={inventoryProductModalOffset}
        inventoryProductModalDragging={inventoryProductModalDragging}
        inventoryMappingForm={inventoryMappingForm}
        inventoryProductForm={inventoryProductForm}
        inventoryStockTypeOptions={inventoryStockTypeOptions}
        inventoryProductPurityWeight={inventoryProductPurityWeight}
        setEditingProductId={setEditingProductId}
        setInventoryMappingForm={setInventoryMappingForm}
        setInventoryStockCodeManualOverride={setInventoryStockCodeManualOverride}
        setInventoryModalOffset={setInventoryModalOffset}
        setShowInventoryMappingModal={setShowInventoryMappingModal}
        setEditingInventoryProductId={setEditingInventoryProductId}
        setInventoryProductModalOffset={setInventoryProductModalOffset}
        setShowInventoryProductModal={setShowInventoryProductModal}
        setInventoryVatFilter={setInventoryVatFilter}
        setInventoryVatSortDir={setInventoryVatSortDir}
        setStockMovementsFilter={setStockMovementsFilter}
        setInventoryProductForm={setInventoryProductForm}
        setStockTypeModalTab={setStockTypeModalTab}
        createInventoryMappingForm={createInventoryMappingForm}
        decodeInventoryCategoryMeta={decodeInventoryCategoryMeta}
        titleCaseWords={titleCaseWords}
        formatVatPercent={formatVatPercent}
        resolveMainStockValueFromForm={resolveMainStockValueFromForm}
        handleEditProduct={handleEditProduct}
        handleDeleteProduct={handleDeleteProduct}
        handleEditInventoryCatalogProduct={handleEditInventoryCatalogProduct}
        handleDeleteInventoryCatalogProduct={handleDeleteInventoryCatalogProduct}
        loadStockLedger={loadStockLedger}
        resetInventoryProductForm={resetInventoryProductForm}
        handleCreateInventoryCatalogProduct={handleCreateInventoryCatalogProduct}
        handleInventoryProductModalDragStart={handleInventoryProductModalDragStart}
        resetInventoryMappingForm={resetInventoryMappingForm}
        handleCreateProduct={handleCreateProduct}
        handleInventoryModalDragStart={handleInventoryModalDragStart}
          />
        </Suspense>
      )}
      {/* SETTINGS TAB */}
      {activeTab === 'settings' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPSettingsTab
            C={C}
            selectedBrandingKey={selectedBrandingKey}
            setSelectedBrandingKey={setSelectedBrandingKey}
            handleSelectBrandingProfile={handleSelectBrandingProfile}
            brandingProfiles={brandingProfiles}
            brandingForm={brandingForm}
            setBrandingForm={setBrandingForm}
            reportBranding={reportBranding}
            handleBrandingLogoFile={handleBrandingLogoFile}
            saving={saving}
            canManageAccounts={canManageAccounts}
            handleSaveBranding={handleSaveBranding}
            inventoryStockCodeSettings={inventoryStockCodeSettings}
            setInventoryStockCodeSettings={setInventoryStockCodeSettings}
            handleCreateBrandingDraft={handleCreateBrandingDraft}
            brandingPreviewLogo={brandingPreviewLogo}
            brandingPreview={brandingPreview}
          />
        </Suspense>
      )}
      {/* CURRENCIES TAB */}
      {activeTab === 'currencies' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <ERPCurrenciesTab
            C={C}
            erpBaseCurrencyCode={erpBaseCurrencyCode}
            canManageAccounts={canManageAccounts}
            showCurrencyForm={showCurrencyForm}
            setShowCurrencyForm={setShowCurrencyForm}
            handleSyncCurrencyMaster={handleSyncCurrencyMaster}
            saving={saving}
            setActiveTabGuarded={setActiveTabGuarded}
            usdConversion={usdConversion}
            setUsdConversion={setUsdConversion}
            usdToTargetAmount={usdToTargetAmount}
            selectedUsdConversionRate={selectedUsdConversionRate}
            currencyForm={currencyForm}
            setCurrencyForm={setCurrencyForm}
            handleCreateCurrency={handleCreateCurrency}
            currencies={currencies}
            handleEditCurrency={handleEditCurrency}
            handleDeleteCurrency={handleDeleteCurrency}
          />
        </Suspense>
      )}
      <ErpEditRecordModal
        editState={editState}
        setEditState={setEditState}
        accounts={accounts}
        ledgerDepartments={LEDGER_DEPARTMENTS}
        erpBaseCurrencyCode={erpBaseCurrencyCode}
        saving={saving}
        onClose={closeEditModal}
        onSubmit={handleSaveEdit}
        colors={C}
      />
      {/* VOUCHERS TAB */}
      {(activeTab === 'vouchers' || jumpToVoucher) && (
      <ERPVouchersTabContainer activeTab={activeTab}>
        <Suspense fallback={<div style={{ padding: '1rem', color: C.inkSoft }}>Loading vouchers...</div>}>
          <VoucherTab
            token={token}
            user={user}
            accounts={accounts}
            customers={customers}
            vendors={vendors}
            currencies={currencies}
            reportBranding={branding}
            pendingOpenTransactionId={jumpToVoucher?.id || null}
            pendingOpenTransactionType={jumpToVoucher?.type || null}
            onPendingOpenTransactionConsumed={onJumpToVoucherConsumed}
          />
        </Suspense>
      </ERPVouchersTabContainer>
      )}
      {/* DIRECT DEALS TAB */}
      {activeTab === 'direct-deals' && (
        <Suspense fallback={<ErpSubTabFallback />}>
          <DirectDealsTab
            token={token}
            customers={customers}
            currencies={currencies}
            canManage={canManageDirectDeals}
            isSuperAdmin={isSuperAdmin}
          />
        </Suspense>
      )}
    </>
  )
}
