/**
 * Shared flat enterprise window chrome (presentation only).
 * Used by Voucher editor + Direct Deals modal — no business logic.
 */

export const erpWin = {
  shell: {
    border: '1px solid var(--border, #E5E7EB)',
    borderRadius: '12px',
    background: 'var(--bg-card, #FFFFFF)',
    boxShadow: 'var(--shadow-card, 0 1px 2px rgba(15,23,42,0.04), 0 4px 12px rgba(15,23,42,0.06))',
    overflow: 'hidden',
  },
  titleBar: {
    background: 'var(--brand-soft)',
    color: 'var(--brand-on-soft)',
    borderBottom: '1px solid var(--brand-border)',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexShrink: 0,
  },
  titleText: {
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--brand-on-soft)',
    letterSpacing: '-0.01em',
  },
  titleBtn: {
    width: 28,
    height: 28,
    background: '#FFFFFF',
    border: '1px solid var(--border, #E5E7EB)',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 12,
    color: 'var(--text-secondary, #374151)',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  toolbar: {
    background: '#F8FAFC',
    borderBottom: '1px solid var(--border, #E5E7EB)',
    padding: '6px 10px',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  toolBtn: {
    minWidth: 32,
    height: 32,
    padding: '0 8px',
    background: '#FFFFFF',
    border: '1px solid var(--border, #E5E7EB)',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 13,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-primary, #111827)',
  },
  body: {
    padding: '12px 14px',
    background: '#FFFFFF',
  },
  footer: {
    background: '#F8FAFC',
    borderTop: '1px solid var(--border, #E5E7EB)',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
    gap: 8,
    flexWrap: 'wrap',
  },
  footerBtn: {
    padding: '8px 14px',
    border: '1px solid var(--border, #E5E7EB)',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    background: '#FFFFFF',
    color: 'var(--text-primary, #111827)',
    fontFamily: 'inherit',
  },
  footerBtnPrimary: {
    padding: '8px 14px',
    border: '1px solid var(--brand-button-bg, var(--brand-dark))',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    background: 'var(--brand-button-bg, var(--brand-dark))',
    color: 'var(--brand-button-text, #FFFFFF)',
    fontFamily: 'inherit',
  },
  input: {
    border: '1px solid var(--border-input, #9CA3AF)',
    padding: '6px 10px',
    fontSize: 13,
    background: '#FFFFFF',
    borderRadius: 8,
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    color: 'var(--text-primary, #111827)',
  },
  select: {
    border: '1px solid var(--border-input, #9CA3AF)',
    padding: '6px 8px',
    fontSize: 13,
    background: '#FFFFFF',
    borderRadius: 8,
    fontFamily: 'inherit',
    cursor: 'pointer',
    width: '100%',
    boxSizing: 'border-box',
    color: 'var(--text-primary, #111827)',
  },
}
