export const EMPTY_VENDOR_FORM = {
  vendorCode: '',
  name: '',
  contactPerson: '',
  phone: '',
  email: '',
  address: '',
  city: '',
  country: '',
  postalCode: '',
  gstVat: '',
  taxRegistrationNo: '',
  openingBalance: '',
  paymentTermsDays: '30',
  creditLimit: '',
  category: 'general',
  rating: '3',
  riskLevel: 'medium',
  status: 'active',
  notes: '',
  tags: '',
  preferredCurrency: 'USD',
  bankName: '',
  bankAccountNumber: '',
  iban: '',
  swiftCode: '',
  currency: 'USD',
}

export const EMPTY_VENDOR_DOCUMENT_FORM = {
  docType: 'contract',
  title: '',
  documentNo: '',
  fileUrl: '',
  file: null,
  issueDate: '',
  expiryDate: '',
  status: 'active',
  verified: false,
  notes: '',
}

export function vendorToFormState(vendor) {
  return {
    vendorCode: vendor.vendorCode || '',
    name: vendor.name || '',
    contactPerson: vendor.contactPerson || '',
    phone: vendor.phone || '',
    email: vendor.email || '',
    address: vendor.address || '',
    city: vendor.city || '',
    country: vendor.country || '',
    postalCode: vendor.postalCode || '',
    gstVat: vendor.gstVat || '',
    taxRegistrationNo: vendor.taxRegistrationNo || '',
    openingBalance: String(vendor.openingBalance || ''),
    paymentTermsDays: String(vendor.paymentTermsDays || 30),
    creditLimit: String(vendor.creditLimit || ''),
    category: vendor.category || 'general',
    rating: String(vendor.rating || 3),
    riskLevel: vendor.riskLevel || 'medium',
    status: vendor.status || 'active',
    notes: vendor.notes || '',
    tags: Array.isArray(vendor.tags) ? vendor.tags.join(', ') : '',
    preferredCurrency: vendor.preferredCurrency || vendor.currency || 'USD',
    bankName: vendor.bankName || '',
    bankAccountNumber: vendor.bankAccountNumber || '',
    iban: vendor.iban || '',
    swiftCode: vendor.swiftCode || '',
    currency: vendor.currency || 'USD',
  }
}
