// FILE: src/context/LanguageContext.jsx
// Provides language switching (English, Arabic, Uzbek, Russian) across the whole app.
// Arabic uses RTL layout; others are LTR.

import { createContext, useContext, useEffect, useState } from 'react'

// ── Translations ─────────────────────────────────────────────────────────────
const translations = {
  en: {
    appName:            'Ops Dashboard',
    controlSystem:      'Control System',
    overview:           'Overview',
    chat:               'Chat',
    admin:              'Admin',
    hr:                 'HR',
    compliance:         'Compliance',
    production:         'Production',
    finance:            'Finance',
    sales:              'Sales',
    operations:         'Operations',
    training:           'Training',
    erp:                'ERP',
    adminSection:       'Admin',
    departments:        'Departments',
    signIn:             'SIGN IN',
    signOut:            'Sign out',
    username:           'Username',
    password:           'Password',
    enterUsername:      'Enter your username',
    enterPassword:      'Enter your password',
    signingIn:          'Signing in...',
    accessByInvitation: 'Access by invitation only',
    operationsControl:  'Operations Control System',
    readOnly:           'Read Only',
    loginErrEmpty:      'Please enter your username and password.',
    loginErrNetwork:    'Cannot reach server. Check your connection or try again.',
    loginErrServer:     'Server error while signing in. Please try again shortly.',
    loginErrInvalid:    'Invalid username or password.',
    superAdmin:         'Super Admin',
    management:         'Management',
    deptHead:           'Dept. Head',
    deptUser:           'Dept. User',
    external:           'External',
    loadingModule:      'Loading module...',
    moduleFailedLoad:   'This module failed to load.',
    dashboardStillAvail:'The rest of the dashboard is still available. Switch tabs or reload.',
    selectTab:          'Select a tab from the sidebar',
    pageNotFound:       'Page not found',
    backToDashboard:    'Back to dashboard',
    dashboard:          'Dashboard',
    language:           'Language',
    noData:             'No data available',
    loading:            'Loading...',
    saving:             'Saving...',
    saved:              'Saved',
    error:              'Error',
    success:            'Success',
    save:               'Save',
    cancel:             'Cancel',
    delete:             'Delete',
    edit:               'Edit',
    add:                'Add',
    create:             'Create',
    update:             'Update',
    search:             'Search',
    filter:             'Filter',
    export:             'Export',
    import:             'Import',
    print:              'Print',
    close:              'Close',
    confirm:            'Confirm',
    submit:             'Submit',
    approve:            'Approve',
    reject:             'Reject',
    back:               'Back',
    next:               'Next',
    done:               'Done',
    view:               'View',
    reset:              'Reset',
    clear:              'Clear',
    apply:              'Apply',
    remove:             'Remove',
    send:               'Send',
    download:           'Download',
    upload:             'Upload',
    post:               'Post',
    reopen:             'Reopen',
    returnForEdit:      'Return for Edit',
    all:                'All',
    none:               'None',
    yes:                'Yes',
    no:                 'No',
    actions:            'Actions',
    details:            'Details',
    summary:            'Summary',
    total:              'Total',
    subtotal:           'Subtotal',
    notes:              'Notes',
    remarks:            'Remarks',
    status:             'Status',
    type:               'Type',
    date:               'Date',
    amount:             'Amount',
    currency:           'Currency',
    description:        'Description',
    reference:          'Reference',
    department:         'Department',
    role:               'Role',
    name:               'Name',
    code:               'Code',
    phone:              'Phone',
    address:            'Address',
    email:              'Email',
    quantity:           'Quantity',
    price:              'Price',
    rate:               'Rate',
    branch:             'Branch',
    from:               'From',
    to:                 'To',
    by:                 'By',
    of:                 'of',
    statusDraft:        'Draft',
    statusSubmitted:    'Submitted',
    statusApproved:     'Approved',
    statusPosted:       'Posted',
    statusReturned:     'Returned',
    statusRejected:     'Rejected',
    statusActive:       'Active',
    statusInactive:     'Inactive',
    statusPending:      'Pending',
    statusCompleted:    'Completed',
    statusCancelled:    'Cancelled',
    statusOnHold:       'On Hold',
    statusUnderReview:  'Under Review',
    statusScheduled:    'Scheduled',
    statusInProgress:   'In Progress',
    statusOverdue:      'Overdue',
    statusProcessed:    'Processed',
    statusExpired:      'Expired',
    statusExpiringSoon: 'Expiring Soon',
    statusPaid:         'Paid',
    statusSent:         'Sent',
    statusFiled:        'Filed',
    statusEligible:     'Eligible',
    statusConfirmed:    'Confirmed',
    priorityLow:        'Low',
    priorityMedium:     'Medium',
    priorityHigh:       'High',
    priorityCritical:   'Critical',
    executiveDashboard: 'Executive Dashboard',
    quickActions:       'Quick Actions',
    recentAlerts:       'Recent Alerts',
    recentMessages:     'Recent Messages',
    myTasks:            'My Tasks',
    leaveRequests:      'Leave Requests',
    departmentStatus:   'Department Status',
    addTask:            'Add Task',
    addEmployee:        'Add Employee',
    addLead:            'Add Lead',
    logExpense:         'Log Expense',
    addSupplier:        'Add Supplier',
    scheduleMeeting:    'Schedule Meeting',
    createInvoice:      'Create Invoice',
    logIncident:        'Log Incident',
    generateReport:     'Generate Report',
    globalSearch:       'Global Search',
    newTask:            'New Task',
    newEmployee:        'New Employee',
    newInvoice:         'New Invoice',
    newLead:            'New Lead',
    newMaintenanceTask: 'New Maintenance Task',
    newComplianceIssue: 'New Compliance Issue',
    newAnnouncement:    'New Announcement',
    taskTitle:          'Task Title',
    assignTo:           'Assign To',
    dueDate:            'Due Date',
    priority:           'Priority',
    todoStatus:         'To Do',
    inProgressStatus:   'In Progress',
    blockedStatus:      'Blocked',
    underReviewStatus:  'Under Review',
    completedStatus:    'Completed',
    cancelledStatus:    'Cancelled',
    noTasksFound:       'No tasks found',
    viewAll:            'View All',
    markDone:           'Mark Done',
    dismiss:            'Dismiss',
    attendance:         'Attendance',
    present:            'Present',
    absent:             'Absent',
    late:               'Late',
    onLeave:            'On Leave',
    userManagement:     'User Management',
    systemSettings:     'System Settings',
    addUser:            'Add User',
    editUser:           'Edit User',
    deleteUser:         'Delete User',
    fullName:           'Full Name',
    usernameLabel:      'Username',
    passwordLabel:      'Password',
    newPassword:        'New Password (leave blank to keep)',
    allowedModules:     'Allowed Modules',
    noUsersFound:       'No users found',
    userSaved:          'User saved successfully.',
    userDeleted:        'User deleted.',
    confirmDeleteUser:  'Delete this user? This cannot be undone.',
    settings:           'Settings',
    companyName:        'Company Name',
    timezone:           'Timezone',
    sessionTimeout:     'Session Timeout (min)',
    passwordRotation:   'Password Rotation (days)',
    requireMfa:         'Require MFA for Admins',
    loginAlerts:        'Login Alerts',
    approvalEscalation: 'Approval Escaltion',
    weekendApprovals:   'Allow Weekend Approvals',
    dailyDigest:        'Daily Digest',
    saveSettings:       'Save Settings',
    employeeList:       'Employee List',
    labourLaw:          'Labour Law',
    currentUpdates:     'Current Updates',
    addNewEmployee:     'Add New Employee',
    fillEmployeeDetails:'Fill in the employee details below.',
    idNumber:           'ID Number',
    employeeCode:       'Employee Code',
    performanceRating:  'Performance Rating',
    saveEmployee:       'Save Employee',
    noEmployeesFound:   'No employees found.',
    employeeSaved:      'Employee saved.',
    employeeDeleted:    'Employee deleted.',
    confirmDeleteEmployee: 'Delete this employee record?',
    searchEmployees:    'Search employees...',
    ratingLabel:        'Rating',
    selectDepartment:   'Select department',
    erpDashboard:       'Dashboard',
    erpTransactions:    'Transactions',
    erpLedger:          'Ledger',
    erpAccounts:        'Accounts',
    erpCurrencies:      'Currencies',
    erpMetalRates:      'Metal Rates',
    erpReports:         'Reports',
    erpChartOfAccounts: 'Chart of Accounts',
    erpVouchers:        'Vouchers',
    erpDirectDeals:     'Direct Deals',
    erpInventory:       'Inventory',
    account:            'Account',
    debit:              'Debit',
    credit:             'Credit',
    balance:            'Balance',
    journal:            'Journal',
    voucher:            'Voucher',
    transaction:        'Transaction',
    transactions:       'Transactions',
    ledgerEntry:        'Ledger Entry',
    exchangeRate:       'Exchange Rate',
    metalRate:          'Metal Rate',
    entryType:          'Entry Type',
    fixing:             'Fixing',
    nonFixing:          'Non-Fixing',
    docNo:              'Doc No.',
    docDate:            'Doc Date',
    valueDate:          'Value Date',
    customer:           'Customer',
    direction:          'Direction',
    buy:                'Buy',
    sell:               'Sell',
    metal:              'Metal',
    stockCode:          'Stock Code',
    eqOz:               'Eq. Oz',
    lineItems:          'Line Items',
    addLine:            'Add Line',
    removeLine:         'Remove Line',
    importLines:        'Import Lines',
    exportPdf:          'Export PDF',
    exportExcel:        'Export Excel',
    downloadTemplate:   'Download Template',
    importPreview:      'Import Preview',
    applyToForm:        'Apply to Form',
    clearPreview:       'Clear Preview',
    validRows:          'Valid',
    invalidRows:        'Invalid',
    totalRows:          'Total',
    locked:             'Locked',
    lockedEntryWarning: 'This entry is confirmed and locked. Only Admin can edit.',
    confirmEntry:       'Confirm Entry',
    reopenEntry:        'Reopen Entry',
    kpiOverview:        'KPI Overview',
    revenue:            'Revenue',
    expenses:           'Expenses',
    invoices:           'Invoices',
    budget:             'Budget',
    payroll:            'Payroll',
    arAp:               'AR & AP',
    goldTracker:        'Gold Tracker',
    tax:                'Tax',
    reports:            'Reports',
    generalLedger:      'General Ledger',
    auditTrail:         'Audit Trail',
    totalRevenue:       'Total Revenue',
    netProfit:          'Net Profit',
    cashFlow:           'Cash Flow',
    outstanding:        'Outstanding',
    overdue:            'Overdue',
    invoiceId:          'Invoice ID',
    client:             'Client',
    issueDate:          'Issue Date',
    daysOverdue:        'Days Overdue',
    addInvoice:         'Add Invoice',
    addExpense:         'Add Expense',
    approvedBy:         'Approved By',
    category:           'Category',
    flagged:            'Flagged',
    employee:           'Employee',
    basic:              'Basic',
    allowance:          'Allowance',
    deductions:         'Deductions',
    netPay:             'Net Pay',
    annual:             'Annual',
    spent:              'Spent',
    receivables:        'Receivables',
    payables:           'Payables',
    vendor:             'Vendor',
    taxType:            'Tax Type',
    period:             'Period',
    filed:              'Filed',
    filedDate:          'Filed Date',
    liveMonitor:        'Live Monitor',
    equipment:          'Equipment',
    maintenance:        'Maintenance',
    qualityControl:     'Quality Control',
    shiftManagement:    'Shift Management',
    planning:           'Planning',
    alertsReports:      'Alerts & Reports',
    costTracking:       'Cost Tracking',
    oee:                'OEE',
    uptime:             'Uptime',
    output:             'Output',
    defectRate:         'Defect Rate',
    activeLines:        'Active Lines',
    addEquipment:       'Add Equipment',
    scheduleMaintenance:'Schedule Maintenance',
    logDefect:          'Log Defect',
    readiness:          'Readiness',
    supplyChain:        'Supply Chain',
    goldSourcing:       'Gold Sourcing',
    transport:          'Transport',
    security:           'Security',
    contracts:          'Contracts',
    inventory:          'Inventory',
    liveMap:            'Live Map',
    analytics:          'Analytics',
    opsProjectsNav:          'Projects',
    opsProjectsTitle:  'Operations Projects',
    opsShowArchived:    'Show archived',
    opsApplyTemplate:   'Apply template…',
    opsAddProject:         '+ Add Project',
    opsProjectsOpen:       'open projects',
    opsProjectsCompleted:  'completed',
    opsProjectsIncArchived: '(including archived)',
    opsStaleBadge:      'STALE',
    opsProjectsReminderToastTitle: 'Project reminder',
    opsProjectsReminderToastBody: 'Reminder due:',
    opsColTodo: 'To Do',
    opsColInProgress: 'In Progress',
    opsColUnderReview: 'Under review',
    opsColBlocked: 'Blocked',
    opsColDone: 'Done',
    opsProjectsCountOne: 'project',
    opsProjectsCountMany: 'projects',
    opsTeamTemplateTag: '(team)',
    opsProjectsRestrictExternal: 'Projects are not available to vendors.',
    opsProjectsMetaBy: 'By',
    opsProjectsMetaUpd: 'Upd',
    opsProjectsChecklistPct: 'Checklist',
    opsLinkedSupplyChain: 'Supply Chain',
    opsLinkedGoldSourcing: 'Gold Sourcing',
    opsLinkedTransport: 'Transport',
    opsLinkedSecurity: 'Security',
    opsLinkedVendorContracts: 'Vendor Contracts',
    opsLinkedInventory: 'Inventory',
    opsModalTitleEdit: 'Edit Project',
    opsModalTitleAdd: 'Add Project',
    opsModalSubEdit: 'Update project details',
    opsModalSubAdd: 'Create a new operations project',
    opsModalSaveChanges: 'Save Changes',
    opsModalSaveAdd: 'Add Project',
    opsModalFieldTitle: 'Project title',
    opsModalPlaceholderShortTitle: 'Short title',
    opsModalFieldAssign: 'Assigned To',
    opsModalAssignSearchPlaceholder: 'Search team member…',
    opsModalAssignManualPlaceholder: 'Team member',
    opsModalFieldDescription: 'Description',
    opsModalDescPlaceholder: 'Project details…',
    opsModalFieldPriority: 'Priority',
    opsModalFieldDue: 'Due Date',
    opsModalFieldLinked: 'Linked Section',
    opsModalFieldStatus: 'Status',
    opsModalFieldReminder: 'Reminder',
    opsModalFieldHours: 'Est. hours / Logged',
    opsModalHoursEst: 'Est',
    opsModalHoursLogged: 'Logged',
    opsModalFieldTags: 'Tags (comma separated)',
    opsModalTagsPlaceholder: 'e.g. legal, urgent',
    opsModalBlockedReason: 'Blocked reason',
    opsModalBlockedReasonPh: 'Why blocked?',
    opsModalBlockedBy: 'Blocked by project',
    opsModalNoneDash: '—',
    opsModalChecklistHeading: 'Checklist',
    opsModalChecklistStepPh: 'Step title',
    opsModalRemoveChecklistItem: 'Remove checklist item',
    opsModalChecklistAdd: '+ Checklist item',
    opsModalDependsOn: 'Depends on (other ops projects)',
    opsModalNotifyMessage: 'Notify message (optional)',
    opsModalNotifyPlaceholder: 'Included with save / create',
    opsModalAlsoNotify: 'Also notify (team)',
    opsModalAttachments: 'Attachments',
    opsModalUploadedTitle: 'Uploaded',
    opsModalUploadFailed: 'Upload failed',
    opsModalRemoveFileConfirm: 'Remove this file?',
    opsModalRemovedTitle: 'Removed',
    opsModalDeleteFailed: 'Delete failed',
    opsModalRemove: 'Remove',
    opsModalArchive: 'Archive project',
    opsModalTemplateNamePrompt: 'Template name',
    opsModalMyTemplate: 'My template',
    opsModalTemplateSavedLocal: 'Saved',
    opsModalTemplateLocalError: 'Could not save template',
    opsModalSaveLocalTemplate: 'Save as local template',
    opsModalTemplateSavedTeam: 'Team template saved',
    opsModalTemplateTeamError: 'Could not save team template',
    opsModalSaveTeamTemplate: 'Save to team library',
    opsModalProgressHeading: 'Progress updates',
    opsModalNoProgressYet: 'No updates yet.',
    opsModalDash: '—',
    opsModalAddProgressLabel: 'Add progress update',
    opsModalProgressPlaceholder: 'What changed?',
    opsModalLogProgress: 'Log update',
    opsPriCritical: 'Critical',
    opsPriHigh: 'High',
    opsPriMedium: 'Medium',
    opsPriLow: 'Low',
    opsStatusTodo: 'To Do',
    opsStatusInProgress: 'In Progress',
    opsStatusUnderReview: 'Under review',
    opsStatusBlocked: 'Blocked',
    opsStatusDone: 'Done',
    opsProjectsUpdateSingular: 'update',
    opsProjectsUpdatePlural: 'updates',
    opsProjectsDueLabel: 'Due:',
    opsProjectsReminderSet: 'Reminder set',
    opsAutoArchiveHint: 'Auto-archives',
    opsNoProjectsInColumn: 'No projects',
    opsProjectsListViewTitle: 'Project List View',
    opsThProject: 'Project',
    opsThAssigned: 'Assigned To',
    opsThPriority: 'Priority',
    opsThDue: 'Due',
    opsThStatus: 'Status',
    opsThSection: 'Section',
    opsThMeta: 'Meta',
    opsThActions: 'Actions',
    opsArchived: 'Archived',
    opsBtnArchive: 'Archive',
    opsBtnDel: 'Del',
    opsBtnUnarchive: 'Unarchive',
    opsUnarchiveConfirm: 'Restore this project from archive?',
    opsUnarchiveToastTitle: 'Restored',
    opsArchivedProjectBanner: 'This project is archived. It may be hidden from the board until you show archived items.',
    addRoute:           'Add Route',
    addVendor:          'Add Vendor',
    addItem:            'Add Item',
    eligibilityStatus:  'Eligibility Status',
    approvalsTracker:   'Approvals Tracker',
    documentation:      'Documentation',
    regulatoryUpdates:  'Regulatory Updates',
    agreements:         'Agreements',
    permit:             'Permit',
    entity:             'Entity',
    authority:          'Authority',
    filing:             'Filing',
    submittedDate:      'Submitted Date',
    refNo:              'Ref. No.',
    owner:              'Owner',
    version:            'Version',
    expiry:             'Expiry',
    impact:             'Impact',
    actionOwner:        'Action Owner',
    partner:            'Partner',
    agreementType:      'Agreement Type',
    startDate:          'Start Date',
    endDate:            'End Date',
    value:              'Value',
    calendar:           'Calendar',
    batches:            'Batches',
    resources:          'Resources',
    assessments:        'Assessments',
    certifications:     'Certifications',
    feedback:           'Feedback',
    trainees:           'Trainees',
    skillGap:           'Skill Gap',
    trainer:            'Trainer',
    batch:              'Batch',
    venue:              'Venue',
    programme:          'Programme',
    score:              'Score',
    pass:               'Pass',
    fail:               'Fail',
    completion:         'Completion',
    sessionTitle:       'Session Title',
    addSession:         'Add Session',
    addBatch:           'Add Batch',
    crmDashboard:       'CRM Dashboard',
    contacts:           'Contacts',
    companies:          'Companies',
    leads:              'Leads',
    deals:              'Deals',
    activities:         'Activities',
    followups:          'Follow-ups',
    addContact:         'Add Contact',
    addCompany:         'Add Company',
    addDeal:            'Add Deal',
    addActivity:        'Add Activity',
    stage:              'Stage',
    contactType:        'Contact Type',
    leadStage:          'Lead Stage',
    dealStage:          'Deal Stage',
    activityType:       'Activity Type',
    lastActivity:       'Last Activity',
    nextAction:         'Next Action',
    pipelineValue:      'Pipeline Value',
    conversionRate:     'Conversion Rate',
    openDeals:          'Open Deals',
    closedDeals:        'Closed Deals',
    activeContacts:     'Active Contacts',
    searchContacts:     'Search contacts...',
    searchCompanies:    'Search companies...',
    searchLeads:        'Search leads...',
    searchDeals:        'Search deals...',
    exportCsv:          'Export CSV',
    importCsv:          'Import CSV',
    messages:           'Messages',
    typeMessage:        'Type a message...',
    sendMessage:        'Send',
    groups:             'Groups',
    direct:             'Direct',
    muted:              'Muted',
    unread:             'Unread',
    today:              'Today',
    yesterday:          'Yesterday',
    noMessages:         'No messages yet. Start the conversation!',
    attachFile:         'Attach file',
    chatSearch:         'Search conversations...',
    voucherList:        'Vouchers',
    createVoucher:      'Create Voucher',
    voucherNo:          'Document No.',
    voucherDate:        'Voucher Date',
    voucherType:        'Voucher Type',
    refresh:            'Refresh',
    accounts:           'Accounts',
    move:               'Move',
    paymentVoucher:     'Payment Voucher',
    receiptVoucher:     'Receipt Voucher',
    journalVoucher:     'Journal Voucher',
    approvalWorkflow:   'Approval Workflow',
    workflowNote:       'Reason / Note',
    enterReason:        'Enter reason (required)',
    reasonRequired:     'Reason is required.',
    attachments:        'Attachments',
    uploadAttachment:   'Upload Attachment',
    noAttachments:      'No attachments.',
    auditLog:           'Audit Log',
    comments:           'Comments',
    addComment:         'Add Comment',
    postComment:        'Post Comment',
    failedToLoadDirectDeals: 'Failed to load direct deals',
    fixingEntries:      'Fixing Entries',
    nonFixingEntries:   'Non-Fixing Entries',
    totalQty:           'Total Qty',
    totalAmount:        'Total Amount',
    cancelEdit:         'Cancel Edit',
    selectCustomer:     'Select customer',
    allTypes:           'All Types',
    applyFilters:       'Apply Filters',
    noFixingEntriesFound: 'No fixing/non-fixing entries found.',
    failedToLoadAccounts: 'Failed to load accounts',
    deleteFailed:       'Delete failed',
    accountTree:        'Account Tree',
    searchByNameOrCode: 'Search by name or code...',
    noAccounts:         'No accounts',
    selectAccountFromTree: 'Select an account from the tree',
    rightClickAccountForOptions: 'Right-click any account for add / edit / move options',
    exampleAccountCode: 'e.g. 1010',
    selectType:         'Select type...',
    moduleUnderConstruction: 'Module Under Construction',
    plannedSections:    'Planned Sections',
    builtAsRequired:    'This section will be built as requirements are confirmed.',
  },

  ar: {
    appName:            'لوحة العمليات',
    controlSystem:      'نظام التحكم',
    overview:           'نظرة عامة',
    chat:               'المحادثات',
    admin:              'المسؤول',
    hr:                 'الموارد البشرية',
    compliance:         'الامتثال',
    production:         'الإنتاج',
    finance:            'المالية',
    sales:              'المبيعات',
    operations:         'العمليات',
    training:           'التدريب',
    erp:                'تخطيط الموارد',
    adminSection:       'الإدارة',
    departments:        'الأقسام',
    signIn:             'تسجيل الدخول',
    signOut:            'تسجيل الخروج',
    username:           'اسم المستخدم',
    password:           'كلمة المرور',
    enterUsername:      'أدخل اسم المستخدم',
    enterPassword:      'أدخل كلمة المرور',
    signingIn:          'جاري الدخول...',
    accessByInvitation: 'الدخول بالدعوة فقط',
    operationsControl:  'نظام التحكم بالعمليات',
    readOnly:           'للقراءة فقط',
    loginErrEmpty:      'يرجى إدخال اسم المستخدم وكلمة المرور.',
    loginErrNetwork:    'تعذر الوصول إلى الخادم. تحقق من اتصالك وأعد المحاولة.',
    loginErrServer:     'خطأ في الخادم. يرجى المحاولة مرة أخرى.',
    loginErrInvalid:    'اسم المستخدم أو كلمة المرور غير صحيحة.',
    superAdmin:         'مشرف رئيسي',
    management:         'الإدارة',
    deptHead:           'رئيس القسم',
    deptUser:           'موظف القسم',
    external:           'خارجي',
    loadingModule:      'جاري التحميل...',
    moduleFailedLoad:   'فشل تحميل هذه الوحدة.',
    dashboardStillAvail:'بقية لوحة التحكم متاحة. قم بتبديل التبويبات أو أعد التحميل.',
    selectTab:          'حدد تبويباً من الشريط الجانبي',
    pageNotFound:       'الصفحة غير موجودة',
    backToDashboard:    'العودة إلى لوحة التحكم',
    dashboard:          'لوحة التحكم',
    language:           'اللغة',
    noData:             'لا توجد بيانات',
    loading:            'جاري التحميل...',
    saving:             'جاري الحفظ...',
    saved:              'تم الحفظ',
    error:              'خطأ',
    success:            'نجاح',
    save:               'حفظ',
    cancel:             'إلغاء',
    delete:             'حذف',
    edit:               'تعديل',
    add:                'إضافة',
    create:             'إنشاء',
    update:             'تحديث',
    search:             'بحث',
    filter:             'تصفية',
    export:             'تصدير',
    import:             'استيراد',
    print:              'طباعة',
    close:              'إغلاق',
    confirm:            'تأكيد',
    submit:             'إرسال',
    approve:            'موافقة',
    reject:             'رفض',
    back:               'رجوع',
    next:               'التالي',
    done:               'تم',
    view:               'عرض',
    reset:              'إعادة تعيين',
    clear:              'مسح',
    apply:              'تطبيق',
    remove:             'إزالة',
    send:               'إرسال',
    download:           'تنزيل',
    upload:             'رفع',
    post:               'ترحيل',
    reopen:             'إعادة فتح',
    returnForEdit:      'إعادة للتعديل',
    all:                'الكل',
    none:               'لا شيء',
    yes:                'نعم',
    no:                 'لا',
    actions:            'الإجراءات',
    details:            'التفاصيل',
    summary:            'الملخص',
    total:              'الإجمالي',
    subtotal:           'المجموع الفرعي',
    notes:              'ملاحظات',
    remarks:            'تعليقات',
    status:             'الحالة',
    type:               'النوع',
    date:               'التاريخ',
    amount:             'المبلغ',
    currency:           'العملة',
    description:        'الوصف',
    reference:          'المرجع',
    department:         'القسم',
    role:               'الدور',
    name:               'الاسم',
    code:               'الرمز',
    phone:              'الهاتف',
    address:            'العنوان',
    email:              'البريد الإلكتروني',
    quantity:           'الكمية',
    price:              'السعر',
    rate:               'المعدل',
    branch:             'الفرع',
    from:               'من',
    to:                 'إلى',
    by:                 'بواسطة',
    of:                 'من',
    statusDraft:        'مسودة',
    statusSubmitted:    'مقدم',
    statusApproved:     'موافق عليه',
    statusPosted:       'مرحل',
    statusReturned:     'معاد',
    statusRejected:     'مرفوض',
    statusActive:       'نشط',
    statusInactive:     'غير نشط',
    statusPending:      'قيد الانتظار',
    statusCompleted:    'مكتمل',
    statusCancelled:    'ملغي',
    statusOnHold:       'معلق',
    statusUnderReview:  'قيد المراجعة',
    statusScheduled:    'مجدول',
    statusInProgress:   'قيد التنفيذ',
    statusOverdue:      'متأخر',
    statusProcessed:    'تمت المعالجة',
    statusExpired:      'منتهي الصلاحية',
    statusExpiringSoon: 'ينتهي قريباً',
    statusPaid:         'مدفوع',
    statusSent:         'مرسل',
    statusFiled:        'مودع',
    statusEligible:     'مؤهل',
    statusConfirmed:    'مؤكد',
    priorityLow:        'منخفض',
    priorityMedium:     'متوسط',
    priorityHigh:       'مرتفع',
    priorityCritical:   'حرج',
    executiveDashboard: 'لوحة التنفيذيين',
    quickActions:       'إجراءات سريعة',
    recentAlerts:       'تنبيهات حديثة',
    recentMessages:     'رسائل حديثة',
    myTasks:            'مهامي',
    leaveRequests:      'طلبات الإجازة',
    departmentStatus:   'حالة الأقسام',
    addTask:            'إضافة مهمة',
    addEmployee:        'إضافة موظف',
    addLead:            'إضافة عميل محتمل',
    logExpense:         'تسجيل مصروف',
    addSupplier:        'إضافة مورد',
    scheduleMeeting:    'جدولة اجتماع',
    createInvoice:      'إنشاء فاتورة',
    logIncident:        'تسجيل حادثة',
    generateReport:     'إنشاء تقرير',
    globalSearch:       'بحث شامل',
    newTask:            'مهمة جديدة',
    newEmployee:        'موظف جديد',
    newInvoice:         'فاتورة جديدة',
    newLead:            'عميل محتمل جديد',
    newMaintenanceTask: 'مهمة صيانة جديدة',
    newComplianceIssue: 'مشكلة امتثال جديدة',
    newAnnouncement:    'إعلان جديد',
    taskTitle:          'عنوان المهمة',
    assignTo:           'تعيين إلى',
    dueDate:            'تاريخ الاستحقاق',
    priority:           'الأولوية',
    todoStatus:         'قائمة المهام',
    inProgressStatus:   'قيد التنفيذ',
    blockedStatus:      'محظور',
    underReviewStatus:  'قيد المراجعة',
    completedStatus:    'مكتمل',
    cancelledStatus:    'ملغي',
    noTasksFound:       'لا توجد مهام',
    viewAll:            'عرض الكل',
    markDone:           'تحديد كمنجز',
    dismiss:            'رفض',
    attendance:         'الحضور',
    present:            'حاضر',
    absent:             'غائب',
    late:               'متأخر',
    onLeave:            'في إجازة',
    userManagement:     'إدارة المستخدمين',
    systemSettings:     'إعدادات النظام',
    addUser:            'إضافة مستخدم',
    editUser:           'تعديل المستخدم',
    deleteUser:         'حذف المستخدم',
    fullName:           'الاسم الكامل',
    usernameLabel:      'اسم المستخدم',
    passwordLabel:      'كلمة المرور',
    newPassword:        'كلمة مرور جديدة (اتركه فارغاً للإبقاء)',
    allowedModules:     'الوحدات المسموح بها',
    noUsersFound:       'لا يوجد مستخدمون',
    userSaved:          'تم حفظ المستخدم.',
    userDeleted:        'تم حذف المستخدم.',
    confirmDeleteUser:  'حذف هذا المستخدم؟ لا يمكن التراجع.',
    settings:           'الإعدادات',
    companyName:        'اسم الشركة',
    timezone:           'المنطقة الزمنية',
    sessionTimeout:     'مهلة الجلسة (دقيقة)',
    passwordRotation:   'تدوير كلمة المرور (أيام)',
    requireMfa:         'مصادقة ثنائية للمشرفين',
    loginAlerts:        'تنبيهات تسجيل الدخول',
    approvalEscalation: 'تصعيد الموافقات',
    weekendApprovals:   'السماح بالموافقات في عطلة نهاية الأسبوع',
    dailyDigest:        'ملخص يومي',
    saveSettings:       'حفظ الإعدادات',
    employeeList:       'قائمة الموظفين',
    labourLaw:          'قانون العمل',
    currentUpdates:     'التحديثات الحالية',
    addNewEmployee:     'إضافة موظف جديد',
    fillEmployeeDetails:'أدخل بيانات الموظف أدناه.',
    idNumber:           'رقم الهوية',
    employeeCode:       'رمز الموظف',
    performanceRating:  'تقييم الأداء',
    saveEmployee:       'حفظ الموظف',
    noEmployeesFound:   'لا يوجد موظفون.',
    employeeSaved:      'تم حفظ الموظف.',
    employeeDeleted:    'تم حذف الموظف.',
    confirmDeleteEmployee: 'حذف سجل هذا الموظف؟',
    searchEmployees:    'بحث عن موظفين...',
    ratingLabel:        'التقييم',
    selectDepartment:   'اختر القسم',
    erpDashboard:       'لوحة ERP',
    erpTransactions:    'المعاملات',
    erpLedger:          'دفتر الأستاذ',
    erpAccounts:        'الحسابات',
    erpCurrencies:      'العملات',
    erpMetalRates:      'أسعار المعادن',
    erpReports:         'التقارير',
    erpChartOfAccounts: 'دليل الحسابات',
    erpVouchers:        'القسائم',
    erpDirectDeals:     'الصفقات المباشرة',
    erpInventory:       'المخزون',
    account:            'الحساب',
    debit:              'مدين',
    credit:             'دائن',
    balance:            'الرصيد',
    journal:            'يومية',
    voucher:            'قسيمة',
    transaction:        'معاملة',
    transactions:       'المعاملات',
    ledgerEntry:        'قيد الأستاذ',
    exchangeRate:       'سعر الصرف',
    metalRate:          'سعر المعدن',
    entryType:          'نوع القيد',
    fixing:             'تثبيت',
    nonFixing:          'غير تثبيت',
    docNo:              'رقم المستند',
    docDate:            'تاريخ المستند',
    valueDate:          'تاريخ القيمة',
    customer:           'العميل',
    direction:          'الاتجاه',
    buy:                'شراء',
    sell:               'بيع',
    metal:              'المعدن',
    stockCode:          'رمز المخزون',
    eqOz:               'مكافئ أوقية',
    lineItems:          'بنود السطر',
    addLine:            'إضافة سطر',
    removeLine:         'حذف سطر',
    importLines:        'استيراد البنود',
    exportPdf:          'تصدير PDF',
    exportExcel:        'تصدير Excel',
    downloadTemplate:   'تنزيل القالب',
    importPreview:      'معاينة الاستيراد',
    applyToForm:        'تطبيق على النموذج',
    clearPreview:       'مسح المعاينة',
    validRows:          'صحيح',
    invalidRows:        'غير صحيح',
    totalRows:          'الإجمالي',
    locked:             'مقفل',
    lockedEntryWarning: 'هذا القيد مؤكد ومقفل. المشرف فقط يمكنه التعديل.',
    confirmEntry:       'تأكيد القيد',
    reopenEntry:        'إعادة فتح القيد',
    kpiOverview:        'نظرة عامة على المؤشرات',
    revenue:            'الإيرادات',
    expenses:           'المصروفات',
    invoices:           'الفواتير',
    budget:             'الميزانية',
    payroll:            'كشف الرواتب',
    arAp:               'الذمم المدينة والدائنة',
    goldTracker:        'متتبع الذهب',
    tax:                'الضرائب',
    reports:            'التقارير',
    generalLedger:      'دفتر الأستاذ العام',
    auditTrail:         'سجل المراجعة',
    totalRevenue:       'إجمالي الإيرادات',
    netProfit:          'صافي الربح',
    cashFlow:           'التدفق النقدي',
    outstanding:        'معلق',
    overdue:            'متأخر',
    invoiceId:          'رقم الفاتورة',
    client:             'العميل',
    issueDate:          'تاريخ الإصدار',
    daysOverdue:        'أيام التأخير',
    addInvoice:         'إضافة فاتورة',
    addExpense:         'إضافة مصروف',
    approvedBy:         'بموافقة',
    category:           'التصنيف',
    flagged:            'معلم',
    employee:           'الموظف',
    basic:              'الأساسي',
    allowance:          'البدل',
    deductions:         'الخصومات',
    netPay:             'صافي الراتب',
    annual:             'سنوي',
    spent:              'المنفق',
    receivables:        'الذمم المدينة',
    payables:           'الذمم الدائنة',
    vendor:             'المورد',
    taxType:            'نوع الضريبة',
    period:             'الفترة',
    filed:              'مودع',
    filedDate:          'تاريخ الإيداع',
    liveMonitor:        'مراقبة مباشرة',
    equipment:          'المعدات',
    maintenance:        'الصيانة',
    qualityControl:     'ضبط الجودة',
    shiftManagement:    'إدارة الوردية',
    planning:           'التخطيط',
    alertsReports:      'التنبيهات والتقارير',
    costTracking:       'تتبع التكاليف',
    oee:                'كفاءة المعدات الكلية',
    uptime:             'وقت التشغيل',
    output:             'الإنتاج',
    defectRate:         'معدل العيوب',
    activeLines:        'خطوط نشطة',
    addEquipment:       'إضافة معدة',
    scheduleMaintenance:'جدولة صيانة',
    logDefect:          'تسجيل عيب',
    readiness:          'الجاهزية',
    supplyChain:        'سلسلة التوريد',
    goldSourcing:       'مصادر الذهب',
    transport:          'النقل',
    security:           'الأمن',
    contracts:          'العقود',
    inventory:          'المخزون',
    liveMap:            'الخريطة المباشرة',
    analytics:          'التحليلات',
    opsProjectsNav:          'المشاريع',
    opsProjectsTitle:  'مشاريع العمليات',
    opsShowArchived:    'عرض المؤرشفة',
    opsApplyTemplate:   'تطبيق قالب…',
    opsAddProject:         '+ إضافة مشروع',
    opsProjectsOpen:       'مشاريع مفتوحة',
    opsProjectsCompleted:  'مكتملة',
    opsProjectsIncArchived: '(بما في ذلك المؤرشفة)',
    opsStaleBadge:      'قديمة',
    opsProjectsReminderToastTitle: 'تذكير مشروع',
    opsProjectsReminderToastBody: 'استحق التذكير:',
    opsColTodo: 'للتنفيذ',
    opsColInProgress: 'قيد التنفيذ',
    opsColUnderReview: 'قيد المراجعة',
    opsColBlocked: 'معطّل',
    opsColDone: 'منجز',
    opsProjectsCountOne: 'مشروع',
    opsProjectsCountMany: 'مشاريع',
    opsTeamTemplateTag: '(الفريق)',
    opsProjectsRestrictExternal: 'المشاريع غير متاحة للمورّدين.',
    opsProjectsMetaBy: 'من',
    opsProjectsMetaUpd: 'تحديث',
    opsProjectsChecklistPct: 'قائمة التحقق',
    opsLinkedSupplyChain: 'سلسلة التوريد',
    opsLinkedGoldSourcing: 'مصادر الذهب',
    opsLinkedTransport: 'النقل',
    opsLinkedSecurity: 'الأمن',
    opsLinkedVendorContracts: 'عقود المورّدين',
    opsLinkedInventory: 'المخزون',
    opsModalTitleEdit: 'تعديل مشروع',
    opsModalTitleAdd: 'إضافة مشروع',
    opsModalSubEdit: 'تحديث تفاصيل المشروع',
    opsModalSubAdd: 'إنشاء مشروع عمليات جديد',
    opsModalSaveChanges: 'حفظ التغييرات',
    opsModalSaveAdd: 'إضافة مشروع',
    opsModalFieldTitle: 'عنوان المشروع',
    opsModalPlaceholderShortTitle: 'عنوان قصير',
    opsModalFieldAssign: 'تعيين إلى',
    opsModalAssignSearchPlaceholder: 'ابحث عن عضو الفريق…',
    opsModalAssignManualPlaceholder: 'عضو الفريق',
    opsModalFieldDescription: 'الوصف',
    opsModalDescPlaceholder: 'تفاصيل المشروع…',
    opsModalFieldPriority: 'الأولوية',
    opsModalFieldDue: 'تاريخ الاستحقاق',
    opsModalFieldLinked: 'القسم المرتبط',
    opsModalFieldStatus: 'الحالة',
    opsModalFieldReminder: 'تذكير',
    opsModalFieldHours: 'ساعات تقديرية / مسجّلة',
    opsModalHoursEst: 'تقدير',
    opsModalHoursLogged: 'مسجّل',
    opsModalFieldTags: 'وسوم (مفصولة بفاصلة)',
    opsModalTagsPlaceholder: 'مثال: legal, urgent',
    opsModalBlockedReason: 'سبب التعطيل',
    opsModalBlockedReasonPh: 'لماذا معطّلة؟',
    opsModalBlockedBy: 'معطّلة بسبب مشروع',
    opsModalNoneDash: '—',
    opsModalChecklistHeading: 'قائمة التحقق',
    opsModalChecklistStepPh: 'عنوان الخطوة',
    opsModalRemoveChecklistItem: 'إزالة عنصر',
    opsModalChecklistAdd: '+ عنصر قائمة',
    opsModalDependsOn: 'تعتمد على (مشاريع عمليات أخرى)',
    opsModalNotifyMessage: 'رسالة إشعار (اختياري)',
    opsModalNotifyPlaceholder: 'تُضمّن مع الحفظ / الإنشاء',
    opsModalAlsoNotify: 'إشعار أيضاً (الفريق)',
    opsModalAttachments: 'المرفقات',
    opsModalUploadedTitle: 'تم الرفع',
    opsModalUploadFailed: 'فشل الرفع',
    opsModalRemoveFileConfirm: 'إزالة هذا الملف؟',
    opsModalRemovedTitle: 'تمت الإزالة',
    opsModalDeleteFailed: 'فشل الحذف',
    opsModalRemove: 'إزالة',
    opsModalArchive: 'أرشفة المشروع',
    opsModalTemplateNamePrompt: 'اسم القالب',
    opsModalMyTemplate: 'قالب',
    opsModalTemplateSavedLocal: 'تم الحفظ',
    opsModalTemplateLocalError: 'تعذّر حفظ القالب',
    opsModalSaveLocalTemplate: 'حفظ كقالب محلي',
    opsModalTemplateSavedTeam: 'تم حفظ قالب الفريق',
    opsModalTemplateTeamError: 'تعذّر حفظ قالب الفريق',
    opsModalSaveTeamTemplate: 'حفظ في مكتبة الفريق',
    opsModalProgressHeading: 'تحديثات التقدّم',
    opsModalNoProgressYet: 'لا تحديثات بعد.',
    opsModalDash: '—',
    opsModalAddProgressLabel: 'إضافة تحديث تقدّم',
    opsModalProgressPlaceholder: 'ما الذي تغيّر؟',
    opsModalLogProgress: 'تسجيل التحديث',
    opsPriCritical: 'حرج',
    opsPriHigh: 'مرتفع',
    opsPriMedium: 'متوسط',
    opsPriLow: 'منخفض',
    opsStatusTodo: 'للتنفيذ',
    opsStatusInProgress: 'قيد التنفيذ',
    opsStatusUnderReview: 'قيد المراجعة',
    opsStatusBlocked: 'معطّل',
    opsStatusDone: 'منجز',
    opsProjectsUpdateSingular: 'تحديث',
    opsProjectsUpdatePlural: 'تحديثات',
    opsProjectsDueLabel: 'الاستحقاق:',
    opsProjectsReminderSet: 'تم ضبط التذكير',
    opsAutoArchiveHint: 'أرشفة تلقائية',
    opsNoProjectsInColumn: 'لا مشاريع',
    opsProjectsListViewTitle: 'عرض قائمة المشاريع',
    opsThProject: 'المشروع',
    opsThAssigned: 'المكلّف',
    opsThPriority: 'الأولوية',
    opsThDue: 'الاستحقاق',
    opsThStatus: 'الحالة',
    opsThSection: 'القسم',
    opsThMeta: 'بيانات',
    opsThActions: 'إجراءات',
    opsArchived: 'مؤرشف',
    opsBtnArchive: 'أرشفة',
    opsBtnDel: 'حذف',
    opsBtnUnarchive: 'إلغاء الأرشفة',
    opsUnarchiveConfirm: 'استعادة هذا المشروع من الأرشيف؟',
    opsUnarchiveToastTitle: 'تمت الاستعادة',
    opsArchivedProjectBanner: 'هذا المشروع مؤرشف وقد يختفي من اللوحة حتى تعرض المؤرشفة.',
    addRoute:           'إضافة مسار',
    addVendor:          'إضافة بائع',
    addItem:            'إضافة عنصر',
    eligibilityStatus:  'حالة الأهلية',
    approvalsTracker:   'متتبع الموافقات',
    documentation:      'الوثائق',
    regulatoryUpdates:  'التحديثات التنظيمية',
    agreements:         'الاتفاقيات',
    permit:             'التصريح',
    entity:             'الكيان',
    authority:          'الجهة',
    filing:             'الملف',
    submittedDate:      'تاريخ التقديم',
    refNo:              'الرقم المرجعي',
    owner:              'المالك',
    version:            'الإصدار',
    expiry:             'تاريخ الانتهاء',
    impact:             'التأثير',
    actionOwner:        'مالك الإجراء',
    partner:            'الشريك',
    agreementType:      'نوع الاتفاقية',
    startDate:          'تاريخ البدء',
    endDate:            'تاريخ الانتهاء',
    value:              'القيمة',
    calendar:           'التقويم',
    batches:            'الدفعات',
    resources:          'الموارد',
    assessments:        'التقييمات',
    certifications:     'الشهادات',
    feedback:           'التغذية الراجعة',
    trainees:           'المتدربون',
    skillGap:           'فجوة المهارات',
    trainer:            'المدرب',
    batch:              'الدفعة',
    venue:              'المكان',
    programme:          'البرنامج',
    score:              'الدرجة',
    pass:               'ناجح',
    fail:               'راسب',
    completion:         'الإتمام',
    sessionTitle:       'عنوان الجلسة',
    addSession:         'إضافة جلسة',
    addBatch:           'إضافة دفعة',
    crmDashboard:       'لوحة إدارة العملاء',
    contacts:           'جهات الاتصال',
    companies:          'الشركات',
    leads:              'العملاء المحتملون',
    deals:              'الصفقات',
    activities:         'الأنشطة',
    followups:          'المتابعات',
    addContact:         'إضافة جهة اتصال',
    addCompany:         'إضافة شركة',
    addDeal:            'إضافة صفقة',
    addActivity:        'إضافة نشاط',
    stage:              'المرحلة',
    contactType:        'نوع جهة الاتصال',
    leadStage:          'مرحلة العميل المحتمل',
    dealStage:          'مرحلة الصفقة',
    activityType:       'نوع النشاط',
    lastActivity:       'آخر نشاط',
    nextAction:         'الإجراء التالي',
    pipelineValue:      'قيمة خط الأنابيب',
    conversionRate:     'معدل التحويل',
    openDeals:          'صفقات مفتوحة',
    closedDeals:        'صفقات مغلقة',
    activeContacts:     'جهات اتصال نشطة',
    searchContacts:     'بحث جهات الاتصال...',
    searchCompanies:    'بحث الشركات...',
    searchLeads:        'بحث العملاء المحتملين...',
    searchDeals:        'بحث الصفقات...',
    exportCsv:          'تصدير CSV',
    importCsv:          'استيراد CSV',
    messages:           'الرسائل',
    typeMessage:        'اكتب رسالة...',
    sendMessage:        'إرسال',
    groups:             'المجموعات',
    direct:             'مباشر',
    muted:              'مكتوم',
    unread:             'غير مقروء',
    today:              'اليوم',
    yesterday:          'أمس',
    noMessages:         'لا توجد رسائل. ابدأ المحادثة!',
    attachFile:         'إرفاق ملف',
    chatSearch:         'بحث في المحادثات...',
    voucherList:        'القسائم',
    createVoucher:      'إنشاء قسيمة',
    voucherNo:          'رقم المستند',
    voucherDate:        'تاريخ القسيمة',
    voucherType:        'نوع القسيمة',
    paymentVoucher:     'قسيمة دفع',
    receiptVoucher:     'قسيمة استلام',
    journalVoucher:     'قيد يومية',
    approvalWorkflow:   'سير الموافقة',
    workflowNote:       'السبب / الملاحظة',
    enterReason:        'أدخل السبب (مطلوب)',
    reasonRequired:     'السبب مطلوب.',
    attachments:        'المرفقات',
    uploadAttachment:   'رفع مرفق',
    noAttachments:      'لا توجد مرفقات.',
    auditLog:           'سجل التدقيق',
    comments:           'التعليقات',
    addComment:         'إضافة تعليق',
    postComment:        'نشر التعليق',
    moduleUnderConstruction: 'الوحدة قيد الإنشاء',
    plannedSections:    'الأقسام المخطط لها',
    builtAsRequired:    'سيتم بناء هذا القسم بمجرد تأكيد المتطلبات.',
  },

  uz: {
    appName:            'Ops Dashboard',
    controlSystem:      'Boshqaruv tizimi',
    overview:           "Umumiy ko'rinish",
    chat:               'Chat',
    admin:              'Admin',
    hr:                 'Kadrlar',
    compliance:         'Muvofiqlik',
    production:         'Ishlab chiqarish',
    finance:            'Moliya',
    sales:              'Savdo',
    operations:         'Operatsiyalar',
    training:           "O'quv",
    erp:                'ERP',
    adminSection:       'Admin',
    departments:        "Bo'limlar",
    signIn:             'KIRISH',
    signOut:            'Chiqish',
    username:           'Foydalanuvchi nomi',
    password:           'Parol',
    enterUsername:      'Foydalanuvchi nomini kiriting',
    enterPassword:      'Parolni kiriting',
    signingIn:          'Kirilmoqda...',
    accessByInvitation: 'Faqat taklif orqali kirish',
    operationsControl:  'Operatsiyalarni boshqarish tizimi',
    readOnly:           "Faqat o'qish",
    loginErrEmpty:      'Foydalanuvchi nomi va parolni kiriting.',
    loginErrNetwork:    "Serverga ulanib bo'lmadi. Aloqangizni tekshiring.",
    loginErrServer:     "Kirish vaqtida server xatosi. Qayta urinib ko'ring.",
    loginErrInvalid:    "Noto'g'ri foydalanuvchi nomi yoki parol.",
    superAdmin:         'Super Admin',
    management:         'Boshqaruv',
    deptHead:           "Bo'lim boshlig'i",
    deptUser:           "Bo'lim xodimi",
    external:           'Tashqi',
    loadingModule:      'Modul yuklanmoqda...',
    moduleFailedLoad:   'Bu modul yuklanmadi.',
    dashboardStillAvail:"Qolgan qismlar mavjud. Yorliqlarni almashtiring yoki qayta yuklang.",
    selectTab:          'Yon paneldan yorliq tanlang',
    pageNotFound:       'Sahifa topilmadi',
    backToDashboard:    "Dashboardga qaytish",
    dashboard:          'Dashboard',
    language:           'Til',
    noData:             "Ma'lumot yo'q",
    loading:            'Yuklanmoqda...',
    saving:             'Saqlanmoqda...',
    saved:              'Saqlandi',
    error:              'Xato',
    success:            'Muvaffaqiyat',
    save:               'Saqlash',
    cancel:             'Bekor qilish',
    delete:             "O'chirish",
    edit:               'Tahrirlash',
    add:                "Qo'shish",
    create:             'Yaratish',
    update:             'Yangilash',
    search:             'Qidirish',
    filter:             'Filtrlash',
    export:             'Eksport',
    import:             'Import',
    print:              'Chop etish',
    close:              'Yopish',
    confirm:            'Tasdiqlash',
    submit:             'Yuborish',
    approve:            'Tasdiqlash',
    reject:             'Rad etish',
    back:               'Orqaga',
    next:               'Keyingi',
    done:               'Bajarildi',
    view:               "Ko'rish",
    reset:              'Tiklash',
    clear:              'Tozalash',
    apply:              "Qo'llash",
    remove:             "Olib tashlash",
    send:               'Yuborish',
    download:           'Yuklab olish',
    upload:             'Yuklash',
    post:               'Joylashtirish',
    reopen:             'Qayta ochish',
    returnForEdit:      'Tahrirlash uchun qaytarish',
    all:                'Barchasi',
    none:               'Hech biri',
    yes:                'Ha',
    no:                 "Yo'q",
    actions:            'Harakatlar',
    details:            'Tafsilotlar',
    summary:            'Xulosa',
    total:              'Jami',
    subtotal:           'Qisman jami',
    notes:              'Eslatmalar',
    remarks:            'Izohlar',
    status:             'Holat',
    type:               'Tur',
    date:               'Sana',
    amount:             'Summa',
    currency:           'Valyuta',
    description:        'Tavsif',
    reference:          'Havola',
    department:         "Bo'lim",
    role:               'Rol',
    name:               'Ism',
    code:               'Kod',
    phone:              'Telefon',
    address:            'Manzil',
    email:              'Elektron pochta',
    quantity:           'Miqdor',
    price:              'Narx',
    rate:               'Kurs',
    branch:             'Filial',
    from:               'Dan',
    to:                 'Ga',
    by:                 'Tomonidan',
    of:                 'ning',
    statusDraft:        'Qoralama',
    statusSubmitted:    'Yuborilgan',
    statusApproved:     'Tasdiqlangan',
    statusPosted:       'Joylashtirilgan',
    statusReturned:     'Qaytarilgan',
    statusRejected:     'Rad etilgan',
    statusActive:       'Faol',
    statusInactive:     'Faol emas',
    statusPending:      'Kutilmoqda',
    statusCompleted:    'Bajarilgan',
    statusCancelled:    'Bekor qilingan',
    statusOnHold:       "To'xtatilgan",
    statusUnderReview:  "Ko'rib chiqilmoqda",
    statusScheduled:    'Rejalashtirilgan',
    statusInProgress:   'Jarayonda',
    statusOverdue:      "Muddati o'tgan",
    statusProcessed:    'Qayta ishlangan',
    statusExpired:      'Muddati tugagan',
    statusExpiringSoon: 'Tez orada tugaydi',
    statusPaid:         "To'langan",
    statusSent:         'Yuborilgan',
    statusFiled:        'Topshirilgan',
    statusEligible:     'Mos',
    statusConfirmed:    'Tasdiqlangan',
    priorityLow:        'Past',
    priorityMedium:     "O'rta",
    priorityHigh:       'Yuqori',
    priorityCritical:   'Kritik',
    executiveDashboard: 'Boshqaruv paneli',
    quickActions:       'Tezkor harakatlar',
    recentAlerts:       'Oxirgi ogohlantirishlar',
    recentMessages:     'Oxirgi xabarlar',
    myTasks:            'Mening vazifalarim',
    leaveRequests:      "Ta'til so'rovlari",
    departmentStatus:   "Bo'limlar holati",
    addTask:            "Vazifa qo'shish",
    addEmployee:        "Xodim qo'shish",
    addLead:            "Potentsial mijoz qo'shish",
    logExpense:         'Xarajat kiritish',
    addSupplier:        "Ta'minotchi qo'shish",
    scheduleMeeting:    'Uchrashuv rejalash',
    createInvoice:      'Hisob-faktura yaratish',
    logIncident:        'Hodisa kiritish',
    generateReport:     'Hisobot yaratish',
    globalSearch:       'Umumiy qidirish',
    newTask:            'Yangi vazifa',
    newEmployee:        'Yangi xodim',
    newInvoice:         'Yangi hisob-faktura',
    newLead:            'Yangi potentsial mijoz',
    newMaintenanceTask: 'Yangi texnik xizmat vazifasi',
    newComplianceIssue: 'Yangi muvofiqlik muammosi',
    newAnnouncement:    "Yangi e'lon",
    taskTitle:          'Vazifa sarlavhasi',
    assignTo:           'Tayinlash',
    dueDate:            'Muddat',
    priority:           'Ustuvorlik',
    todoStatus:         'Bajarilishi kerak',
    inProgressStatus:   'Jarayonda',
    blockedStatus:      'Bloklangan',
    underReviewStatus:  "Ko'rib chiqilmoqda",
    completedStatus:    'Bajarilgan',
    cancelledStatus:    'Bekor qilingan',
    noTasksFound:       'Vazifalar topilmadi',
    viewAll:            "Barchasini ko'rish",
    markDone:           'Bajarildi deb belgilash',
    dismiss:            'Yopish',
    attendance:         'Davomat',
    present:            'Kelgan',
    absent:             'Kelmagan',
    late:               'Kech kelgan',
    onLeave:            "Ta'tilda",
    userManagement:     'Foydalanuvchilarni boshqarish',
    systemSettings:     'Tizim sozalamalari',
    addUser:            "Foydalanuvchi qo'shish",
    editUser:           'Foydalanuvchini tahrirlash',
    deleteUser:         "Foydalanuvchini o'chirish",
    fullName:           "To'liq ism",
    usernameLabel:      'Foydalanuvchi nomi',
    passwordLabel:      'Parol',
    newPassword:        "Yangi parol (bo'sh qoldiring - o'zgarmaydi)",
    allowedModules:     'Ruxsat etilgan modullar',
    noUsersFound:       'Foydalanuvchilar topilmadi',
    userSaved:          'Foydalanuvchi saqlandi.',
    userDeleted:        "Foydalanuvchi o'chirildi.",
    confirmDeleteUser:  "Bu foydalanuvchini o'chirasizmi?",
    settings:           'Sozlamalar',
    companyName:        'Kompaniya nomi',
    timezone:           'Vaqt mintaqasi',
    sessionTimeout:     'Sessiya muddati (daqiqa)',
    passwordRotation:   'Parol yangilash (kun)',
    requireMfa:         'Adminlar uchun ikki bosqichli tekshiruv',
    loginAlerts:        'Kirish ogohlantirishlari',
    approvalEscalation: "Tasdiqlashni yuqoriga ko'tarish",
    weekendApprovals:   'Dam olish kunlarida tasdiqlashga ruxsat',
    dailyDigest:        'Kunlik xulosa',
    saveSettings:       'Sozlamalarni saqlash',
    employeeList:       "Xodimlar ro'yxati",
    labourLaw:          'Mehnat qonunchiligi',
    currentUpdates:     'Joriy yangilanishlar',
    addNewEmployee:     "Yangi xodim qo'shish",
    fillEmployeeDetails:"Xodim ma'lumotlarini to'ldiring.",
    idNumber:           'ID raqam',
    employeeCode:       'Xodim kodi',
    performanceRating:  'Samaradorlik reytingi',
    saveEmployee:       'Xodimni saqlash',
    noEmployeesFound:   'Xodimlar topilmadi.',
    employeeSaved:      'Xodim saqlandi.',
    employeeDeleted:    "Xodim o'chirildi.",
    confirmDeleteEmployee: "Bu xodim yozuvini o'chirasizmi?",
    searchEmployees:    'Xodimlarni qidirish...',
    ratingLabel:        'Reyting',
    selectDepartment:   "Bo'limni tanlang",
    erpDashboard:       'Dashboard',
    erpTransactions:    'Tranzaksiyalar',
    erpLedger:          'Bosh daftar',
    erpAccounts:        'Hisoblar',
    erpCurrencies:      'Valyutalar',
    erpMetalRates:      'Metall narxlari',
    erpReports:         'Hisobotlar',
    erpChartOfAccounts: 'Hisoblar rejasi',
    erpVouchers:        'Orderlar',
    erpDirectDeals:     "To'g'ridan-to'g'ri bitimlar",
    erpInventory:       'Inventar',
    account:            'Hisob',
    debit:              'Debet',
    credit:             'Kredit',
    balance:            'Balans',
    journal:            'Jurnal',
    voucher:            'Order',
    transaction:        'Tranzaksiya',
    transactions:       'Tranzaksiyalar',
    ledgerEntry:        'Bosh daftar yozuvi',
    exchangeRate:       'Valyuta kursi',
    metalRate:          'Metall kursi',
    entryType:          'Yozuv turi',
    fixing:             'Belgilangan',
    nonFixing:          'Belgilanmagan',
    docNo:              'Hujjat raqami',
    docDate:            'Hujjat sanasi',
    valueDate:          'Qiymat sanasi',
    customer:           'Mijoz',
    direction:          "Yo'nalish",
    buy:                'Sotib olish',
    sell:               'Sotish',
    metal:              'Metall',
    stockCode:          'Aksiya kodi',
    eqOz:               'Teng. untsiya',
    lineItems:          'Satr bandlari',
    addLine:            "Satr qo'shish",
    removeLine:         "Satrni o'chirish",
    importLines:        'Bandlarni import qilish',
    exportPdf:          'PDF eksport',
    exportExcel:        'Excel eksport',
    downloadTemplate:   'Shablonni yuklab olish',
    importPreview:      "Import oldindan ko'rish",
    applyToForm:        "Formaga qo'llash",
    clearPreview:       "Ko'rishni tozalash",
    validRows:          "To'g'ri",
    invalidRows:        "Noto'g'ri",
    totalRows:          'Jami',
    locked:             'Qulflangan',
    lockedEntryWarning: 'Bu yozuv tasdiqlangan va qulflangan. Faqat Admin tahrirlashi mumkin.',
    confirmEntry:       'Yozuvni tasdiqlash',
    reopenEntry:        'Yozuvni qayta ochish',
    kpiOverview:        'KPI sharhi',
    revenue:            'Daromad',
    expenses:           'Xarajatlar',
    invoices:           'Hisob-fakturalar',
    budget:             'Byudjet',
    payroll:            'Ish haqi',
    arAp:               'Debitorlik va kreditorlik',
    goldTracker:        'Oltin kuzatuv',
    tax:                'Soliq',
    reports:            'Hisobotlar',
    generalLedger:      'Bosh daftar',
    auditTrail:         'Audit izi',
    totalRevenue:       'Jami daromad',
    netProfit:          'Sof foyda',
    cashFlow:           'Pul oqimi',
    outstanding:        'Qolingan',
    overdue:            "Muddati o'tgan",
    invoiceId:          'Hisob-faktura ID',
    client:             'Mijoz',
    issueDate:          'Chiqarilgan sana',
    daysOverdue:        'Kechikkan kunlar',
    addInvoice:         "Hisob-faktura qo'shish",
    addExpense:         "Xarajat qo'shish",
    approvedBy:         'Tasdiqlagan',
    category:           'Toifa',
    flagged:            'Belgilangan',
    employee:           'Xodim',
    basic:              'Asosiy',
    allowance:          'Nafaqa',
    deductions:         'Ushlab qolishlar',
    netPay:             'Sof ish haqi',
    annual:             'Yillik',
    spent:              'Sarflangan',
    receivables:        'Debitorlik',
    payables:           'Kreditorlik',
    vendor:             "Ta'minotchi",
    taxType:            'Soliq turi',
    period:             'Davr',
    filed:              'Topshirilgan',
    filedDate:          'Topshirilgan sana',
    liveMonitor:        'Jonli monitoring',
    equipment:          'Uskunalar',
    maintenance:        'Texnik xizmat',
    qualityControl:     'Sifat nazorati',
    shiftManagement:    'Smenani boshqarish',
    planning:           'Rejalashtirish',
    alertsReports:      'Ogohlantirishlar va hisobotlar',
    costTracking:       'Xarajatlarni kuzatish',
    oee:                'Uskuna samaradorligi',
    uptime:             'Ishlash vaqti',
    output:             'Chiqish',
    defectRate:         'Nuqson darajasi',
    activeLines:        'Faol liniyalar',
    addEquipment:       "Uskuna qo'shish",
    scheduleMaintenance:'Texnik xizmatni rejalashtirish',
    logDefect:          'Nuqson kiritish',
    readiness:          'Tayyorlik',
    supplyChain:        "Ta'minot zanjiri",
    goldSourcing:       'Oltin manbai',
    transport:          'Transport',
    security:           'Xavfsizlik',
    contracts:          'Shartnomalar',
    inventory:          'Inventar',
    liveMap:            'Jonli xarita',
    analytics:          'Tahlillar',
    opsProjectsNav:          'Loyihalar',
    opsProjectsTitle:  'Operatsiya loyihalari',
    opsShowArchived:    'Arxivlanganlarni ko‘rsatish',
    opsApplyTemplate:   'Shablon qo‘llash…',
    opsAddProject:         '+ Loyiha qo‘shish',
    opsProjectsOpen:       'ochiq loyihalar',
    opsProjectsCompleted:  'bajarilgan',
    opsProjectsIncArchived: '(arxivlanganlar bilan)',
    opsStaleBadge:      'ESKIRGAN',
    opsProjectsReminderToastTitle: 'Loyiha eslatmasi',
    opsProjectsReminderToastBody: 'Eslatma muddati:',
    opsColTodo: 'Bajarish kerak',
    opsColInProgress: 'Jarayonda',
    opsColUnderReview: 'Ko‘rib chiqilmoqda',
    opsColBlocked: 'Bloklangan',
    opsColDone: 'Bajarilgan',
    opsProjectsCountOne: 'loyiha',
    opsProjectsCountMany: 'loyihalar',
    opsTeamTemplateTag: '(jamoa)',
    opsProjectsRestrictExternal: 'Loyihalar yetkazib beruvchilar uchun mavjud emas.',
    opsProjectsMetaBy: 'Kimdan',
    opsProjectsMetaUpd: 'Yang.',
    opsProjectsChecklistPct: 'Tekshiruv ro‘yxati',
    opsLinkedSupplyChain: 'Ta’minot zanjiri',
    opsLinkedGoldSourcing: 'Oltin manbalari',
    opsLinkedTransport: 'Transport',
    opsLinkedSecurity: 'Xavfsizlik',
    opsLinkedVendorContracts: 'Yetkazib beruvchi shartnomalari',
    opsLinkedInventory: 'Inventar',
    opsModalTitleEdit: 'Loyihani tahrirlash',
    opsModalTitleAdd: 'Loyiha qo‘shish',
    opsModalSubEdit: 'Loyiha tafsilotlarini yangilash',
    opsModalSubAdd: 'Yangi operatsion loyiha yaratish',
    opsModalSaveChanges: 'O‘zgarishlarni saqlash',
    opsModalSaveAdd: 'Loyiha qo‘shish',
    opsModalFieldTitle: 'Loyiha nomi',
    opsModalPlaceholderShortTitle: 'Qisqa nom',
    opsModalFieldAssign: 'Ijrochi',
    opsModalAssignSearchPlaceholder: 'Jamoa a’zosini qidiring…',
    opsModalAssignManualPlaceholder: 'Jamoa a’zosi',
    opsModalFieldDescription: 'Tavsif',
    opsModalDescPlaceholder: 'Loyiha tafsilotlari…',
    opsModalFieldPriority: 'Muhimlik',
    opsModalFieldDue: 'Muddati',
    opsModalFieldLinked: 'Bog‘langan bo‘lim',
    opsModalFieldStatus: 'Holat',
    opsModalFieldReminder: 'Eslatma',
    opsModalFieldHours: 'Taxminiy soatlar / yozilgan',
    opsModalHoursEst: 'Taxmin',
    opsModalHoursLogged: 'Yozilgan',
    opsModalFieldTags: 'Teglar (vergul bilan)',
    opsModalTagsPlaceholder: 'masalan: legal, urgent',
    opsModalBlockedReason: 'Blok sababi',
    opsModalBlockedReasonPh: 'Nima uchun bloklangan?',
    opsModalBlockedBy: 'Bloklovchi loyiha',
    opsModalNoneDash: '—',
    opsModalChecklistHeading: 'Tekshiruv ro‘yxati',
    opsModalChecklistStepPh: 'Qadam nomi',
    opsModalRemoveChecklistItem: 'Bandni olib tashlash',
    opsModalChecklistAdd: '+ Ro‘yxat bandi',
    opsModalDependsOn: 'Bog‘liq (boshqa operatsion loyihalar)',
    opsModalNotifyMessage: 'Bildirishnoma matni (ixtiyoriy)',
    opsModalNotifyPlaceholder: 'Saqlash / yaratish bilan birga',
    opsModalAlsoNotify: 'Shuningdek xabar berish (jamoa)',
    opsModalAttachments: 'Ilovalar',
    opsModalUploadedTitle: 'Yuklandi',
    opsModalUploadFailed: 'Yuklash muvaffaqiyatsiz',
    opsModalRemoveFileConfirm: 'Bu faylni olib tashlaysizmi?',
    opsModalRemovedTitle: 'Olib tashlandi',
    opsModalDeleteFailed: 'O‘chirish muvaffaqiyatsiz',
    opsModalRemove: 'Olib tashlash',
    opsModalArchive: 'Loyihani arxivlash',
    opsModalTemplateNamePrompt: 'Shablon nomi',
    opsModalMyTemplate: 'Mening shablonim',
    opsModalTemplateSavedLocal: 'Saqlandi',
    opsModalTemplateLocalError: 'Shablonni saqlab bo‘lmadi',
    opsModalSaveLocalTemplate: 'Mahalliy shablon sifatida saqlash',
    opsModalTemplateSavedTeam: 'Jamoa shabloni saqlandi',
    opsModalTemplateTeamError: 'Jamoa shablonini saqlab bo‘lmadi',
    opsModalSaveTeamTemplate: 'Jamoa kutubxonasiga saqlash',
    opsModalProgressHeading: 'Jarayon yangilanishlari',
    opsModalNoProgressYet: 'Hali yangilanishlar yo‘q.',
    opsModalDash: '—',
    opsModalAddProgressLabel: 'Jarayon yangilanishi qo‘shish',
    opsModalProgressPlaceholder: 'Nima o‘zgardi?',
    opsModalLogProgress: 'Yangilanishni yozish',
    opsPriCritical: 'Kritik',
    opsPriHigh: 'Yuqori',
    opsPriMedium: 'O‘rta',
    opsPriLow: 'Past',
    opsStatusTodo: 'Bajarish kerak',
    opsStatusInProgress: 'Jarayonda',
    opsStatusUnderReview: 'Ko‘rib chiqilmoqda',
    opsStatusBlocked: 'Bloklangan',
    opsStatusDone: 'Bajarilgan',
    opsProjectsUpdateSingular: 'yangilanish',
    opsProjectsUpdatePlural: 'yangilanishlar',
    opsProjectsDueLabel: 'Muddati:',
    opsProjectsReminderSet: 'Eslatma o‘rnatilgan',
    opsAutoArchiveHint: 'Avtoarxiv',
    opsNoProjectsInColumn: 'Loyihalar yo‘q',
    opsProjectsListViewTitle: 'Loyihalar ro‘yxati',
    opsThProject: 'Loyiha',
    opsThAssigned: 'Ijrochi',
    opsThPriority: 'Muhimlik',
    opsThDue: 'Muddat',
    opsThStatus: 'Holat',
    opsThSection: 'Bo‘lim',
    opsThMeta: 'Meta',
    opsThActions: 'Harakatlar',
    opsArchived: 'Arxivlangan',
    opsBtnArchive: 'Arxivlash',
    opsBtnDel: 'O‘chirish',
    opsBtnUnarchive: 'Arxivdan chiqarish',
    opsUnarchiveConfirm: 'Loyihani arxivdan tiklash?',
    opsUnarchiveToastTitle: 'Tiklandi',
    opsArchivedProjectBanner: 'Bu loyiha arxivlangan. Arxivni ko‘rsatmaguncha taxtadan yo‘qolishi mumkin.',
    addRoute:           "Marshrut qo'shish",
    addVendor:          "Sotuvchi qo'shish",
    addItem:            "Element qo'shish",
    eligibilityStatus:  'Moslik holati',
    approvalsTracker:   'Tasdiqlashlar kuzatuvi',
    documentation:      'Hujjatlar',
    regulatoryUpdates:  'Tartibga solish yangilanishlari',
    agreements:         'Kelishuvlar',
    permit:             'Ruxsatnoma',
    entity:             'Tashkilot',
    authority:          'Organ',
    filing:             'Fayl',
    submittedDate:      'Topshirilgan sana',
    refNo:              'Ref. raqam',
    owner:              'Egasi',
    version:            'Versiya',
    expiry:             'Amal qilish muddati',
    impact:             "Ta'sir",
    actionOwner:        'Harakat egasi',
    partner:            'Hamkor',
    agreementType:      'Kelishuv turi',
    startDate:          'Boshlanish sanasi',
    endDate:            'Tugash sanasi',
    value:              'Qiymat',
    calendar:           'Taqvim',
    batches:            'Guruhlar',
    resources:          'Resurslar',
    assessments:        'Baholashlar',
    certifications:     'Sertifikatlar',
    feedback:           'Fikr-mulohazalar',
    trainees:           'Tinglovchilar',
    skillGap:           "Ko'nikma bo'shligi",
    trainer:            'Murabbiy',
    batch:              'Guruh',
    venue:              'Joyi',
    programme:          'Dastur',
    score:              'Ball',
    pass:               "O'tdi",
    fail:               'Yiqildi',
    completion:         'Bajarilish',
    sessionTitle:       'Sessiya sarlavhasi',
    addSession:         "Sessiya qo'shish",
    addBatch:           "Guruh qo'shish",
    crmDashboard:       'CRM paneli',
    contacts:           'Kontaktlar',
    companies:          'Kompaniyalar',
    leads:              'Potentsial mijozlar',
    deals:              'Bitimlar',
    activities:         'Faoliyatlar',
    followups:          'Kuzatuv',
    addContact:         "Kontakt qo'shish",
    addCompany:         "Kompaniya qo'shish",
    addDeal:            "Bitim qo'shish",
    addActivity:        "Faoliyat qo'shish",
    stage:              'Bosqich',
    contactType:        'Kontakt turi',
    leadStage:          'Potentsial mijoz bosqichi',
    dealStage:          'Bitim bosqichi',
    activityType:       'Faoliyat turi',
    lastActivity:       'Oxirgi faoliyat',
    nextAction:         'Keyingi harakat',
    pipelineValue:      'Quvur liniyasi qiymati',
    conversionRate:     'Konversiya darajasi',
    openDeals:          'Ochiq bitimlar',
    closedDeals:        'Yopiq bitimlar',
    activeContacts:     'Faol kontaktlar',
    searchContacts:     'Kontaktlarni qidirish...',
    searchCompanies:    'Kompaniyalarni qidirish...',
    searchLeads:        'Potentsial mijozlarni qidirish...',
    searchDeals:        'Bitimlarni qidirish...',
    exportCsv:          'CSV eksport',
    importCsv:          'CSV import',
    messages:           'Xabarlar',
    typeMessage:        'Xabar yozing...',
    sendMessage:        'Yuborish',
    groups:             'Guruhlar',
    direct:             "To'g'ridan-to'g'ri",
    muted:              "Ovoz o'chirilgan",
    unread:             "O'qilmagan",
    today:              'Bugun',
    yesterday:          'Kecha',
    noMessages:         "Xabarlar yo'q. Suhbatni boshlang!",
    attachFile:         'Fayl biriktirish',
    chatSearch:         'Suhbatlarni qidirish...',
    voucherList:        'Orderlar',
    createVoucher:      'Order yaratish',
    voucherNo:          'Hujjat raqami',
    voucherDate:        'Order sanasi',
    voucherType:        'Order turi',
    paymentVoucher:     "To'lov orderi",
    receiptVoucher:     'Qabul orderi',
    journalVoucher:     'Jurnal yozuvi',
    approvalWorkflow:   'Tasdiqlash jarayoni',
    workflowNote:       'Sabab / Eslatma',
    enterReason:        'Sabab kiriting (majburiy)',
    reasonRequired:     'Sabab majburiy.',
    attachments:        'Ilovalar',
    uploadAttachment:   'Ilova yuklash',
    noAttachments:      "Ilovalar yo'q.",
    auditLog:           'Audit jurnali',
    comments:           'Izohlar',
    addComment:         "Izoh qo'shish",
    postComment:        'Izohni joylashtirish',
    moduleUnderConstruction: 'Modul ishlab chiqilmoqda',
    plannedSections:    "Rejalashtirilgan bo'limlar",
    builtAsRequired:    "Bu bo'lim talablar tasdiqlanganidan so'ng quriladi.",
    accounts:           'Hisoblar',
    accountTree:        'Hisob daraxti',
    allTypes:           'Barcha turlar',
    applyFilters:       "Filtrlarni qo'llash",
    cancelEdit:         'Tahrirlashni bekor qilish',
    deleteFailed:       "O'chirish muvaffaqiyatsiz",
    exampleAccountCode: 'M: 1010',
    failedToLoadAccounts: "Hisoblarni yuklab bo'lmadi",
    failedToLoadDirectDeals: "To'g'ridan-to'g'ri bitimlarni yuklab bo'lmadi",
    fixingEntries:      'Fiksatsiya yozuvlari',
    move:               'Ko\'chirish',
    noAccounts:         'Hisob yo\'q',
    noFixingEntriesFound: 'Fiksatsiya yozuvlari topilmadi.',
    nonFixingEntries:   'Fiksatsiyasiz yozuvlar',
    refresh:            'Yangilash',
    rightClickAccountForOptions: "Hisobni sichqonchaning o'ng tugmasi bilan bosing",
    searchByNameOrCode: 'Nom yoki kod bo\'yicha qidirish...',
    selectAccountFromTree: 'Daraxtdan hisob tanlang',
    selectCustomer:     'Mijoz tanlang',
    selectType:         'Turni tanlang...',
    totalAmount:        'Jami summa',
    totalQty:           'Jami miqdor',
  },

  ru: {
    appName:            'Ops Dashboard',
    controlSystem:      'Система управления',
    overview:           'Обзор',
    chat:               'Чат',
    admin:              'Администратор',
    hr:                 'Кадры',
    compliance:         'Соответствие',
    production:         'Производство',
    finance:            'Финансы',
    sales:              'Продажи',
    operations:         'Операции',
    training:           'Обучение',
    erp:                'ERP',
    adminSection:       'Администрирование',
    departments:        'Отделы',
    signIn:             'ВОЙТИ',
    signOut:            'Выйти',
    username:           'Имя пользователя',
    password:           'Пароль',
    enterUsername:      'Введите имя пользователя',
    enterPassword:      'Введите пароль',
    signingIn:          'Вход...',
    accessByInvitation: 'Доступ только по приглашению',
    operationsControl:  'Система управления операциями',
    readOnly:           'Только чтение',
    loginErrEmpty:      'Введите имя пользователя и пароль.',
    loginErrNetwork:    'Не удаётся подключиться к серверу. Проверьте соединение.',
    loginErrServer:     'Ошибка сервера при входе. Попробуйте ещё раз.',
    loginErrInvalid:    'Неверное имя пользователя или пароль.',
    superAdmin:         'Супер Админ',
    management:         'Руководство',
    deptHead:           'Руководитель отдела',
    deptUser:           'Сотрудник отдела',
    external:           'Внешний',
    loadingModule:      'Загрузка модуля...',
    moduleFailedLoad:   'Этот модуль не удалось загрузить.',
    dashboardStillAvail:'Остальная часть панели доступна. Переключите вкладки или перезагрузите.',
    selectTab:          'Выберите вкладку на боковой панели',
    pageNotFound:       'Страница не найдена',
    backToDashboard:    'Вернуться на панель управления',
    dashboard:          'Панель управления',
    language:           'Язык',
    noData:             'Нет данных',
    loading:            'Загрузка...',
    saving:             'Сохранение...',
    saved:              'Сохранено',
    error:              'Ошибка',
    success:            'Успех',
    save:               'Сохранить',
    cancel:             'Отмена',
    delete:             'Удалить',
    edit:               'Изменить',
    add:                'Добавить',
    create:             'Создать',
    update:             'Обновить',
    search:             'Поиск',
    filter:             'Фильтр',
    export:             'Экспорт',
    import:             'Импорт',
    print:              'Печать',
    close:              'Закрыть',
    confirm:            'Подтвердить',
    submit:             'Отправить',
    approve:            'Утвердить',
    reject:             'Отклонить',
    back:               'Назад',
    next:               'Далее',
    done:               'Готово',
    view:               'Просмотр',
    reset:              'Сброс',
    clear:              'Очистить',
    apply:              'Применить',
    remove:             'Удалить',
    send:               'Отправить',
    download:           'Скачать',
    upload:             'Загрузить',
    post:               'Провести',
    reopen:             'Переоткрыть',
    returnForEdit:      'Вернуть на правку',
    all:                'Все',
    none:               'Нет',
    yes:                'Да',
    no:                 'Нет',
    actions:            'Действия',
    details:            'Детали',
    summary:            'Сводка',
    total:              'Итого',
    subtotal:           'Подытог',
    notes:              'Заметки',
    remarks:            'Примечания',
    status:             'Статус',
    type:               'Тип',
    date:               'Дата',
    amount:             'Сумма',
    currency:           'Валюта',
    description:        'Описание',
    reference:          'Ссылка',
    department:         'Отдел',
    role:               'Роль',
    name:               'Имя',
    code:               'Код',
    phone:              'Телефон',
    address:            'Адрес',
    email:              'Эл. почта',
    quantity:           'Количество',
    price:              'Цена',
    rate:               'Курс',
    branch:             'Филиал',
    from:               'От',
    to:                 'До',
    by:                 'Кем',
    of:                 'из',
    statusDraft:        'Черновик',
    statusSubmitted:    'Отправлено',
    statusApproved:     'Утверждено',
    statusPosted:       'Проведено',
    statusReturned:     'Возвращено',
    statusRejected:     'Отклонено',
    statusActive:       'Активно',
    statusInactive:     'Неактивно',
    statusPending:      'В ожидании',
    statusCompleted:    'Завершено',
    statusCancelled:    'Отменено',
    statusOnHold:       'Приостановлено',
    statusUnderReview:  'На рассмотрении',
    statusScheduled:    'Запланировано',
    statusInProgress:   'В процессе',
    statusOverdue:      'Просрочено',
    statusProcessed:    'Обработано',
    statusExpired:      'Истёк',
    statusExpiringSoon: 'Скоро истечёт',
    statusPaid:         'Оплачено',
    statusSent:         'Отправлено',
    statusFiled:        'Подано',
    statusEligible:     'Подходит',
    statusConfirmed:    'Подтверждено',
    priorityLow:        'Низкий',
    priorityMedium:     'Средний',
    priorityHigh:       'Высокий',
    priorityCritical:   'Критический',
    executiveDashboard: 'Панель руководителя',
    quickActions:       'Быстрые действия',
    recentAlerts:       'Последние уведомления',
    recentMessages:     'Последние сообщения',
    myTasks:            'Мои задачи',
    leaveRequests:      'Заявки на отпуск',
    departmentStatus:   'Статус отделов',
    addTask:            'Добавить задачу',
    addEmployee:        'Добавить сотрудника',
    addLead:            'Добавить лида',
    logExpense:         'Записать расход',
    addSupplier:        'Добавить поставщика',
    scheduleMeeting:    'Запланировать встречу',
    createInvoice:      'Создать счёт',
    logIncident:        'Записать инцидент',
    generateReport:     'Создать отчёт',
    globalSearch:       'Глобальный поиск',
    newTask:            'Новая задача',
    newEmployee:        'Новый сотрудник',
    newInvoice:         'Новый счёт',
    newLead:            'Новый лид',
    newMaintenanceTask: 'Новая задача ТО',
    newComplianceIssue: 'Новая проблема соответствия',
    newAnnouncement:    'Новое объявление',
    taskTitle:          'Название задачи',
    assignTo:           'Назначить',
    dueDate:            'Срок',
    priority:           'Приоритет',
    todoStatus:         'К выполнению',
    inProgressStatus:   'В процессе',
    blockedStatus:      'Заблокировано',
    underReviewStatus:  'На рассмотрении',
    completedStatus:    'Завершено',
    cancelledStatus:    'Отменено',
    noTasksFound:       'Задачи не найдены',
    viewAll:            'Просмотреть все',
    markDone:           'Отметить выполненным',
    dismiss:            'Закрыть',
    attendance:         'Посещаемость',
    present:            'Присутствует',
    absent:             'Отсутствует',
    late:               'Опоздал',
    onLeave:            'В отпуске',
    userManagement:     'Управление пользователями',
    systemSettings:     'Настройки системы',
    addUser:            'Добавить пользователя',
    editUser:           'Изменить пользователя',
    deleteUser:         'Удалить пользователя',
    fullName:           'Полное имя',
    usernameLabel:      'Имя пользователя',
    passwordLabel:      'Пароль',
    newPassword:        'Новый пароль (оставьте пустым для сохранения)',
    allowedModules:     'Разрешённые модули',
    noUsersFound:       'Пользователи не найдены',
    userSaved:          'Пользователь сохранён.',
    userDeleted:        'Пользователь удалён.',
    confirmDeleteUser:  'Удалить пользователя? Это нельзя отменить.',
    settings:           'Настройки',
    companyName:        'Название компании',
    timezone:           'Часовой пояс',
    sessionTimeout:     'Тайм-аут сессии (мин)',
    passwordRotation:   'Ротация пароля (дней)',
    requireMfa:         'Требовать MFA для администраторов',
    loginAlerts:        'Уведомления о входе',
    approvalEscalation: 'Эскалация согласований',
    weekendApprovals:   'Разрешить согласование в выходные',
    dailyDigest:        'Ежедневная сводка',
    saveSettings:       'Сохранить настройки',
    employeeList:       'Список сотрудников',
    labourLaw:          'Трудовое законодательство',
    currentUpdates:     'Текущие обновления',
    addNewEmployee:     'Добавить нового сотрудника',
    fillEmployeeDetails:'Заполните данные сотрудника.',
    idNumber:           'Номер удостоверения',
    employeeCode:       'Код сотрудника',
    performanceRating:  'Рейтинг эффективности',
    saveEmployee:       'Сохранить сотрудника',
    noEmployeesFound:   'Сотрудники не найдены.',
    employeeSaved:      'Сотрудник сохранён.',
    employeeDeleted:    'Сотрудник удалён.',
    confirmDeleteEmployee: 'Удалить запись сотрудника?',
    searchEmployees:    'Поиск сотрудников...',
    ratingLabel:        'Рейтинг',
    selectDepartment:   'Выберите отдел',
    erpDashboard:       'Панель ERP',
    erpTransactions:    'Транзакции',
    erpLedger:          'Главная книга',
    erpAccounts:        'Счета',
    erpCurrencies:      'Валюты',
    erpMetalRates:      'Курсы металлов',
    erpReports:         'Отчёты',
    erpChartOfAccounts: 'План счетов',
    erpVouchers:        'Ордера',
    erpDirectDeals:     'Прямые сделки',
    erpInventory:       'Инвентарь',
    account:            'Счёт',
    debit:              'Дебет',
    credit:             'Кредит',
    balance:            'Баланс',
    journal:            'Журнал',
    voucher:            'Ордер',
    transaction:        'Транзакция',
    transactions:       'Транзакции',
    ledgerEntry:        'Запись главной книги',
    exchangeRate:       'Обменный курс',
    metalRate:          'Курс металла',
    entryType:          'Тип записи',
    fixing:             'Фиксинг',
    nonFixing:          'Нефиксинг',
    docNo:              'Номер документа',
    docDate:            'Дата документа',
    valueDate:          'Дата валютирования',
    customer:           'Клиент',
    direction:          'Направление',
    buy:                'Купить',
    sell:               'Продать',
    metal:              'Металл',
    stockCode:          'Код акции',
    eqOz:               'Экв. унция',
    lineItems:          'Строки',
    addLine:            'Добавить строку',
    removeLine:         'Удалить строку',
    importLines:        'Импортировать строки',
    exportPdf:          'Экспорт PDF',
    exportExcel:        'Экспорт Excel',
    downloadTemplate:   'Скачать шаблон',
    importPreview:      'Предпросмотр импорта',
    applyToForm:        'Применить к форме',
    clearPreview:       'Очистить предпросмотр',
    validRows:          'Корректных',
    invalidRows:        'С ошибками',
    totalRows:          'Итого',
    locked:             'Заблокировано',
    lockedEntryWarning: 'Запись подтверждена и заблокирована. Только Администратор может редактировать.',
    confirmEntry:       'Подтвердить запись',
    reopenEntry:        'Переоткрыть запись',
    kpiOverview:        'Обзор KPI',
    revenue:            'Выручка',
    expenses:           'Расходы',
    invoices:           'Счета-фактуры',
    budget:             'Бюджет',
    payroll:            'Зарплатная ведомость',
    arAp:               'Дебиторы и кредиторы',
    goldTracker:        'Трекер золота',
    tax:                'Налог',
    reports:            'Отчёты',
    generalLedger:      'Главная книга',
    auditTrail:         'Журнал аудита',
    totalRevenue:       'Общая выручка',
    netProfit:          'Чистая прибыль',
    cashFlow:           'Денежный поток',
    outstanding:        'Непогашенный',
    overdue:            'Просроченный',
    invoiceId:          'ID счёта',
    client:             'Клиент',
    issueDate:          'Дата выставления',
    daysOverdue:        'Дней просрочки',
    addInvoice:         'Добавить счёт',
    addExpense:         'Добавить расход',
    approvedBy:         'Утверждено',
    category:           'Категория',
    flagged:            'Помечено',
    employee:           'Сотрудник',
    basic:              'Оклад',
    allowance:          'Надбавка',
    deductions:         'Удержания',
    netPay:             'Чистый оклад',
    annual:             'Годовой',
    spent:              'Потрачено',
    receivables:        'Дебиторская задолженность',
    payables:           'Кредиторская задолженность',
    vendor:             'Поставщик',
    taxType:            'Вид налога',
    period:             'Период',
    filed:              'Подано',
    filedDate:          'Дата подачи',
    liveMonitor:        'Онлайн-мониторинг',
    equipment:          'Оборудование',
    maintenance:        'Техническое обслуживание',
    qualityControl:     'Контроль качества',
    shiftManagement:    'Управление сменами',
    planning:           'Планирование',
    alertsReports:      'Предупреждения и отчёты',
    costTracking:       'Отслеживание затрат',
    oee:                'Общая эффективность оборудования',
    uptime:             'Время работы',
    output:             'Производительность',
    defectRate:         'Уровень дефектов',
    activeLines:        'Активные линии',
    addEquipment:       'Добавить оборудование',
    scheduleMaintenance:'Запланировать ТО',
    logDefect:          'Записать дефект',
    readiness:          'Готовность',
    supplyChain:        'Цепочка поставок',
    goldSourcing:       'Источники золота',
    transport:          'Транспорт',
    security:           'Безопасность',
    contracts:          'Контракты',
    inventory:          'Инвентарь',
    liveMap:            'Живая карта',
    analytics:          'Аналитика',
    opsProjectsNav:          'Проекты',
    opsProjectsTitle:  'Операционные проекты',
    opsShowArchived:    'Показать архивные',
    opsApplyTemplate:   'Применить шаблон…',
    opsAddProject:         '+ Добавить проект',
    opsProjectsOpen:       'открытых проектов',
    opsProjectsCompleted:  'завершено',
    opsProjectsIncArchived: '(включая архивные)',
    opsStaleBadge:      'УСТАРЕЛО',
    opsProjectsReminderToastTitle: 'Напоминание по проекту',
    opsProjectsReminderToastBody: 'Срок напоминания:',
    opsColTodo: 'К выполнению',
    opsColInProgress: 'В работе',
    opsColUnderReview: 'На проверке',
    opsColBlocked: 'Заблокировано',
    opsColDone: 'Готово',
    opsProjectsCountOne: 'проект',
    opsProjectsCountMany: 'проектов',
    opsTeamTemplateTag: '(команда)',
    opsProjectsRestrictExternal: 'Проекты недоступны для внешних поставщиков.',
    opsProjectsMetaBy: 'От',
    opsProjectsMetaUpd: 'Обн.',
    opsProjectsChecklistPct: 'Чек-лист',
    opsLinkedSupplyChain: 'Цепочка поставок',
    opsLinkedGoldSourcing: 'Золотые источники',
    opsLinkedTransport: 'Транспорт',
    opsLinkedSecurity: 'Безопасность',
    opsLinkedVendorContracts: 'Контракты поставщиков',
    opsLinkedInventory: 'Склад',
    opsModalTitleEdit: 'Редактировать проект',
    opsModalTitleAdd: 'Добавить проект',
    opsModalSubEdit: 'Обновить детали проекта',
    opsModalSubAdd: 'Создать новый операционный проект',
    opsModalSaveChanges: 'Сохранить изменения',
    opsModalSaveAdd: 'Добавить проект',
    opsModalFieldTitle: 'Название проекта',
    opsModalPlaceholderShortTitle: 'Краткое название',
    opsModalFieldAssign: 'Исполнитель',
    opsModalAssignSearchPlaceholder: 'Поиск участника команды…',
    opsModalAssignManualPlaceholder: 'Участник команды',
    opsModalFieldDescription: 'Описание',
    opsModalDescPlaceholder: 'Детали проекта…',
    opsModalFieldPriority: 'Приоритет',
    opsModalFieldDue: 'Срок',
    opsModalFieldLinked: 'Связанный раздел',
    opsModalFieldStatus: 'Статус',
    opsModalFieldReminder: 'Напоминание',
    opsModalFieldHours: 'Оценка часов / списано',
    opsModalHoursEst: 'Оценка',
    opsModalHoursLogged: 'Списано',
    opsModalFieldTags: 'Теги (через запятую)',
    opsModalTagsPlaceholder: 'например: legal, urgent',
    opsModalBlockedReason: 'Причина блокировки',
    opsModalBlockedReasonPh: 'Почему заблокировано?',
    opsModalBlockedBy: 'Блокирующий проект',
    opsModalNoneDash: '—',
    opsModalChecklistHeading: 'Чек-лист',
    opsModalChecklistStepPh: 'Название шага',
    opsModalRemoveChecklistItem: 'Удалить пункт',
    opsModalChecklistAdd: '+ Пункт чек-листа',
    opsModalDependsOn: 'Зависит от (других операционных проектов)',
    opsModalNotifyMessage: 'Текст уведомления (необязательно)',
    opsModalNotifyPlaceholder: 'Включается при сохранении / создании',
    opsModalAlsoNotify: 'Также уведомить (команда)',
    opsModalAttachments: 'Вложения',
    opsModalUploadedTitle: 'Загружено',
    opsModalUploadFailed: 'Ошибка загрузки',
    opsModalRemoveFileConfirm: 'Удалить этот файл?',
    opsModalRemovedTitle: 'Удалено',
    opsModalDeleteFailed: 'Ошибка удаления',
    opsModalRemove: 'Удалить',
    opsModalArchive: 'Архивировать проект',
    opsModalTemplateNamePrompt: 'Имя шаблона',
    opsModalMyTemplate: 'Мой шаблон',
    opsModalTemplateSavedLocal: 'Сохранено',
    opsModalTemplateLocalError: 'Не удалось сохранить шаблон',
    opsModalSaveLocalTemplate: 'Сохранить локальный шаблон',
    opsModalTemplateSavedTeam: 'Командный шаблон сохранён',
    opsModalTemplateTeamError: 'Не удалось сохранить командный шаблон',
    opsModalSaveTeamTemplate: 'В командную библиотеку',
    opsModalProgressHeading: 'Обновления прогресса',
    opsModalNoProgressYet: 'Пока нет обновлений.',
    opsModalDash: '—',
    opsModalAddProgressLabel: 'Добавить обновление',
    opsModalProgressPlaceholder: 'Что изменилось?',
    opsModalLogProgress: 'Записать обновление',
    opsPriCritical: 'Критический',
    opsPriHigh: 'Высокий',
    opsPriMedium: 'Средний',
    opsPriLow: 'Низкий',
    opsStatusTodo: 'К выполнению',
    opsStatusInProgress: 'В работе',
    opsStatusUnderReview: 'На проверке',
    opsStatusBlocked: 'Заблокировано',
    opsStatusDone: 'Готово',
    opsProjectsUpdateSingular: 'обновление',
    opsProjectsUpdatePlural: 'обновлений',
    opsProjectsDueLabel: 'Срок:',
    opsProjectsReminderSet: 'Напоминание задано',
    opsAutoArchiveHint: 'Автоархив',
    opsNoProjectsInColumn: 'Нет проектов',
    opsProjectsListViewTitle: 'Список проектов',
    opsThProject: 'Проект',
    opsThAssigned: 'Исполнитель',
    opsThPriority: 'Приоритет',
    opsThDue: 'Срок',
    opsThStatus: 'Статус',
    opsThSection: 'Раздел',
    opsThMeta: 'Мета',
    opsThActions: 'Действия',
    opsArchived: 'В архиве',
    opsBtnArchive: 'В архив',
    opsBtnDel: 'Удал.',
    opsBtnUnarchive: 'Из архива',
    opsUnarchiveConfirm: 'Восстановить проект из архива?',
    opsUnarchiveToastTitle: 'Восстановлено',
    opsArchivedProjectBanner: 'Проект в архиве и может не отображаться на доске, пока не включён показ архивных.',
    addRoute:           'Добавить маршрут',
    addVendor:          'Добавить продавца',
    addItem:            'Добавить элемент',
    eligibilityStatus:  'Статус права',
    approvalsTracker:   'Трекер согласований',
    documentation:      'Документация',
    regulatoryUpdates:  'Нормативные обновления',
    agreements:         'Соглашения',
    permit:             'Разрешение',
    entity:             'Объект',
    authority:          'Орган власти',
    filing:             'Подача',
    submittedDate:      'Дата подачи',
    refNo:              'Реф. номер',
    owner:              'Ответственный',
    version:            'Версия',
    expiry:             'Срок действия',
    impact:             'Влияние',
    actionOwner:        'Ответственный',
    partner:            'Партнёр',
    agreementType:      'Тип соглашения',
    startDate:          'Дата начала',
    endDate:            'Дата окончания',
    value:              'Стоимость',
    calendar:           'Календарь',
    batches:            'Группы',
    resources:          'Ресурсы',
    assessments:        'Оценки',
    certifications:     'Сертификаты',
    feedback:           'Обратная связь',
    trainees:           'Стажёры',
    skillGap:           'Пробелы в навыках',
    trainer:            'Тренер',
    batch:              'Группа',
    venue:              'Место',
    programme:          'Программа',
    score:              'Балл',
    pass:               'Сдал',
    fail:               'Не сдал',
    completion:         'Выполнение',
    sessionTitle:       'Название сессии',
    addSession:         'Добавить сессию',
    addBatch:           'Добавить группу',
    crmDashboard:       'Панель CRM',
    contacts:           'Контакты',
    companies:          'Компании',
    leads:              'Лиды',
    deals:              'Сделки',
    activities:         'Действия',
    followups:          'Задачи follow-up',
    addContact:         'Добавить контакт',
    addCompany:         'Добавить компанию',
    addDeal:            'Добавить сделку',
    addActivity:        'Добавить действие',
    stage:              'Этап',
    contactType:        'Тип контакта',
    leadStage:          'Этап лида',
    dealStage:          'Этап сделки',
    activityType:       'Тип действия',
    lastActivity:       'Последнее действие',
    nextAction:         'Следующий шаг',
    pipelineValue:      'Стоимость воронки',
    conversionRate:     'Конверсия',
    openDeals:          'Открытые сделки',
    closedDeals:        'Закрытые сделки',
    activeContacts:     'Активные контакты',
    searchContacts:     'Поиск контактов...',
    searchCompanies:    'Поиск компаний...',
    searchLeads:        'Поиск лидов...',
    searchDeals:        'Поиск сделок...',
    exportCsv:          'Экспорт CSV',
    importCsv:          'Импорт CSV',
    messages:           'Сообщения',
    typeMessage:        'Введите сообщение...',
    sendMessage:        'Отправить',
    groups:             'Группы',
    direct:             'Личные',
    muted:              'Без звука',
    unread:             'Непрочитанные',
    today:              'Сегодня',
    yesterday:          'Вчера',
    noMessages:         'Нет сообщений. Начните разговор!',
    attachFile:         'Прикрепить файл',
    chatSearch:         'Поиск по чатам...',
    voucherList:        'Ордера',
    createVoucher:      'Создать ордер',
    voucherNo:          'Номер документа',
    voucherDate:        'Дата ордера',
    voucherType:        'Тип ордера',
    paymentVoucher:     'Расходный ордер',
    receiptVoucher:     'Приходный ордер',
    journalVoucher:     'Журнальная запись',
    approvalWorkflow:   'Процесс согласования',
    workflowNote:       'Причина / Заметка',
    enterReason:        'Введите причину (обязательно)',
    reasonRequired:     'Причина обязательна.',
    attachments:        'Вложения',
    uploadAttachment:   'Загрузить вложение',
    noAttachments:      'Нет вложений.',
    auditLog:           'Журнал аудита',
    comments:           'Комментарии',
    addComment:         'Добавить комментарий',
    postComment:        'Опубликовать комментарий',
    moduleUnderConstruction: 'Модуль в разработке',
    plannedSections:    'Запланированные разделы',
    builtAsRequired:    'Этот раздел будет создан после подтверждения требований.',
    accounts:           'Счета',
    accountTree:        'Дерево счетов',
    allTypes:           'Все типы',
    applyFilters:       'Применить фильтры',
    cancelEdit:         'Отменить редактирование',
    deleteFailed:       'Ошибка удаления',
    exampleAccountCode: 'напр. 1010',
    failedToLoadAccounts: 'Не удалось загрузить счета',
    failedToLoadDirectDeals: 'Не удалось загрузить прямые сделки',
    fixingEntries:      'Записи с фиксингом',
    move:               'Переместить',
    noAccounts:         'Нет счетов',
    noFixingEntriesFound: 'Записи фиксинга не найдены.',
    nonFixingEntries:   'Записи без фиксинга',
    refresh:            'Обновить',
    rightClickAccountForOptions: 'Щёлкните правой кнопкой мыши для параметров',
    searchByNameOrCode: 'Поиск по имени или коду...',
    selectAccountFromTree: 'Выберите счёт из дерева',
    selectCustomer:     'Выберите клиента',
    selectType:         'Выберите тип...',
    totalAmount:        'Итоговая сумма',
    totalQty:           'Итоговое количество',
  },
}

// ── Language metadata ─────────────────────────────────────────────────────────
export const LANGUAGES = [
  { code: 'en', label: 'English',  nativeLabel: 'English',  flag: '🇬🇧', dir: 'ltr' },
  { code: 'ar', label: 'Arabic',   nativeLabel: 'عربي',      flag: '🇸🇦', dir: 'rtl' },
  { code: 'uz', label: 'Uzbek',    nativeLabel: "O'zbek",   flag: '🇺🇿', dir: 'ltr' },
  { code: 'ru', label: 'Russian',  nativeLabel: 'Русский',  flag: '🇷🇺', dir: 'ltr' },
]

// ── Context ───────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [langCode, setLangCode] = useState(() => {
    return localStorage.getItem('app_language') || 'en'
  })

  const langMeta = LANGUAGES.find(l => l.code === langCode) || LANGUAGES[0]
  const isRTL    = langMeta.dir === 'rtl'

  useEffect(() => {
    document.documentElement.dir  = langMeta.dir
    document.documentElement.lang = langCode
    document.body.dir             = langMeta.dir
  }, [langCode, langMeta.dir])

  const switchLanguage = (code) => {
    localStorage.setItem('app_language', code)
    setLangCode(code)
  }

  const t = (key) => {
    const dict = translations[langCode] || translations.en
    return dict[key] ?? translations.en[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ langCode, langMeta, isRTL, switchLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used inside <LanguageProvider>')
  return ctx
}

export default LanguageContext