/**
 * Frontend-only demo datasets for Production Control Center.
 * Never written to the database. Safe to delete with the demo/ folder.
 */

const now = Date.now()
const hoursAgo = (h) => new Date(now - h * 3600_000).toISOString()
const daysAgo = (d) => new Date(now - d * 86400_000).toISOString()

export const DEMO_WORK_ORDERS = [
  {
    _id: 'demo-wo-0142',
    woNumber: 'WO-2026-0142',
    product: 'Bridal Necklace',
    quantity: 12,
    unit: 'pcs',
    progress: 68,
    stage: 'polishing',
    status: 'in_progress',
    assignedTo: 'Priya Nair',
    targetDate: daysAgo(-5),
    createdAt: daysAgo(8),
    updatedAt: hoursAgo(2),
  },
  {
    _id: 'demo-wo-0143',
    woNumber: 'WO-2026-0143',
    product: 'Gold Chain 22K',
    quantity: 40,
    unit: 'pcs',
    progress: 35,
    stage: 'casting',
    status: 'in_progress',
    assignedTo: 'Arjun Mehta',
    targetDate: daysAgo(-3),
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(5),
  },
  {
    _id: 'demo-wo-0144',
    woNumber: 'WO-2026-0144',
    product: 'Bangles Set',
    quantity: 24,
    unit: 'pcs',
    progress: 90,
    stage: 'finishing',
    status: 'quality_check',
    assignedTo: 'Sana Khan',
    targetDate: daysAgo(-1),
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(1),
  },
  {
    _id: 'demo-wo-0145',
    woNumber: 'WO-2026-0145',
    product: 'Gold Ring',
    quantity: 60,
    unit: 'pcs',
    progress: 15,
    stage: 'casting',
    status: 'scheduled',
    assignedTo: 'Rahul Desai',
    targetDate: daysAgo(-7),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    _id: 'demo-wo-0146',
    woNumber: 'WO-2026-0146',
    product: 'Pendant',
    quantity: 18,
    unit: 'pcs',
    progress: 100,
    stage: 'completed',
    status: 'completed',
    assignedTo: 'Priya Nair',
    targetDate: daysAgo(1),
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(20),
  },
]

export const DEMO_BATCHES = [
  {
    _id: 'demo-batch-001',
    batchNumber: 'B-260901-001',
    workOrderId: 'demo-wo-0142',
    workOrderNumber: 'WO-2026-0142',
    metalType: 'Gold',
    purity: '22K',
    product: 'Bridal Necklace',
    purpose: 'Wedding collection',
    targetQuantity: 12,
    initialWeight: 4850.25,
    currentWeight: 4720.1,
    issuedWeight: 4850.25,
    receivedWeight: 4848.0,
    processInputWeight: 4848.0,
    processOutputWeight: 4720.1,
    scrapWeight: 85.4,
    lossWeight: 42.5,
    recoveredWeight: 12.0,
    currentDepartment: 'polishing',
    currentHolderName: 'Priya Nair',
    currentProcess: 'Polishing',
    currentMachineName: 'Polish-03',
    status: 'IN_PROCESS',
    startedAt: daysAgo(3),
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(1),
  },
  {
    _id: 'demo-batch-002',
    batchNumber: 'B-260901-002',
    workOrderId: 'demo-wo-0143',
    workOrderNumber: 'WO-2026-0143',
    metalType: 'Gold',
    purity: '22K',
    product: 'Gold Chain 22K',
    purpose: 'Retail chain lot',
    targetQuantity: 40,
    initialWeight: 3200,
    currentWeight: 3185.5,
    issuedWeight: 3200,
    receivedWeight: 3198,
    processInputWeight: 3198,
    processOutputWeight: 3185.5,
    scrapWeight: 8.2,
    lossWeight: 4.3,
    recoveredWeight: 0,
    currentDepartment: 'casting',
    currentHolderName: 'Arjun Mehta',
    currentProcess: 'Casting',
    currentMachineName: 'Cast-01',
    status: 'IN_PROCESS',
    startedAt: daysAgo(2),
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(3),
  },
  {
    _id: 'demo-batch-003',
    batchNumber: 'B-260901-003',
    workOrderId: 'demo-wo-0144',
    workOrderNumber: 'WO-2026-0144',
    metalType: 'Gold',
    purity: '18K',
    product: 'Bangles Set',
    purpose: 'Boutique order',
    targetQuantity: 24,
    initialWeight: 2100,
    currentWeight: 2065.75,
    issuedWeight: 2100,
    receivedWeight: 2095,
    processInputWeight: 2095,
    processOutputWeight: 2065.75,
    scrapWeight: 18.0,
    lossWeight: 11.25,
    recoveredWeight: 0,
    currentDepartment: 'quality_control',
    currentHolderName: 'Sana Khan',
    currentProcess: 'Quality Control',
    currentMachineName: '',
    status: 'QC',
    startedAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(0.5),
  },
  {
    _id: 'demo-batch-004',
    batchNumber: 'B-260901-004',
    workOrderId: 'demo-wo-0145',
    workOrderNumber: 'WO-2026-0145',
    metalType: 'Gold',
    purity: '18K',
    product: 'Gold Ring',
    purpose: 'Daily production',
    targetQuantity: 60,
    initialWeight: 1500,
    currentWeight: 1500,
    issuedWeight: 0,
    receivedWeight: 0,
    processInputWeight: 0,
    processOutputWeight: 0,
    scrapWeight: 0,
    lossWeight: 0,
    recoveredWeight: 0,
    currentDepartment: 'vault',
    currentHolderName: 'Vault Officer',
    currentProcess: '',
    currentMachineName: '',
    status: 'AWAITING_ISSUE',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: 'demo-batch-005',
    batchNumber: 'B-260901-005',
    workOrderId: 'demo-wo-0142',
    workOrderNumber: 'WO-2026-0142',
    metalType: 'Gold',
    purity: '22K',
    product: 'Bridal Necklace',
    purpose: 'Rework stone setting',
    targetQuantity: 4,
    initialWeight: 620,
    currentWeight: 615.2,
    issuedWeight: 620,
    receivedWeight: 618,
    processInputWeight: 618,
    processOutputWeight: 615.2,
    scrapWeight: 1.5,
    lossWeight: 1.3,
    recoveredWeight: 0,
    currentDepartment: 'finishing',
    currentHolderName: 'Rahul Desai',
    currentProcess: 'Finishing',
    currentMachineName: 'Finish-02',
    status: 'REWORK',
    startedAt: daysAgo(1),
    createdAt: daysAgo(7),
    updatedAt: hoursAgo(4),
  },
  {
    _id: 'demo-batch-006',
    batchNumber: 'B-260901-006',
    workOrderId: 'demo-wo-0143',
    workOrderNumber: 'WO-2026-0143',
    metalType: 'Gold',
    purity: '22K',
    product: 'Gold Chain 22K',
    purpose: 'Hold — weight variance check',
    targetQuantity: 10,
    initialWeight: 880,
    currentWeight: 872,
    issuedWeight: 880,
    receivedWeight: 878,
    processInputWeight: 878,
    processOutputWeight: 872,
    scrapWeight: 3,
    lossWeight: 3,
    recoveredWeight: 0,
    currentDepartment: 'rolling',
    currentHolderName: 'Floor Manager',
    currentProcess: 'Rolling',
    currentMachineName: 'Roll-01',
    status: 'HOLD',
    holdReason: 'Variance above tolerance',
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(6),
  },
  {
    _id: 'demo-batch-007',
    batchNumber: 'B-260831-012',
    workOrderId: 'demo-wo-0146',
    workOrderNumber: 'WO-2026-0146',
    metalType: 'Gold',
    purity: '18K',
    product: 'Pendant',
    purpose: 'Completed lot',
    targetQuantity: 18,
    initialWeight: 940,
    currentWeight: 912.4,
    issuedWeight: 940,
    receivedWeight: 938,
    processInputWeight: 938,
    processOutputWeight: 912.4,
    scrapWeight: 16.2,
    lossWeight: 9.4,
    recoveredWeight: 0,
    currentDepartment: 'packing',
    currentHolderName: 'Priya Nair',
    currentProcess: 'Packing',
    currentMachineName: '',
    status: 'COMPLETED',
    completedAt: hoursAgo(18),
    createdAt: daysAgo(12),
    updatedAt: hoursAgo(18),
  },
  {
    _id: 'demo-batch-008',
    batchNumber: 'B-260901-008',
    workOrderId: 'demo-wo-0144',
    workOrderNumber: 'WO-2026-0144',
    metalType: 'Gold',
    purity: '18K',
    product: 'Bangles Set',
    purpose: 'In transit to finishing',
    targetQuantity: 8,
    initialWeight: 710,
    currentWeight: 710,
    issuedWeight: 710,
    receivedWeight: 0,
    processInputWeight: 0,
    processOutputWeight: 0,
    scrapWeight: 0,
    lossWeight: 0,
    recoveredWeight: 0,
    currentDepartment: 'polishing',
    currentHolderName: 'Courier Desk',
    currentProcess: '',
    currentMachineName: '',
    status: 'IN_TRANSIT',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(1),
  },
]

export const DEMO_PASSES = [
  {
    _id: 'demo-pass-1',
    passNumber: 'PASS-260901-01',
    batchId: 'demo-batch-001',
    batchNumber: 'B-260901-001',
    fromDepartment: 'casting',
    toDepartment: 'polishing',
    weight: 4780,
    purpose: 'Move to polish',
    status: 'RECEIVED',
    createdAt: daysAgo(2),
  },
  {
    _id: 'demo-pass-2',
    passNumber: 'PASS-260901-02',
    batchId: 'demo-batch-008',
    batchNumber: 'B-260901-008',
    fromDepartment: 'polishing',
    toDepartment: 'finishing',
    weight: 710,
    purpose: 'Finish route',
    status: 'IN_TRANSIT',
    createdAt: hoursAgo(2),
  },
  {
    _id: 'demo-pass-3',
    passNumber: 'PASS-260901-03',
    batchId: 'demo-batch-003',
    batchNumber: 'B-260901-003',
    fromDepartment: 'finishing',
    toDepartment: 'quality_control',
    weight: 2065.75,
    purpose: 'QC inspection',
    status: 'APPROVED',
    createdAt: hoursAgo(5),
  },
  {
    _id: 'demo-pass-4',
    passNumber: 'PASS-260901-04',
    batchId: 'demo-batch-002',
    batchNumber: 'B-260901-002',
    fromDepartment: 'vault',
    toDepartment: 'casting',
    weight: 3200,
    purpose: 'Issue to casting',
    status: 'REQUESTED',
    createdAt: hoursAgo(0.5),
  },
]

export const DEMO_MOVEMENTS = [
  {
    _id: 'demo-mov-1',
    movementNumber: 'MM-260901-01',
    batchNumber: 'B-260901-001',
    fromDepartment: 'vault',
    toDepartment: 'casting',
    fromPersonName: 'Vault Officer',
    toPersonName: 'Arjun Mehta',
    weight: 4850.25,
    status: 'COMPLETED',
    purpose: 'Issue',
    createdAt: daysAgo(4),
  },
  {
    _id: 'demo-mov-2',
    movementNumber: 'MM-260901-02',
    batchNumber: 'B-260901-001',
    fromDepartment: 'casting',
    toDepartment: 'polishing',
    fromPersonName: 'Arjun Mehta',
    toPersonName: 'Priya Nair',
    weight: 4780,
    status: 'COMPLETED',
    purpose: 'Process handoff',
    createdAt: daysAgo(2),
  },
  {
    _id: 'demo-mov-3',
    movementNumber: 'MM-260901-03',
    batchNumber: 'B-260901-008',
    fromDepartment: 'polishing',
    toDepartment: 'finishing',
    fromPersonName: 'Priya Nair',
    toPersonName: 'Rahul Desai',
    weight: 710,
    status: 'IN_TRANSIT',
    purpose: 'Finish route',
    createdAt: hoursAgo(1),
  },
]

export const DEMO_PROCESSES = [
  {
    _id: 'demo-proc-1',
    processNumber: 'PR-260901-01',
    batchNumber: 'B-260901-001',
    process: 'Polishing',
    department: 'polishing',
    inputWeight: 4780,
    outputWeight: null,
    status: 'IN_PROGRESS',
    operatorName: 'Priya Nair',
    machineName: 'Polish-03',
    startTime: hoursAgo(6),
    createdAt: hoursAgo(6),
  },
  {
    _id: 'demo-proc-2',
    processNumber: 'PR-260901-02',
    batchNumber: 'B-260901-002',
    process: 'Casting',
    department: 'casting',
    inputWeight: 3198,
    outputWeight: null,
    status: 'IN_PROGRESS',
    operatorName: 'Arjun Mehta',
    machineName: 'Cast-01',
    startTime: hoursAgo(4),
    createdAt: hoursAgo(4),
  },
  {
    _id: 'demo-proc-3',
    processNumber: 'PR-260830-18',
    batchNumber: 'B-260831-012',
    process: 'Polishing',
    department: 'polishing',
    inputWeight: 930,
    outputWeight: 912.4,
    scrap: 10,
    loss: 7.6,
    status: 'COMPLETED',
    operatorName: 'Priya Nair',
    machineName: 'Polish-02',
    startTime: daysAgo(3),
    endTime: daysAgo(2),
    createdAt: daysAgo(3),
  },
]

export const DEMO_QC = [
  {
    _id: 'demo-qc-1',
    inspectionNumber: 'QC-260901-01',
    batchNumber: 'B-260901-003',
    result: 'HOLD',
    inspectorName: 'Sana Khan',
    remarks: 'Finish check pending stone alignment',
    createdAt: hoursAgo(1),
  },
  {
    _id: 'demo-qc-2',
    inspectionNumber: 'QC-260831-09',
    batchNumber: 'B-260831-012',
    result: 'PASS',
    inspectorName: 'Sana Khan',
    remarks: 'Within tolerance',
    createdAt: hoursAgo(20),
  },
  {
    _id: 'demo-qc-3',
    inspectionNumber: 'QC-260901-02',
    batchNumber: 'B-260901-005',
    result: 'FAIL',
    inspectorName: 'QC Lead',
    remarks: 'Setting misalignment — rework',
    createdAt: hoursAgo(8),
  },
  {
    _id: 'demo-qc-4',
    inspectionNumber: 'QC-260901-03',
    batchNumber: 'B-260901-005',
    result: 'REWORK',
    inspectorName: 'QC Lead',
    remarks: 'Sent to finishing rework',
    createdAt: hoursAgo(7),
  },
]

export const DEMO_MACHINES = [
  {
    _id: 'demo-m-1',
    machineCode: 'CAST-01',
    name: 'Cast-01',
    department: 'casting',
    process: 'Casting',
    status: 'RUNNING',
    currentBatchNumber: 'B-260901-002',
    currentOperatorName: 'Arjun Mehta',
    lastMaintenance: daysAgo(20),
    nextMaintenance: daysAgo(-10),
    isActive: true,
  },
  {
    _id: 'demo-m-2',
    machineCode: 'POL-03',
    name: 'Polish-03',
    department: 'polishing',
    process: 'Polishing',
    status: 'RUNNING',
    currentBatchNumber: 'B-260901-001',
    currentOperatorName: 'Priya Nair',
    lastMaintenance: daysAgo(12),
    nextMaintenance: daysAgo(-18),
    isActive: true,
  },
  {
    _id: 'demo-m-3',
    machineCode: 'ROLL-01',
    name: 'Roll-01',
    department: 'rolling',
    process: 'Rolling',
    status: 'IDLE',
    currentBatchNumber: '',
    currentOperatorName: '',
    lastMaintenance: daysAgo(5),
    nextMaintenance: daysAgo(-25),
    isActive: true,
  },
  {
    _id: 'demo-m-4',
    machineCode: 'FIN-02',
    name: 'Finish-02',
    department: 'finishing',
    process: 'Finishing',
    status: 'MAINTENANCE',
    currentBatchNumber: '',
    currentOperatorName: '',
    lastMaintenance: hoursAgo(2),
    nextMaintenance: daysAgo(-30),
    isActive: true,
  },
  {
    _id: 'demo-m-5',
    machineCode: 'CAST-02',
    name: 'Cast-02',
    department: 'casting',
    process: 'Casting',
    status: 'FAULT',
    currentBatchNumber: '',
    currentOperatorName: '',
    lastMaintenance: daysAgo(40),
    nextMaintenance: daysAgo(5),
    isActive: true,
  },
]

export const DEMO_ALERTS = [
  {
    _id: 'demo-alert-1',
    alertNumber: 'AL-260901-01',
    title: 'Weight variance on hold',
    message: 'Batch B-260901-006 exceeded configured tolerance during rolling.',
    severity: 'critical',
    status: 'OPEN',
    createdAt: hoursAgo(6),
  },
  {
    _id: 'demo-alert-2',
    alertNumber: 'AL-260901-02',
    title: 'Machine fault',
    message: 'Cast-02 reported FAULT — cooling circuit.',
    severity: 'warning',
    status: 'ACKNOWLEDGED',
    createdAt: hoursAgo(3),
  },
  {
    _id: 'demo-alert-3',
    alertNumber: 'AL-260901-03',
    title: 'QC fail → rework',
    message: 'B-260901-005 failed QC and entered rework.',
    severity: 'warning',
    status: 'OPEN',
    createdAt: hoursAgo(8),
  },
]

export const DEMO_AUDIT = [
  {
    _id: 'demo-aud-1',
    createdAt: hoursAgo(1),
    actorName: 'Priya Nair',
    actorRole: 'operator',
    action: 'PROCESS_STARTED',
    resource: 'ProcessRun',
    detail: 'Polishing started on B-260901-001',
  },
  {
    _id: 'demo-aud-2',
    createdAt: hoursAgo(3),
    actorName: 'Floor Manager',
    actorRole: 'floor_manager',
    action: 'BATCH_HOLD',
    resource: 'ProductionBatch',
    detail: 'B-260901-006 put on HOLD — variance',
  },
  {
    _id: 'demo-aud-3',
    createdAt: hoursAgo(7),
    actorName: 'QC Lead',
    actorRole: 'qc_inspector',
    action: 'QC_FAILED',
    resource: 'QcInspection',
    detail: 'QC FAIL on B-260901-005',
  },
  {
    _id: 'demo-aud-4',
    createdAt: hoursAgo(18),
    actorName: 'Priya Nair',
    actorRole: 'operator',
    action: 'BATCH_COMPLETED',
    resource: 'ProductionBatch',
    detail: 'B-260831-012 marked COMPLETED',
  },
  {
    _id: 'demo-aud-5',
    createdAt: daysAgo(4),
    actorName: 'Vault Officer',
    actorRole: 'vault_officer',
    action: 'METAL_ISSUED',
    resource: 'ProductionBatch',
    detail: 'Issued 4850.25 g to B-260901-001',
  },
]

export const DEMO_FLOW = {
  stages: [
    { key: 'vault', label: 'Vault', order: 0 },
    { key: 'melting', label: 'Melting', order: 1 },
    { key: 'casting', label: 'Casting', order: 2 },
    { key: 'rolling', label: 'Rolling', order: 3 },
    { key: 'polishing', label: 'Polishing', order: 4 },
    { key: 'finishing', label: 'Finishing', order: 5 },
    { key: 'quality_control', label: 'Quality Control', order: 6 },
    { key: 'packing', label: 'Packing', order: 7 },
    { key: 'vault_return', label: 'Vault', order: 8 },
  ],
}

function boardFromBatches(batches) {
  const map = {
    QUEUED: ['CREATED', 'AWAITING_ISSUE', 'ISSUED', 'WAITING'],
    IN_PROGRESS: ['IN_TRANSIT', 'RECEIVED', 'IN_PROCESS'],
    QC: ['QC'],
    REWORK: ['REWORK'],
    HOLD: ['HOLD'],
    COMPLETED: ['COMPLETED', 'RETURNED_TO_VAULT'],
  }
  const board = Object.fromEntries(Object.keys(map).map((k) => [k, []]))
  for (const b of batches) {
    const col = Object.entries(map).find(([, statuses]) => statuses.includes(b.status))?.[0]
    if (col) board[col].push(b)
  }
  return board
}

export function getDemoLiveFloor() {
  const active = DEMO_BATCHES.filter((b) => !['COMPLETED', 'RETURNED_TO_VAULT', 'CANCELLED'].includes(b.status))
  const metalInProduction = active.reduce((s, b) => s + Number(b.currentWeight || 0), 0)
  const scrapTotal = DEMO_BATCHES.reduce((s, b) => s + Number(b.scrapWeight || 0), 0)
  const lossTotal = DEMO_BATCHES.reduce((s, b) => s + Number(b.lossWeight || 0), 0)
  const recoveredTotal = DEMO_BATCHES.reduce((s, b) => s + Number(b.recoveredWeight || 0), 0)

  return {
    success: true,
    kpis: {
      activeWorkOrders: DEMO_WORK_ORDERS.filter((w) => !['completed', 'cancelled'].includes(w.status)).length,
      activeBatches: active.length,
      metalInProduction,
      waiting: DEMO_BATCHES.filter((b) => b.status === 'WAITING' || b.status === 'AWAITING_ISSUE').length,
      qcPending: DEMO_BATCHES.filter((b) => b.status === 'QC').length,
      qcFailed: DEMO_QC.filter((q) => q.result === 'FAIL').length,
      onHold: DEMO_BATCHES.filter((b) => b.status === 'HOLD').length,
      activeAlerts: DEMO_ALERTS.filter((a) => a.status !== 'RESOLVED').length,
      machinesRunning: DEMO_MACHINES.filter((m) => m.status === 'RUNNING').length,
      passesPending: DEMO_PASSES.filter((p) => !['RECEIVED', 'COMPLETED', 'CANCELLED'].includes(p.status)).length,
      completedToday: DEMO_BATCHES.filter((b) => b.status === 'COMPLETED').length,
      returnedToday: 0,
      scrapTotal,
      lossTotal,
      recoveredTotal,
    },
    board: boardFromBatches(DEMO_BATCHES),
    statusCounts: Object.entries(
      DEMO_BATCHES.reduce((acc, b) => {
        acc[b.status] = (acc[b.status] || 0) + 1
        return acc
      }, {}),
    ).map(([status, count]) => ({
      status,
      count,
      weight: DEMO_BATCHES.filter((b) => b.status === status).reduce((s, b) => s + Number(b.currentWeight || 0), 0),
    })),
    activeBatches: active.slice(0, 50),
    custody: [
      { person: 'Priya Nair', department: 'polishing', metalType: 'Gold', purity: '22K', weight: 4720.1, batches: 1 },
      { person: 'Arjun Mehta', department: 'casting', metalType: 'Gold', purity: '22K', weight: 3185.5, batches: 1 },
      { person: 'Sana Khan', department: 'quality_control', metalType: 'Gold', purity: '18K', weight: 2065.75, batches: 1 },
    ],
    metalByDepartment: [
      { department: 'polishing', metalType: 'Gold', weight: 5430.1 },
      { department: 'casting', metalType: 'Gold', weight: 3185.5 },
      { department: 'quality_control', metalType: 'Gold', weight: 2065.75 },
      { department: 'vault', metalType: 'Gold', weight: 1500 },
      { department: 'finishing', metalType: 'Gold', weight: 615.2 },
      { department: 'rolling', metalType: 'Gold', weight: 872 },
    ],
    attention: DEMO_ALERTS.filter((a) => a.status !== 'RESOLVED'),
    recentActivity: DEMO_MOVEMENTS,
  }
}

export function getDemoBatchDetail(batchId) {
  const batch = DEMO_BATCHES.find((b) => b._id === batchId)
  if (!batch) return null
  const expectedWeight = Number(batch.initialWeight || 0) - Number(batch.lossWeight || 0)
  const actualWeight = Number(batch.currentWeight || 0)
  const difference = actualWeight - expectedWeight
  const variancePct = expectedWeight > 0 ? (Math.abs(difference) / expectedWeight) * 100 : 0
  return {
    success: true,
    batch,
    movements: DEMO_MOVEMENTS.filter((m) => m.batchNumber === batch.batchNumber),
    passes: DEMO_PASSES.filter((p) => p.batchNumber === batch.batchNumber),
    processes: DEMO_PROCESSES.filter((p) => p.batchNumber === batch.batchNumber),
    qc: DEMO_QC.filter((q) => q.batchNumber === batch.batchNumber),
    adjustments: [],
    audits: DEMO_AUDIT.filter((a) => String(a.detail || '').includes(batch.batchNumber)),
    timeline: [
      { at: batch.createdAt, type: 'created', label: `Batch ${batch.batchNumber} created` },
      ...(batch.startedAt ? [{ at: batch.startedAt, type: 'started', label: 'Production started' }] : []),
      ...(batch.completedAt ? [{ at: batch.completedAt, type: 'completed', label: 'Batch completed' }] : []),
    ],
    weightReconciliation: {
      initialWeight: batch.initialWeight,
      issuedWeight: batch.issuedWeight,
      receivedWeight: batch.receivedWeight,
      processInput: batch.processInputWeight,
      processOutput: batch.processOutputWeight,
      scrap: batch.scrapWeight,
      loss: batch.lossWeight,
      recovered: batch.recoveredWeight,
      currentWeight: batch.currentWeight,
      expectedWeight,
      actualWeight,
      difference,
      variancePct,
    },
  }
}

export function getDemoWorkOrdersSummary() {
  const byWorkOrder = DEMO_WORK_ORDERS.map((wo) => {
    const linked = DEMO_BATCHES.filter((b) => b.workOrderId === wo._id)
    return {
      workOrderId: wo._id,
      workOrderNumber: wo.woNumber,
      batchCount: linked.length,
      activeCount: linked.filter((b) => !['COMPLETED', 'RETURNED_TO_VAULT', 'CANCELLED'].includes(b.status)).length,
      metalWeight: linked.reduce((s, b) => s + Number(b.currentWeight || 0), 0),
    }
  })
  return { success: true, byWorkOrder }
}
