import { StyleSheet } from 'react-native'
import type { MobileTenantBranding } from '@/src/config/tenantBranding'

export function createOperationsStyles(b: MobileTenantBranding) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: b.colors.background },
    center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    deniedTitle: { fontSize: 18, fontWeight: '700', color: b.colors.text, marginBottom: 8 },
    deniedText: { fontSize: 14, color: b.colors.muted, textAlign: 'center' },
    sectionTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: b.colors.text,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 4,
    },
    subHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
    },
    backBtn: { padding: 8 },
    backText: { fontSize: 22, color: b.colors.text, fontWeight: '600' },
    subHeaderTitle: { flex: 1, fontSize: 16, fontWeight: '700', color: b.colors.text },
    note: { fontSize: 12, color: b.colors.muted, paddingHorizontal: 16, marginBottom: 6 },
    error: { color: b.colors.danger, paddingHorizontal: 16, marginBottom: 8 },
    listContent: { paddingBottom: 32 },
    sectionHeader: {
      fontSize: 13,
      fontWeight: '700',
      color: b.colors.muted,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 6,
      backgroundColor: b.colors.background,
    },
    empty: { textAlign: 'center', color: b.colors.muted, padding: 32, fontSize: 14 },
    cappedNote: { textAlign: 'center', color: b.colors.muted, padding: 16, fontSize: 12 },
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    modalCard: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 16,
      maxHeight: '85%',
    },
    modalCardCompact: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
      maxHeight: '42%',
    },
    modalCardSheet: {
      minHeight: 0,
    },
    filterSheetList: {
      maxHeight: 260,
    },
    filterSheetListAccounts: {
      maxHeight: 240,
    },
    refreshBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 6,
    },
    refreshBannerText: {
      fontSize: 12,
      color: b.colors.muted,
    },
    modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12, color: b.colors.text },
    input: {
      borderWidth: 1,
      borderColor: '#E5E7EB',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: b.colors.text,
      backgroundColor: '#FAFAFA',
      marginBottom: 10,
    },
    sheetOption: {
      paddingVertical: 11,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: '#E5E7EB',
    },
    sheetOptionText: { fontSize: 15, color: b.colors.text },
    sheetOptionActive: { fontWeight: '700', color: b.colors.primary },
    accountRow: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E5E7EB' },
    accountRowCode: { fontSize: 13, fontWeight: '700', color: b.colors.text },
    accountRowName: { fontSize: 12, color: b.colors.muted, marginTop: 2 },
    analysisHero: { paddingHorizontal: 16, paddingVertical: 12 },
    analysisHeroAmount: { fontSize: 28, fontWeight: '800' },
    analysisHeroLabel: { fontSize: 14, color: b.colors.muted, marginTop: 4 },
    categoryHeader: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8 },
    categoryHeroAmount: { fontSize: 26, fontWeight: '800', color: b.colors.danger, marginTop: 4 },
    categoryHeroPeriod: { fontSize: 14, color: b.colors.muted, marginTop: 2 },
    categoryHeroTitle: { fontSize: 18, fontWeight: '700', color: b.colors.text },
    closeBtn: {
      marginTop: 12,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      alignItems: 'center',
    },
    closeBtnText: { fontWeight: '700', color: b.colors.text },
    detailLine: { fontSize: 14, color: b.colors.text, marginBottom: 8, lineHeight: 20 },
    detailLabel: { fontWeight: '700' },
  })
}

export type OperationsStyles = ReturnType<typeof createOperationsStyles>
