const BATCH_ENTRY_DIRECTIONS = ['IN', 'OUT']
const BATCH_ENTRY_STATUSES = ['PENDING', 'APPROVED', 'REJECTED']
const BATCH_ENTRY_MAX_LINES = 8

module.exports = {
  BATCH_ENTRY_DIRECTIONS,
  BATCH_ENTRY_STATUSES,
  BATCH_ENTRY_MAX_LINES,
}
